/**
 * THESIS: a person's permitted work and relationships lead; machines explain reachability.
 * OWN-WORLD: Scout's neutral canvas, lime action signal, compact rows and quiet hairlines.
 * STORY: sign in, see current scope, choose a project/agent, then manage explicit access.
 * FIRST VIEWPORT: narrow navigation, network heading, project/work rows, scope sidebar.
 * FORM: extend the existing Scout Operate surface; no new visual identity or metric tiles.
 */
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Network, Users, Bot, Laptop, ArrowRight, RefreshCw, LogOut, Plus, ShieldCheck } from "lucide-react";
import { ScoutMark } from "../components/ScoutMark.tsx";
import { accessApi, AccessApiError } from "./api.ts";
import type { Agent, Delegation, Grant, NetworkState, Principal, Scope, Session, Work } from "./types.ts";
import "./access.css";
type Tab = "network" | "people" | "services" | "devices";
const tabs = [{ id: "network", label: "Network", Icon: Network }, { id: "people", label: "People", Icon: Users }, { id: "services", label: "Services", Icon: Bot }, { id: "devices", label: "Devices", Icon: Laptop }] as const;
const emptyScope = (): Scope => ({ all: false, agentIds: [], projectIds: [] });
const short = (id: string) => id.length > 18 ? `${id.slice(0, 8)}…${id.slice(-6)}` : id;
const expiry = (time: number) => new Date(time).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
const localTime = (time: number) => new Date(time - new Date(time).getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const labelFor = (state: NetworkState, id: string) => state.principals.find((p) => p.principal.id === id)?.principal.label ?? short(id);
function Notice({ children }: { children: ReactNode }) { return <p className="access-notice">{children}</p>; }
export function AccessPane() {
  const [session, setSession] = useState<Session | null>(null), [state, setState] = useState<NetworkState | null>(null), [work, setWork] = useState<Work[]>([]);
  const [offset, setOffset] = useState(0), [tab, setTab] = useState<Tab>("network"), [selected, setSelected] = useState<string | null>(null), [error, setError] = useState("");
  const [busy, setBusy] = useState(false), [updated, setUpdated] = useState<number | null>(null), [adding, setAdding] = useState(false), [result, setResult] = useState<string | null>(null);
  const refreshGeneration = useRef(0);
  const [signing, setSigning] = useState<{ preview: any; resolve: (value: any) => void; reject: (error: Error) => void } | null>(null);
  const rpc = useCallback(<T,>(payload: unknown) => accessApi<T>("rpc", payload, session?.csrf), [session?.csrf]);
  const refresh = useCallback(async () => {
    if (!session?.authenticated) return;
    const generation = ++refreshGeneration.current;
    try {
      const [next, items] = await Promise.all([rpc<NetworkState>({ operation: "network.status", offset }), rpc<{ work: Work[] }>({ operation: "work.list" })]);
      if (generation !== refreshGeneration.current) return;
      setState(next); setWork(items.work); setUpdated(Date.now()); setError("");
    } catch (cause) { if (generation !== refreshGeneration.current) return; setState(null); setWork([]); setError(String((cause as Error).message)); if (cause instanceof AccessApiError && (cause.status === 401 || cause.code === "csrf_required")) { setSession(await accessApi<Session>("session").catch(() => ({ authenticated: false }))); } }
  }, [session?.authenticated, rpc, offset]);
  useEffect(() => { void accessApi<Session>("session").then(setSession).catch(() => { setSession({ authenticated: false }); setError("The isolated access server is unavailable. Open the configured access address; this pane does not use local operator access."); }); }, []);
  useEffect(() => { void refresh(); if (!session?.authenticated) return; const timer = setInterval(() => void refresh(), 20000); return () => clearInterval(timer); }, [refresh, session?.authenticated]);
  async function manage(payload: unknown) {
    setBusy(true); setError("");
    try {
      const preview = await accessApi<any>("manage/preview", payload, session?.csrf);
      const data = await new Promise<any>((resolve, reject) => setSigning({ preview, resolve, reject }));
      await refresh(); return data;
    } catch (cause) { setError((cause as Error).message); throw cause; }
    finally { setBusy(false); setSigning(null); }
  }
  async function revoke(payload: Record<string, unknown>, name: string) {
    // The server-produced preview confirms the exact revocation and requires step-up.
    await manage({ action: "revoke", ...payload }).catch(() => {});
  }
  const canSign = Boolean(session?.user?.canSign ?? session?.canSign), selectedPrincipal = state?.principals.find((p) => p.principal.id === selected);
  return <div className="access-shell" data-scout-theme>
    {signing && <SigningDialog state={state} preview={signing.preview} onCancel={() => signing.reject(new Error(""))} onConfirm={async (password) => { const result = await accessApi("manage", { previewId: signing.preview.previewId, password }, session?.csrf); signing.resolve(result); }} />}
    <aside className="access-nav"><a className="access-brand" href="/access"><ScoutMark />Scout</a><div className="access-nav-label">Your network</div>
      <nav aria-label="Access control">{tabs.map(({ id, label, Icon }) => <button key={id} aria-current={tab === id ? "page" : undefined} onClick={() => { refreshGeneration.current++; setTab(id); setOffset(0); setSelected(null); setAdding(false); setResult(null); }}><Icon size={17} />{label}</button>)}</nav>
      <div className="access-nav-footer"><ShieldCheck size={17} /><span>Explicit access<br /><small>One identity. Defined scope.</small></span></div>
    </aside>
    <div className="access-content"><header className="access-topbar"><span>OpenScout / {tabs.find((t) => t.id === tab)?.label}</span>{session?.authenticated && <div><span>{state?.viewer.principal.label ?? session.user?.login}</span><button aria-label="Sign out" title="Sign out" onClick={async () => { refreshGeneration.current++; try { await accessApi("logout", {}, session.csrf); } finally { setState(null); setWork([]); setSession(await accessApi<Session>("session").catch(() => ({ authenticated: false }))); } }}><LogOut size={16} /></button></div>}</header>
      <main className="access-main">{error && <div className="access-error" role="alert">{error}</div>}
        {session === null ? <p role="status">Connecting to your access server…</p> : !session.authenticated ? <Login csrf={session.csrf} onLogin={setSession} onError={setError} /> : !state ? <section className="access-empty"><h1>Your network is unavailable</h1><p>Access may have expired or changed. Renew your approved device through the CLI, then refresh.</p><button onClick={() => void refresh()}><RefreshCw size={15} />Try again</button></section> : <>
          <div className="access-heading"><div><p className="access-eyebrow">{state.network.label} <span className="access-role">{state.viewer.role}</span></p><h1>{tab === "network" ? "Your network, in view" : tab === "people" ? "People" : tab === "services" ? "Services" : "Approved devices"}</h1><p>{tab === "network" ? "The projects and agents you can reach, and the work you own." : tab === "devices" ? "Devices act for an identity within an expiring scope." : "Choose an identity to inspect its access and share specific resources."}</p></div><div className="access-heading-actions"><button aria-label="Refresh access" disabled={busy} onClick={() => void refresh()}><RefreshCw size={16} />Refresh</button>{tab !== "network" && ((tab === "devices" && canSign) || (tab !== "devices" && state.canAdmin)) && <button className="access-primary" onClick={() => setAdding(!adding)}><Plus size={16} />{tab === "devices" ? "Approve device" : "Import signed policy"}</button>}</div></div>
          <div className="access-freshness"><span>Policy {state.network.revision} · expires {expiry(state.network.expiresAt)}</span><span>{updated ? `Checked ${new Date(updated).toLocaleTimeString()}` : "Checking…"}</span></div>
          {!canSign && <Notice>This login has no principal signing key configured. You can inspect access and use your approved device; policy changes remain available through the CLI.</Notice>}
          {adding && (tab === "devices" ? <DeviceForm state={state} busy={busy} onSave={manage} onClose={() => setAdding(false)} /> : <SignedPolicyForm busy={busy} onSave={manage} onClose={() => setAdding(false)} />)}
          {tab === "network" && <div className="access-overview"><section><h2>Projects & agents</h2><ProjectList state={state} onSelect={(agent) => { setSelected(agent.id); setResult(null); }} selected={selected} />
            <div className="access-section-title"><h2>Your work</h2><span>Most recent 100 requests</span></div>{work.length ? <div className="access-rows">{work.map((item) => <button className="access-work" key={item.id} onClick={async () => { try { const data = await rpc<any>({ operation: "result", workId: item.id }); setResult(data.output ?? data.summary ?? data.error ?? "No result yet. Refresh while this request is running."); } catch (cause) { setError((cause as Error).message); } }}><span><strong>{state.resources.agents.find((a) => a.id === item.agentId)?.displayName ?? item.agentId}</strong><small>{item.summary || "Open request result"}</small></span><span className="access-state">{item.state}</span><ArrowRight size={15} /></button>)}</div> : <div className="access-empty compact"><p>No readable work yet.</p><small>Request work from a permitted agent. Results belong to your identity and remain subject to current access.</small></div>}
            {result !== null && <section className="access-result"><div className="access-section-title"><h2>Request result</h2><button onClick={() => setResult(null)}>Close</button></div><pre>{result}</pre></section>}
          </section><aside className="access-context">{selected && state.resources.agents.some((a) => a.id === selected) ? <RequestForm agent={state.resources.agents.find((a) => a.id === selected)!} boundary={state.executionBoundary} onSend={async (payload) => { await rpc(payload); await refresh(); }} /> : <><h2>Your current scope</h2><p>{state.canAdmin ? "You can administer resources explicitly enrolled into this network." : "Only shared resources and actions appear here. Hidden projects and agent counts are not exposed."}</p><dl><dt>Identity</dt><dd>{state.viewer.principal.label}</dd><dt>Broker</dt><dd>Direct home-broker connection</dd><dt>Availability</dt><dd>Registered agents; live harness readiness is not inferred</dd></dl><Notice>{state.executionBoundary}</Notice></>}</aside></div>}
          {(tab === "people" || tab === "services") && <div className="access-split"><section className="access-rows">{state.principals.filter((p) => p.principal.kind === (tab === "people" ? "person" : "service")).map((p) => <button className={`access-person ${selected === p.principal.id ? "is-selected" : ""}`} key={p.principal.id} onClick={() => setSelected(p.principal.id)}><span className="access-avatar">{p.principal.label.slice(0, 1).toUpperCase()}</span><span><strong>{p.principal.label}</strong><small>{short(p.principal.id)}</small></span><span className="access-state">{state.revokedPrincipalIds.includes(p.principal.id) ? "Revoked" : p.role}</span><ArrowRight size={15} /></button>)}{!state.principals.some((p) => p.principal.kind === (tab === "people" ? "person" : "service")) && <div className="access-empty"><h2>No {tab} visible</h2><p>{state.canAdmin ? "Import a CLI-signed policy to add an identity." : "Your session shows only your own identity."}</p></div>}</section>
          <aside className="access-detail">{selectedPrincipal ? <PrincipalDetail state={state} principal={selectedPrincipal.principal} role={selectedPrincipal.role} canSign={canSign} busy={busy} manage={manage} revoke={revoke} rpc={rpc} /> : <div className="access-empty"><h2>Choose an identity</h2><p>Inspect role, grants, devices and effective access before making changes.</p></div>}</aside></div>}
          {tab === "devices" && <section className="access-rows">{state.delegations.length ? state.delegations.map((d) => {
            const device = state.devices.find((entry) => entry.publicKey === d.devicePublicKey), id = device?.keyId;
            const revoked = state.revokedDelegationIds.includes(`${d.principalId}:${d.id}`) || Boolean(id && state.revokedDeviceIds.includes(id)) || state.signedRevocations.some((r) => r.artifact.issuerId === d.principalId && ((r.artifact.targetKind === "delegation" && r.artifact.targetId === d.id) || (id && r.artifact.targetKind === "device" && r.artifact.targetId === id)));
            const mayRevoke = canSign && d.principalId === state.viewer.principal.id;
            return <div className="access-device" key={`${d.principalId}:${d.id}`}><Laptop size={19} /><div><strong>{d.id}</strong><small>{labelFor(state, d.principalId)} · {id ? short(id) : "Possession not recorded on this page"}</small><small>{d.actions.join(" · ")} · expires {expiry(d.expiresAt)}</small></div><span className="access-state">{revoked ? "Revoked" : d.expiresAt <= Date.now() ? "Expired" : "Approved"}</span>{mayRevoke && !revoked && <button onClick={() => void revoke({ kind: "delegation", id: d.id, principalId: d.principalId }, d.id)}>Revoke delegation</button>}{mayRevoke && id && !revoked && <button className="access-danger" onClick={() => void revoke({ kind: "device", id, principalId: d.principalId }, "this device and future delegations")}>Revoke device</button>}</div>;
          }) : <div className="access-empty"><h2>No device certificates recorded</h2><p>Approve a public device key or make the device’s first signed request through the CLI.</p></div>}<Notice>Delegation revocation stops one certificate. Device revocation stops this identity using that key, including renewed certificates. Self-revocation can be delivered before first use; each receiving broker must receive the signed change.</Notice></section>}
        </>}
      {state?.pagination && <div className="access-pagination"><button disabled={offset === 0} onClick={() => { refreshGeneration.current++; setOffset(Math.max(0, offset - 100)); setSelected(null); }}>Previous page</button><span>Page {offset / 100 + 1} · up to 100 records per collection</span><button disabled={state.pagination.nextOffset === null} onClick={() => { refreshGeneration.current++; setOffset(state.pagination?.nextOffset ?? offset); setSelected(null); }}>Next page</button></div>}
      </main></div>
  </div>;
}
function Login({ csrf, onLogin, onError }: { csrf?: string; onLogin: (session: Session) => void; onError: (error: string) => void }) {
  const [login, setLogin] = useState(""), [password, setPassword] = useState(""), [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); onError(""); try { onLogin(await accessApi<Session>("login", { login, password }, csrf)); setPassword(""); } catch (cause) { onError((cause as Error).message); if (cause instanceof AccessApiError && cause.code === "csrf_required") onLogin(await accessApi<Session>("session")); } finally { setBusy(false); } }
  return <section className="access-login"><ShieldCheck size={27} /><h1>Sign in to your network</h1><p>Use the login configured for this isolated access server. Your mesh signing keys stay on the server.</p><form onSubmit={submit}><label>Login<input autoComplete="username" required value={login} onChange={(e) => setLogin(e.target.value)} /></label><label>Password<input autoComplete="current-password" type="password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="access-primary" disabled={busy}>{busy ? "Signing in…" : "Sign in"}<ArrowRight size={16} /></button></form><small>Hosted sign-in and recovery are not linked to this network. Ask its operator for an explicitly configured login.</small></section>;
}
function ProjectList({ state, selected, onSelect }: { state: NetworkState; selected: string | null; onSelect: (agent: Agent) => void }) {
  const groups = new Map<string, Agent[]>(); for (const agent of state.resources.agents) { const group = agent.projectId ?? "selected-agents"; groups.set(group, [...(groups.get(group) ?? []), agent]); }
  if (!groups.size) return <div className="access-empty"><h2>No resources shared yet</h2><p>An admin can grant access after resources are explicitly enrolled through the CLI.</p></div>;
  return <div className="access-projects">{[...groups].map(([name, agents]) => <section key={name}><h3>{agents[0]?.projectName ?? "Selected agents"}</h3>{agents.map((agent) => <button key={agent.id} className={`access-agent ${selected === agent.id ? "is-selected" : ""}`} onClick={() => onSelect(agent)}><Bot size={18} /><span><strong>{agent.displayName}</strong><small>{agent.actions.filter((a) => a !== "discover").map((a) => a === "message" ? "Leave a message" : a === "read-own" ? "Read own results" : a === "request" ? "Request work" : a).join(" · ") || "Discovery only"}</small></span><ArrowRight size={16} /></button>)}</section>)}</div>;
}
function ScopeFields({ state, scope, onChange }: { state: NetworkState; scope: Scope; onChange: (scope: Scope) => void }) {
  const toggle = (kind: "agentIds" | "projectIds", id: string) => onChange({ ...scope, [kind]: scope[kind].includes(id) ? scope[kind].filter((item) => item !== id) : [...scope[kind], id] });
  return <fieldset><legend>Resources</legend><label className="access-check"><input type="checkbox" checked={scope.all} onChange={(e) => onChange(e.target.checked ? { all: true, agentIds: [], projectIds: [] } : emptyScope())} />All enrolled resources</label>{scope.all ? <Notice>This includes every resource now enrolled and resources enrolled later.</Notice> : <><div className="access-scope-group"><strong>Projects</strong><small>Includes future agents in each selected project.</small>{state.resources.projects.map((p) => <label className="access-check" key={p.id}><input type="checkbox" checked={scope.projectIds.includes(p.id)} onChange={() => toggle("projectIds", p.id)} />{p.name}</label>)}</div><div className="access-scope-group"><strong>Additional agents</strong>{state.resources.agents.map((a) => <label className="access-check" key={a.id}><input type="checkbox" checked={scope.agentIds.includes(a.id)} onChange={() => toggle("agentIds", a.id)} />{a.displayName}</label>)}</div><small>Projects and selected agents are combined. An empty selection grants no access.</small></>}</fieldset>;
}
function ActionFields({ actions, onChange, boundary, permitted, allowAdmin = false }: { actions: string[]; onChange: (actions: string[]) => void; boundary: string; permitted?: string[]; allowAdmin?: boolean }) {
  return <fieldset><legend>Actions</legend>{[["discover", "See availability"], ["message", "Leave a message · no wake"], ["request", "Request work · may wake agent"], ["read-own", "Read this identity’s results"], ...(allowAdmin ? [["admin", "Manage access · all-resource delegation required"]] : [])].map(([id, label]) => <label className="access-check" key={id}><input type="checkbox" disabled={permitted !== undefined && !permitted.includes(id!)} checked={actions.includes(id!)} onChange={() => onChange(actions.includes(id!) ? actions.filter((a) => a !== id) : [...actions, id!])} />{label}</label>)}{actions.includes("request") && <Notice>{boundary}</Notice>}</fieldset>;
}
function SignedPolicyForm({ busy, onSave, onClose }: { busy: boolean; onSave: (payload: unknown) => Promise<any>; onClose: () => void }) {
  const [value, setValue] = useState(""), [error, setError] = useState("");
  return <form className="access-editor" onSubmit={async (e) => { e.preventDefault(); try { const artifact = JSON.parse(value); if (artifact.privateKey || artifact.identity || artifact.kind !== "policy") throw new Error("Paste only a signed public policy artifact."); await onSave({ action: "policy.submit", artifact }); onClose(); } catch (cause) { setError((cause as Error).message); } }}><h2>Import a signed membership policy</h2><p>Membership and roles are signed by the network root through the CLI. This gateway never holds that root key. Paste the resulting public policy; the broker verifies its signature and increasing revision.</p><label>Signed policy JSON<textarea required rows={8} value={value} onChange={(e) => setValue(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<div className="access-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="access-primary" disabled={busy}>Review signed policy</button></div></form>;
}
function PrincipalDetail({ state, principal, role, canSign, busy, manage, revoke, rpc }: { state: NetworkState; principal: Principal; role: string; canSign: boolean; busy: boolean; manage: (payload: unknown) => Promise<any>; revoke: (payload: Record<string, unknown>, name: string) => Promise<void>; rpc: <T>(payload: unknown) => Promise<T> }) {
  const [editing, setEditing] = useState<Grant | "new" | null>(null), [preview, setPreview] = useState<Agent[] | null>(null), [previewError, setPreviewError] = useState("");
  useEffect(() => { setEditing(null); setPreview(null); setPreviewError(""); }, [principal.id]);
  const grants = state.grants.filter((g) => g.subjectId === principal.id), devices = state.delegations.filter((d) => d.principalId === principal.id);
  const revoked = state.revokedPrincipalIds.includes(principal.id);
  return <><div className="access-section-title"><h2>{principal.label}</h2><span className="access-role">{revoked ? "Revoked" : role}</span></div><code className="access-key">{principal.id}</code><Notice>Membership and role changes require a root-signed policy produced through the CLI. The access server never stores the root key.</Notice>
    <div className="access-section-title"><h3>Resource grants</h3>{state.canAdmin && state.viewer.role === "admin" && canSign && principal.id !== state.viewer.principal.id && !revoked && <button onClick={() => setEditing("new")}><Plus size={14} />Grant access</button>}</div>
    {grants.map((grant) => { const stopped = grant.revoked || state.revokedGrantIds.includes(`${grant.issuerId}:${grant.id}`) || state.signedRevocations.some((r) => r.artifact.issuerId === grant.issuerId && r.artifact.targetKind === "grant" && r.artifact.targetId === grant.id); return <div className="access-grant" key={`${grant.issuerId}:${grant.id}`}><strong>{grant.scope.all ? "All enrolled resources" : `${grant.scope.projectIds.length} ${grant.scope.projectIds.length === 1 ? "project" : "projects"} · ${grant.scope.agentIds.length} ${grant.scope.agentIds.length === 1 ? "agent" : "agents"}`}</strong><small>{grant.actions.join(" · ")}</small><small>{stopped ? "Revoked" : `Expires ${expiry(grant.expiresAt)}`} · issued by {labelFor(state, grant.issuerId)}</small>{canSign && !stopped && <div className="access-form-actions">{grant.issuerId === state.viewer.principal.id && <button onClick={() => setEditing(grant)}>Edit scope</button>}{grant.issuerId === state.viewer.principal.id && <button className="access-danger" onClick={() => void revoke({ kind: "grant", id: grant.id, issuerId: grant.issuerId }, "this grant")}>Revoke</button>}</div>}</div>; })}
    {!grants.length && <p className="access-muted">{role === "owner" || role === "admin" ? "This role has all enrolled-resource authority, bounded by each device delegation." : "No explicit resource grants."}</p>}
    {editing && <GrantForm key={editing === "new" ? "new" : editing.id} state={state} principal={principal} grant={editing === "new" ? undefined : editing} busy={busy} onSave={manage} onClose={() => setEditing(null)} />}
    {state.canAdmin && devices.length > 0 && <><h3>Effective device access</h3><p className="access-muted">Preview applies current grants, device scope and revocations at the broker.</p>{devices.map((d) => <button key={d.id} className="access-preview-button" onClick={async () => { setPreviewError(""); try { const data = await rpc<{ agents: Agent[] }>({ operation: "access.preview", artifact: d }); setPreview(data.agents); } catch { setPreview(null); setPreviewError("This device is expired or revoked. It has no current access."); } }}>Preview {d.id}<ArrowRight size={14} /></button>)}</>}
    {previewError && <Notice>{previewError}</Notice>}{preview && <div className="access-preview" aria-live="polite">{preview.length ? preview.map((a) => <p key={a.id}><strong>{a.displayName}</strong><small>{a.actions.join(" · ")}</small></p>) : <p>No resources visible to this device.</p>}<Notice>{state.executionBoundary}</Notice></div>}
  </>;
}
function GrantForm({ state, principal, grant, busy, onSave, onClose }: { state: NetworkState; principal: Principal; grant?: Grant; busy: boolean; onSave: (payload: unknown) => Promise<any>; onClose: () => void }) {
  const [scope, setScope] = useState(grant?.scope ?? emptyScope()), [actions, setActions] = useState(grant?.actions ?? ["discover", "message"]), [until, setUntil] = useState(localTime(grant?.expiresAt ?? Math.min(state.network.expiresAt, Date.now() + 86400000))), [error, setError] = useState("");
  return <form className="access-editor" onSubmit={async (e) => { e.preventDefault(); try { await onSave({ action: "grant.save", subjectId: principal.id, scope, actions, expiresAt: new Date(until).getTime(), ...(grant ? { id: grant.id } : {}) }); onClose(); } catch (cause) { setError((cause as Error).message); } }}><h3>{grant ? "Edit access" : `Share with ${principal.label}`}</h3><ScopeFields state={state} scope={scope} onChange={setScope} /><ActionFields actions={actions} onChange={setActions} boundary={state.executionBoundary} /><label>Expires<input type="datetime-local" required value={until} max={localTime(state.network.expiresAt)} onChange={(e) => setUntil(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<div className="access-form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="access-primary" disabled={busy}>Save access</button></div></form>;
}
function DeviceForm({ state, busy, onSave, onClose }: { state: NetworkState; busy: boolean; onSave: (payload: unknown) => Promise<any>; onClose: () => void }) {
  const [key, setKey] = useState(""), [id, setId] = useState(""), [scope, setScope] = useState(emptyScope()), [actions, setActions] = useState(["discover", "message"].filter((a) => state.viewerDevice.actions.includes(a))), [error, setError] = useState(""), [certificate, setCertificate] = useState<string | null>(null);
  return <form className="access-editor" onSubmit={async (e) => { e.preventDefault(); try { const publicValue = key.trim().startsWith("{") ? JSON.parse(key) : null; if (publicValue && (publicValue.privateKey || publicValue.identity)) throw new Error("Paste a public key only; keep private credentials on the device."); const devicePublicKey = publicValue ? publicValue.publicKey : key.trim(); const value = await onSave({ action: "device.approve", id, devicePublicKey, scope, actions, expiresAt: Math.min(state.network.expiresAt, state.viewerDevice.expiresAt, Date.now() + 86400000) }); setCertificate(JSON.stringify(value.delegation ?? value, null, 2)); } catch (cause) { setError((cause as Error).message); } }}><h2>Approve a device for {state.viewer.principal.label}</h2><p>Generate its private key on that device using the CLI. Paste only its public key or public.json here.</p><label>Delegation name<input required pattern="[A-Za-z0-9][A-Za-z0-9._:@-]{0,199}" value={id} onChange={(e) => setId(e.target.value)} placeholder="laptop-september" /></label><label>Public device key<textarea required value={key} onChange={(e) => setKey(e.target.value)} rows={3} /></label><ScopeFields state={state} scope={scope} onChange={setScope} /><ActionFields actions={actions} onChange={setActions} boundary={state.executionBoundary} permitted={state.viewerDevice.actions} allowAdmin={state.canAdmin && state.viewer.role === "admin"} /><Notice>This approval expires by {expiry(state.viewerDevice.expiresAt)} and cannot exceed this configured device’s scope or actions. The device must prove possession on its first signed request.</Notice>{error && <p role="alert">{error}</p>}{certificate && <label>Signed public delegation · save on the device<textarea readOnly rows={7} value={certificate} /><button type="button" onClick={() => { const url = URL.createObjectURL(new Blob([certificate], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "delegation.json"; link.click(); URL.revokeObjectURL(url); }}>Download public delegation</button></label>}<div className="access-form-actions"><button type="button" onClick={onClose}>Close</button><button className="access-primary" disabled={busy || certificate !== null}>Approve device</button></div></form>;
}
function RequestForm({ agent, boundary, onSend }: { agent: Agent; boundary: string; onSend: (payload: unknown) => Promise<void> }) {
  const [operation, setOperation] = useState(agent.actions.includes("message") ? "message" : "request"), [body, setBody] = useState(""), [busy, setBusy] = useState(false), [note, setNote] = useState("");
  useEffect(() => { setOperation(agent.actions.includes("message") ? "message" : "request"); setBody(""); setNote(""); }, [agent.id]);
  const canWrite = agent.actions.includes("message") || agent.actions.includes("request");
  return <><h2>{agent.displayName}</h2><p className="access-muted">{agent.projectName ?? "Selected agent"}</p>{canWrite ? <form onSubmit={async (e) => { e.preventDefault(); setBusy(true); try { await onSend({ operation, target: agent.id, requestId: crypto.randomUUID(), body }); setBody(""); setNote(operation === "message" ? "Message saved. No notification or harness wake was requested." : "Request accepted. Its progress will appear under Your work."); } catch (cause) { setNote((cause as Error).message); } finally { setBusy(false); } }}><label>Action<select value={operation} onChange={(e) => setOperation(e.target.value)}>{agent.actions.includes("message") && <option value="message">Leave a message</option>}{agent.actions.includes("request") && <option value="request">Request work</option>}</select></label><label>{operation === "message" ? "Message" : "Work request"}<textarea required maxLength={16000} rows={7} value={body} onChange={(e) => setBody(e.target.value)} /></label>{operation === "request" ? <Notice>{boundary}</Notice> : <Notice>Leaving a message is passive. It does not wake the agent or grant access to replies.</Notice>}<button className="access-primary" disabled={busy}>{busy ? "Sending…" : operation === "message" ? "Leave message" : "Request work"}</button><p role="status">{note}</p></form> : <p>You can discover this agent but have no message or work permission.</p>}</>;
}

function SigningDialog({ state, preview, onCancel, onConfirm }: { state: NetworkState | null; preview: any; onCancel: () => void; onConfirm: (password: string) => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null), [password, setPassword] = useState(""), [error, setError] = useState(""), [sending, setSending] = useState(false);
  useEffect(() => { dialog.current?.showModal(); return () => dialog.current?.close(); }, []);
  return <dialog ref={dialog} className="access-signing-preview" aria-labelledby="access-signing-title" onCancel={(event) => { event.preventDefault(); if (!sending) onCancel(); }}><form onSubmit={async (e) => { e.preventDefault(); setSending(true); setError(""); try { await onConfirm(password); setPassword(""); } catch (cause) { setPassword(""); setError((cause as Error).message); } finally { setSending(false); } }}><h2 id="access-signing-title">Review exact access change</h2><p>This preview expires after one minute. Confirm your password to authorize this change.</p><dl className="access-change-summary"><dt>Change</dt><dd>{preview.artifact.kind}</dd>{preview.artifact.subjectId && <><dt>Shared with</dt><dd>{state ? labelFor(state, preview.artifact.subjectId) : preview.artifact.subjectId}</dd></>}{preview.artifact.targetId && <><dt>Revocation target</dt><dd>{preview.artifact.targetKind}: {preview.artifact.targetId}</dd></>}{preview.artifact.scope && <><dt>Resources</dt><dd>{preview.artifact.scope.all ? "All enrolled resources, including future enrollments" : [...preview.artifact.scope.projectIds.map((id: string) => `Project: ${state?.resources.projects.find((p) => p.id === id)?.name ?? id}`), ...preview.artifact.scope.agentIds.map((id: string) => `Agent: ${state?.resources.agents.find((a) => a.id === id)?.displayName ?? id}`)].join("; ") || "No resources"}</dd></>}{preview.artifact.actions && <><dt>Actions</dt><dd>{preview.artifact.actions.join(" · ")}</dd></>}{preview.artifact.expiresAt && <><dt>Expires</dt><dd>{expiry(preview.artifact.expiresAt)}</dd></>}<dt>Receiving broker</dt><dd>{preview.audience}</dd></dl><details><summary>Inspect exact public artifact</summary><pre>{JSON.stringify(preview.artifact, null, 2)}</pre></details>{(preview.warnings ?? []).map((warning: string) => <Notice key={warning}>{warning}</Notice>)}{preview.artifact?.actions?.includes("request") && <Notice>Request permission may provide owner-level local execution through a coding agent. Isolate that agent from owner credentials when containment is required.</Notice>}{preview.artifact?.kind === "revocation" && <Notice>Revocation is permanent at each broker that accepts it. It blocks new operations; already-running work is not cancelled.</Notice>}<label>Confirm your password<input autoFocus autoComplete="current-password" type="password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="access-error" role="alert">{error}</p>}<div className="access-form-actions"><button type="button" disabled={sending} onClick={onCancel}>Cancel</button><button className="access-primary" disabled={sending}>{sending ? "Applying…" : "Confirm change"}</button></div></form></dialog>;
}
