import type { ObserveCacheEntry } from "../../lib/observe.ts";
// Import via the browser-safe `/client` entry — the barrel index re-exports
// node-only history helpers (node:path) that crash the browser bundle.
import { inferModelContextWindowTokens } from "@openscout/agent-sessions/client";
import type { TerminalSessionRecord } from "@openscout/protocol";
import { isRelayCapableTerminalBackend } from "../../lib/terminal-sessions.ts";
import {
  filesFromObserveEvents,
  filterObserveDataForHorizonWithFill,
  isPlausibleFilePath,
  LANE_TRACE_FILL_MIN,
  laneSnippetText,
  observeEventWallMs,
} from "../../lib/lane-observe.ts";
import {
  isStrReplaceTool,
  strReplaceDetailText,
  strReplaceDiffFromEdit,
  strReplaceFromGrokSummary,
  strReplaceFromObject,
  type StrReplaceEdit,
} from "../../lib/lane-edit-display.ts";
import {
  filterTailEventsForDisplay,
  isTailNoiseEvent,
  observeKindFromTailEvent,
  observeTextFromTailEvent,
  observeToolFieldsFromTailEvent,
  tailObserveEventDetail,
} from "../../lib/tail-display.ts";
import type {
  Agent,
  ObserveData,
  ObserveEvent,
  ObserveFile,
  ObserveSessionMeta,
  ObserveUsageMeta,
  TailDiscoveredProcess,
  TailDiscoveredTranscript,
  TailEvent,
  TailHarness,
} from "../../lib/types.ts";
import { laneCompactionStateFromTail } from "./session-compaction.ts";

export type AgentLaneHorizonKey = "5m" | "30m" | "4h" | "24h";

export const DEFAULT_AGENT_LANE_HORIZON: AgentLaneHorizonKey = "5m";

export const AGENT_LANE_HORIZON_OPTIONS: ReadonlyArray<{
  key: AgentLaneHorizonKey;
  label: string;
  windowMs: number;
}> = [
  { key: "5m", label: "5m", windowMs: 5 * 60_000 },
  { key: "30m", label: "30m", windowMs: 30 * 60_000 },
  { key: "4h", label: "4h", windowMs: 4 * 60 * 60_000 },
  { key: "24h", label: "24h", windowMs: 24 * 60 * 60_000 },
];

export function agentLaneHorizonWindowMs(horizon: AgentLaneHorizonKey): number {
  return AGENT_LANE_HORIZON_OPTIONS.find((option) => option.key === horizon)?.windowMs
    ?? AGENT_LANE_HORIZON_OPTIONS[0].windowMs;
}

export function agentLaneHorizonLabel(horizon: AgentLaneHorizonKey): string {
  return AGENT_LANE_HORIZON_OPTIONS.find((option) => option.key === horizon)?.label
    ?? horizon;
}

/** Scale tail replay depth with the selected lane horizon. The floor is
 * 2,000 even for the 5m window: replay feeds the trace FILL (last-N history
 * for present-but-quiet lanes), and one chatty lane can crowd a quiet lane
 * out of a 500-event shared buffer. */
export function agentLaneTailRecentLimit(horizon: AgentLaneHorizonKey): number {
  switch (horizon) {
    case "5m":
    case "30m":
      return 2_000;
    case "4h":
      return 5_000;
    case "24h":
      return 10_000;
    default:
      return 2_000;
  }
}

const MAX_LANE_TRACE_EVENTS = 400;

export type AgentLaneSource = "scout" | "native";

export type AgentLane = {
  id: string;
  agent: Agent;
  source: AgentLaneSource;
  observe: ObserveData | null;
  facts?: LaneFacts;
  lastActiveAt: number;
  current: boolean;
};

export type AgentLaneRosterIssueKind =
  | "session_binding_conflict"
  | "duplicate_transcript_session"
  | "transcript_path_collision"
  | "harness_session_unbound"
  | "harness_session_polluted"
  | "shadowed_scout_card";

export type AgentLaneRosterIssue = {
  id: string;
  kind: AgentLaneRosterIssueKind;
  message: string;
  sessionRef?: string;
  agentIds?: string[];
  agentNames?: string[];
  transcriptPaths?: string[];
  selectedAgentId?: string;
};

export type AgentLaneRosterBuild = {
  lanes: AgentLane[];
  issues: AgentLaneRosterIssue[];
};

export type LaneCompactionFacts = {
  eligible: boolean;
  reason: "high_context" | "over_limit" | "post_compaction_point" | null;
  lastCompactedAt?: number;
  lastCompactedSummary?: string;
};

export type LaneFacts = {
  model?: string;
  effort?: string;
  branch?: string;
  cwd?: string;
  originator?: string;
  attribution?: TailHarness;
  turn?: { phase: "idle" | "started" | "complete"; index?: number };
  usage?: ObserveUsageMeta;
  compaction?: LaneCompactionFacts;
  currentTask?: string;
  /** The observed parent session for a harness-owned child worker. */
  parentSessionId?: string;
  /** A Scout card name for the parent when that session is known to Scout. */
  parentAgentName?: string;
  touchedFiles: ObserveFile[];
};

function titleCaseHarness(value: string): string {
  return value ? `${value[0]?.toUpperCase()}${value.slice(1).toLowerCase()}` : "";
}

/** True for tail-synthesized names like "Grok 0f8eddbb" or "Codex 019edd5a". */
export function isAutoGeneratedLaneAgentName(agent: Agent): boolean {
  const name = agent.name.trim();
  if (!name) return true;
  if (agent.agentClass === "organic") return true;

  const harness = agent.harness?.trim();
  if (!harness) return false;

  const head = titleCaseHarness(harness);
  return new RegExp(`^${head}\\s+[0-9a-f]{6}`, "i").test(name);
}

/** Legacy tmux/runtime refs wrongly stored in the harness session slot. */
export function isTransportRefInHarnessSlot(
  harnessSessionId: string | null | undefined,
  terminalSurface: Agent["terminalSurface"] = null,
): boolean {
  const trimmed = harnessSessionId?.trim();
  if (!trimmed) return false;
  if (/^relay[-:]/i.test(trimmed)) return true;
  const surfaceName = terminalSurface?.sessionName?.trim();
  return Boolean(surfaceName && trimmed === surfaceName);
}

/** Provider conversation id present and not polluted by a transport ref. */
export function hasProviderHarnessSession(agent: Agent): boolean {
  const sessionId = agent.harnessSessionId?.trim();
  if (!sessionId) return false;
  return !isTransportRefInHarnessSlot(sessionId, agent.terminalSurface);
}

/** Warmed-up codex app-server relay waiting for work — not an active lane. */
export function isIdleCodexRelay(agent: Agent): boolean {
  return agent.transport === "codex_app_server" && agent.state === "available";
}

function recentBrokerActivity(
  agent: Agent,
  now: number,
  windowMs: number,
) {
  return (agent.brokerActivity ?? []).filter((event) => (
    event.at > 0 && now - event.at <= windowMs
  ));
}

/** Poll observe only for agents that may produce lane-worthy trace activity. */
export function shouldPollAgentForLaneObserve(
  agent: Agent,
  now: number = Date.now(),
  horizon: AgentLaneHorizonKey = DEFAULT_AGENT_LANE_HORIZON,
): boolean {
  if (isIdleCodexRelay(agent)) return false;
  if (agent.harnessSessionId?.trim()) return true;
  if (agent.state && /^(working|active|running|in_turn|in_flight|queued|waking|dispatching)$/i.test(agent.state.trim())) {
    return true;
  }
  const windowMs = agentLaneHorizonWindowMs(horizon);
  return agent.updatedAt ? now - agent.updatedAt <= windowMs : false;
}

/** @deprecated Use isTransportRefInHarnessSlot */
export function isRelayHarnessSession(value: string | null | undefined): boolean {
  return isTransportRefInHarnessSlot(value);
}

/** Scout-managed cards with deliberate names — not ephemeral transport-only rows. */
export function hasDesignedAgentCard(agent: Agent, source: AgentLaneSource): boolean {
  return source === "scout"
    && agent.agentClass !== "organic"
    && !isAutoGeneratedLaneAgentName(agent)
    && (hasProviderHarnessSession(agent) || (agent.brokerActivity?.length ?? 0) > 0);
}

export function lanePrimaryLabel(agent: Agent, source: AgentLaneSource): string {
  if (agent.role === "subagent") {
    return agent.name.trim() || "Subagent";
  }
  if (hasDesignedAgentCard(agent, source)) {
    return agent.name.trim() || "Agent";
  }
  return agent.project?.trim() || agent.harness?.trim() || "local";
}

export function laneStatusLabel(agent: Agent, source: AgentLaneSource): string {
  return agent.harness?.trim() || lanePrimaryLabel(agent, source);
}

export function laneContextLabel(agent: Agent, source: AgentLaneSource): string {
  if (hasDesignedAgentCard(agent, source)) {
    return [agent.project, agent.branch].filter(Boolean).join(" · ") || agent.harness || "local";
  }
  const harness = agent.harness?.trim();
  const session = agent.harnessSessionId?.trim();
  if (harness && session) {
    return `${harness} · ${session.replace(/\.jsonl$/u, "").slice(0, 8)}`;
  }
  return harness || session?.slice(0, 8) || "native";
}

function stableHash(value: string): string {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

export function nativeSessionId(transcript: TailDiscoveredTranscript): string {
  const sessionId = transcript.sessionId?.trim();
  if (sessionId) {
    return `native:${transcript.source}:${sessionId}`;
  }
  return `native:${transcript.source}:path:${stableHash(transcript.transcriptPath)}`;
}

function metadataRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function tailPayload(event: TailEvent): Record<string, unknown> | null {
  const raw = metadataRecord(event.raw);
  return metadataRecord(raw?.payload);
}

function rawRecordType(event: TailEvent): string | null {
  const raw = metadataRecord(event.raw);
  const type = raw?.type;
  return typeof type === "string" ? type : null;
}

function payloadType(event: TailEvent): string | null {
  const payload = tailPayload(event);
  const type = payload?.type;
  return typeof type === "string" ? type : null;
}

function stringValue(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value !== "string") continue;
    const trimmed = value.trim();
    if (trimmed) return trimmed;
  }
  return undefined;
}

function numberValue(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function sumNumberValues(values: Array<number | undefined>): number | undefined {
  let sawValue = false;
  let total = 0;
  for (const value of values) {
    if (value === undefined) continue;
    sawValue = true;
    total += value;
  }
  return sawValue ? total : undefined;
}

function nestedRecord(
  record: Record<string, unknown> | null | undefined,
  key: string,
): Record<string, unknown> | null {
  return metadataRecord(record?.[key]);
}

function latestPayloadByEntryType(
  events: TailEvent[],
  entryType: string,
): Record<string, unknown> | null {
  let latest: { event: TailEvent; payload: Record<string, unknown> } | null = null;
  for (const event of events) {
    if (rawRecordType(event) !== entryType) continue;
    const payload = tailPayload(event);
    if (!payload) continue;
    if (!latest || event.ts >= latest.event.ts) latest = { event, payload };
  }
  return latest?.payload ?? null;
}

function latestTurnContext(events: TailEvent[]): Record<string, unknown> | null {
  return latestPayloadByEntryType(events, "turn_context");
}

function latestSessionMeta(events: TailEvent[]): Record<string, unknown> | null {
  return latestPayloadByEntryType(events, "session_meta");
}

function effortFromTurnContext(turnContext: Record<string, unknown> | null): string | undefined {
  const collaboration = nestedRecord(turnContext, "collaboration_mode");
  const settings = nestedRecord(collaboration, "settings");
  return stringValue(turnContext?.effort, settings?.reasoning_effort);
}

function branchFromPayload(payload: Record<string, unknown> | null): string | undefined {
  return stringValue(
    payload?.gitBranch,
    payload?.git_branch,
    payload?.currentBranch,
    payload?.current_branch,
    payload?.branch,
  );
}

type UsageScope = "session" | "turn";

function usageFromCodexTokenEvent(
  event: TailEvent,
  model?: string,
  scope: UsageScope = "session",
): ObserveUsageMeta | null {
  if (event.source !== "codex") return null;
  if (rawRecordType(event) !== "event_msg" || payloadType(event) !== "token_count") {
    const summaryTotal = event.summary.match(/^tokens? · ([0-9,]+)/i)?.[1]?.replace(/,/g, "");
    const totalTokens = summaryTotal ? Number.parseInt(summaryTotal, 10) : NaN;
    return Number.isFinite(totalTokens) ? { totalTokens } : null;
  }

  const payload = tailPayload(event);
  const info = nestedRecord(payload, "info");
  const total = nestedRecord(info, "total_token_usage");
  const last = nestedRecord(info, "last_token_usage");
  const rateLimits = nestedRecord(payload, "rate_limits");
  if (!total && !info && !rateLimits) return null;
  const counted = scope === "turn" ? (last ?? total) : (total ?? last);

  const usage: ObserveUsageMeta = {};
  const inputTokens = numberValue(counted?.input_tokens);
  // Codex cached_input_tokens is a subset of input_tokens, not additive.
  // Latest-turn context fill is last.input_tokens only.
  const lastInputTokens = numberValue(last?.input_tokens);
  const contextInputTokens = lastInputTokens;
  const outputTokens = numberValue(counted?.output_tokens);
  const reasoningOutputTokens = numberValue(counted?.reasoning_output_tokens);
  const cacheReadInputTokens = numberValue(counted?.cached_input_tokens)
    ?? numberValue(counted?.cache_read_input_tokens);
  const cacheCreationInputTokens = numberValue(counted?.cache_creation_input_tokens)
    ?? numberValue(counted?.cache_write_input_tokens);
  const totalTokens = numberValue(counted?.total_tokens)
    ?? (
      inputTokens !== undefined || outputTokens !== undefined
        ? (inputTokens ?? 0) + (outputTokens ?? 0)
        : undefined
    );
  const contextWindowTokens = numberValue(info?.model_context_window)
    ?? inferModelContextWindowTokens({ model, adapterType: "codex" });
  const serviceTier = stringValue(payload?.service_tier, rateLimits?.service_tier);
  const speed = stringValue(payload?.speed, rateLimits?.speed);
  const planType = stringValue(payload?.plan_type, rateLimits?.plan_type);

  if (inputTokens !== undefined) usage.inputTokens = inputTokens;
  if (contextInputTokens !== undefined) usage.contextInputTokens = contextInputTokens;
  if (outputTokens !== undefined) usage.outputTokens = outputTokens;
  if (reasoningOutputTokens !== undefined) usage.reasoningOutputTokens = reasoningOutputTokens;
  if (cacheReadInputTokens !== undefined) usage.cacheReadInputTokens = cacheReadInputTokens;
  if (cacheCreationInputTokens !== undefined) usage.cacheCreationInputTokens = cacheCreationInputTokens;
  if (totalTokens !== undefined) usage.totalTokens = totalTokens;
  if (contextWindowTokens !== undefined) usage.contextWindowTokens = contextWindowTokens;
  if (serviceTier) usage.serviceTier = serviceTier;
  if (speed) usage.speed = speed;
  if (planType) usage.planType = planType;
  return Object.keys(usage).length > 0 ? usage : null;
}

function usageFromClaudeAssistantEvent(event: TailEvent): ObserveUsageMeta | null {
  if (event.source !== "claude" || rawRecordType(event) !== "assistant") return null;
  const raw = metadataRecord(event.raw);
  const message = metadataRecord(raw?.message);
  const usageRecord = metadataRecord(message?.usage);
  if (!message || !usageRecord) return null;

  const inputTokens = numberValue(usageRecord.input_tokens);
  const outputTokens = numberValue(usageRecord.output_tokens);
  const cacheReadInputTokens = numberValue(usageRecord.cache_read_input_tokens);
  const cacheCreationInputTokens = numberValue(usageRecord.cache_creation_input_tokens);
  const contextInputTokens = (inputTokens ?? 0) + (cacheReadInputTokens ?? 0) + (cacheCreationInputTokens ?? 0);
  const contextWindowTokens = numberValue(usageRecord.context_window_tokens)
    ?? numberValue(usageRecord.contextWindowTokens)
    ?? numberValue(usageRecord.model_context_window)
    ?? numberValue(message.context_window_tokens)
    ?? numberValue(message.contextWindowTokens)
    ?? numberValue(message.model_context_window)
    ?? inferModelContextWindowTokens({
      model: stringValue(message.model),
      adapterType: "claude-code",
    });
  const totalTokens = (inputTokens ?? 0)
    + (outputTokens ?? 0)
    + (cacheReadInputTokens ?? 0)
    + (cacheCreationInputTokens ?? 0);
  const serverToolUse = metadataRecord(usageRecord.server_tool_use);

  const usage: ObserveUsageMeta = {};
  if (inputTokens !== undefined) usage.inputTokens = inputTokens;
  if (contextInputTokens > 0) usage.contextInputTokens = contextInputTokens;
  if (outputTokens !== undefined) usage.outputTokens = outputTokens;
  if (cacheReadInputTokens !== undefined) usage.cacheReadInputTokens = cacheReadInputTokens;
  if (cacheCreationInputTokens !== undefined) usage.cacheCreationInputTokens = cacheCreationInputTokens;
  if (totalTokens > 0) usage.totalTokens = totalTokens;
  if (contextWindowTokens > 0) usage.contextWindowTokens = contextWindowTokens;
  const webSearchRequests = numberValue(serverToolUse?.web_search_requests);
  const webFetchRequests = numberValue(serverToolUse?.web_fetch_requests);
  if (webSearchRequests !== undefined) usage.webSearchRequests = webSearchRequests;
  if (webFetchRequests !== undefined) usage.webFetchRequests = webFetchRequests;
  const serviceTier = stringValue(message.service_tier, usageRecord.service_tier);
  const speed = stringValue(message.speed, usageRecord.speed);
  if (serviceTier) usage.serviceTier = serviceTier;
  if (speed) usage.speed = speed;
  return Object.keys(usage).length > 0 ? usage : null;
}

function usageFromTailEvents(
  events: TailEvent[],
  options?: { scope?: UsageScope },
): ObserveUsageMeta | undefined {
  let latest: { ts: number; usage: ObserveUsageMeta } | null = null;
  const turnContext = latestTurnContext(events);
  const model = stringValue(
    turnContext?.model,
    nestedRecord(nestedRecord(turnContext, "collaboration_mode"), "settings")?.model,
  );
  const scope = options?.scope ?? "session";
  for (const event of events) {
    if (event.source !== "codex" && event.source !== "claude") continue;
    if (
      event.source === "codex"
      && payloadType(event) !== "token_count"
      && !/^tokens?(?: ·|$)/i.test(event.summary.trim())
    ) {
      continue;
    }
    const usage = event.source === "codex"
      ? usageFromCodexTokenEvent(event, model, scope)
      : usageFromClaudeAssistantEvent(event);
    if (!usage) continue;
    if (!latest || event.ts >= latest.ts) latest = { ts: event.ts, usage };
  }
  return latest?.usage;
}

function codexSessionMetaFromTailEvents(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
): ObserveSessionMeta {
  const sessionMeta = latestSessionMeta(events);
  const turnContext = latestTurnContext(events);
  const collaboration = nestedRecord(turnContext, "collaboration_mode");
  const settings = nestedRecord(collaboration, "settings");
  const sandboxPolicy = metadataRecord(turnContext?.sandbox_policy);
  const permissionProfile = metadataRecord(turnContext?.permission_profile);

  const session: ObserveSessionMeta = {
    adapterType: transcript.source,
    cwd: stringValue(turnContext?.cwd, sessionMeta?.cwd, transcript.cwd) ?? undefined,
    externalSessionId: stringValue(sessionMeta?.id, transcript.sessionId) ?? undefined,
    threadId: stringValue(turnContext?.turn_id) ?? undefined,
    threadPath: transcript.transcriptPath,
    model: stringValue(turnContext?.model, settings?.model) ?? undefined,
    effort: effortFromTurnContext(turnContext),
    gitBranch: branchFromPayload(turnContext) ?? branchFromPayload(sessionMeta),
    cliVersion: stringValue(sessionMeta?.cli_version),
    entrypoint: stringValue(sessionMeta?.thread_source, sessionMeta?.source),
    originator: stringValue(sessionMeta?.originator, sessionMeta?.source),
    source: stringValue(sessionMeta?.source),
    approvalPolicy: stringValue(turnContext?.approval_policy),
    sandbox: stringValue(sandboxPolicy?.type, turnContext?.sandbox),
    permissionMode: stringValue(permissionProfile?.type, turnContext?.permission_mode),
    userType: stringValue(sessionMeta?.user_type, turnContext?.user_type),
    modelProvider: stringValue(sessionMeta?.model_provider, turnContext?.model_provider),
    timezone: stringValue(turnContext?.timezone),
  };

  for (const key of Object.keys(session) as Array<keyof ObserveSessionMeta>) {
    if (session[key] === undefined) delete session[key];
  }
  return session;
}

/**
 * Claude Code transcript records carry session metadata inline rather than in
 * dedicated `turn_context`/`session_meta` payloads: the git branch sits on the
 * top-level `gitBranch` field and the model on assistant-message records at
 * `message.model`. Pull the latest of each so Claude lanes get the same
 * model/branch/cwd facts Codex lanes already have.
 */
function claudeSessionMetaFromTailEvents(
  events: TailEvent[],
): { model?: string; gitBranch?: string; cwd?: string } {
  let model: { ts: number; value: string } | undefined;
  let gitBranch: { ts: number; value: string } | undefined;
  let cwd: { ts: number; value: string } | undefined;

  for (const event of events) {
    if (event.source !== "claude") continue;
    const raw = metadataRecord(event.raw);
    if (!raw) continue;

    const branch = stringValue(raw.gitBranch);
    if (branch && (!gitBranch || event.ts >= gitBranch.ts)) {
      gitBranch = { ts: event.ts, value: branch };
    }

    const dir = stringValue(raw.cwd);
    if (dir && (!cwd || event.ts >= cwd.ts)) {
      cwd = { ts: event.ts, value: dir };
    }

    const message = nestedRecord(raw, "message");
    const messageModel = stringValue(message?.model);
    if (messageModel && (!model || event.ts >= model.ts)) {
      model = { ts: event.ts, value: messageModel };
    }
  }

  return {
    model: model?.value,
    gitBranch: gitBranch?.value,
    cwd: cwd?.value,
  };
}

function mergeObserveFiles(
  left: ObserveFile[] | undefined,
  right: ObserveFile[] | undefined,
): ObserveFile[] {
  const byPath = new Map<string, ObserveFile>();
  for (const file of [...left ?? [], ...right ?? []]) {
    const path = file.path?.trim();
    // Reject mis-recorded bash tokens (e.g. `necho`, `nCHROME=`) that leak into
    // the raw `observe.files` READ inventory; the client inferer is already clean.
    if (!path || !isPlausibleFilePath(path)) continue;
    const existing = byPath.get(path);
    if (!existing) {
      byPath.set(path, { ...file, path });
      continue;
    }
    existing.touches += file.touches;
    existing.lastT = Math.max(existing.lastT, file.lastT);
    if (existing.state === "read" && file.state !== "read") existing.state = file.state;
    if (existing.state === "modified" && file.state === "created") existing.state = "created";
  }
  return [...byPath.values()].sort((leftFile, rightFile) => {
    const leftChanged = leftFile.state === "read" ? 0 : 1;
    const rightChanged = rightFile.state === "read" ? 0 : 1;
    if (leftChanged !== rightChanged) return rightChanged - leftChanged;
    return rightFile.lastT - leftFile.lastT;
  });
}

function turnFactsFromTailEvents(events: TailEvent[]): LaneFacts["turn"] {
  let startedAt = -1;
  let completedAt = -1;
  let startedCount = 0;
  for (const event of events) {
    const summary = event.summary.trim().toLowerCase();
    const type = payloadType(event);
    if (summary === "task started" || type === "task_started") {
      startedAt = Math.max(startedAt, event.ts);
      startedCount += 1;
    }
    if (summary === "task complete" || type === "task_complete" || type === "turn_aborted") {
      completedAt = Math.max(completedAt, event.ts);
    }
  }
  if (startedCount === 0 && completedAt < 0) return { phase: "idle" };
  return {
    phase: startedAt > completedAt ? "started" : "complete",
    index: startedCount || undefined,
  };
}

function currentTaskFromTailEvents(
  events: TailEvent[],
  observe: ObserveData | null | undefined,
): string | undefined {
  const latestObserveAsk = [...observe?.events ?? []]
    .reverse()
    .find((event) => event.kind === "ask" && event.text.trim());
  if (latestObserveAsk) return laneSnippetText(latestObserveAsk.text, 160, 2);

  for (const event of [...events].sort((left, right) => right.ts - left.ts)) {
    if (event.kind === "user" && event.summary.trim()) {
      return laneSnippetText(event.summary, 160, 2);
    }
    const payload = tailPayload(event);
    if (payloadType(event) === "user_message") {
      const message = stringValue(payload?.message);
      if (message) return laneSnippetText(message, 160, 2);
    }
  }
  return undefined;
}

function attributionFromEvents(events: TailEvent[]): TailHarness | undefined {
  let best: TailHarness | undefined;
  for (const event of events) {
    if (!best || (ATTRIBUTION_RANK[event.harness] ?? 0) > (ATTRIBUTION_RANK[best] ?? 0)) {
      best = event.harness;
    }
  }
  return best;
}

function observeSessionFromTail(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
  sessionStart: number,
): ObserveSessionMeta {
  const base = codexSessionMetaFromTailEvents(transcript, events);
  const claude = claudeSessionMetaFromTailEvents(events);
  return {
    ...base,
    // Codex extraction wins where present; Claude lanes carry model/branch
    // inline on the raw records, so backfill any field still empty.
    model: base.model ?? claude.model,
    gitBranch: base.gitBranch ?? claude.gitBranch,
    cwd: base.cwd ?? claude.cwd ?? transcript.cwd ?? undefined,
    externalSessionId: base.externalSessionId ?? transcript.sessionId ?? undefined,
    sessionStart,
  };
}

function parseMaybeJsonRecord(value: string | undefined): Record<string, unknown> | null {
  if (!value?.trim()) return null;
  try {
    return metadataRecord(JSON.parse(value));
  } catch {
    return null;
  }
}

function codexToolPayloadName(event: TailEvent): string | undefined {
  const payload = tailPayload(event);
  return stringValue(payload?.name, payload?.type);
}

function codexToolRawArgument(event: TailEvent): string | undefined {
  const payload = tailPayload(event);
  const args = payload?.arguments;
  if (typeof args === "string") return args;
  const input = payload?.input;
  if (typeof input === "string") return input;
  const command = payload?.command;
  if (Array.isArray(command)) {
    return command.filter((part) => typeof part === "string").join(" ");
  }
  if (typeof command === "string") return command;
  return undefined;
}

function codexPatchTextFromTailEvent(event: TailEvent): string | undefined {
  if (event.source !== "codex") return undefined;
  const name = codexToolPayloadName(event)?.toLowerCase();
  if (name !== "apply_patch" && name !== "patch_apply") return undefined;

  const rawArg = codexToolRawArgument(event);
  const parsed = parseMaybeJsonRecord(rawArg);
  return stringValue(parsed?.patch, parsed?.input, rawArg);
}

function diffPreviewFromPatch(patch: string | undefined): ObserveEvent["diff"] | undefined {
  if (!patch?.trim()) return undefined;
  let add = 0;
  let del = 0;
  const previewLines: string[] = [];
  for (const line of patch.split(/\r?\n/)) {
    if (line.startsWith("+") && !line.startsWith("+++")) add += 1;
    if (line.startsWith("-") && !line.startsWith("---")) del += 1;
    if (previewLines.length < 24 && /^(?:\*\*\* |@@|\+\+\+|---|[+-])/.test(line)) {
      previewLines.push(line);
    }
  }
  if (add === 0 && del === 0 && previewLines.length === 0) return undefined;
  return { add, del, preview: previewLines.join("\n") };
}

function grokToolInputFromTail(event: TailEvent): Record<string, unknown> | null {
  const raw = metadataRecord(event.raw);
  if (!raw) return null;
  return metadataRecord(raw.tool_input);
}

function strReplaceFromTailEvent(
  event: TailEvent,
  toolName: string | undefined,
): StrReplaceEdit | null {
  if (!isStrReplaceTool(toolName)) return null;

  if (event.source === "grok") {
    const fromSummary = strReplaceFromGrokSummary(event.summary);
    if (fromSummary) return fromSummary;
    const fromGrok = strReplaceFromObject(grokToolInputFromTail(event));
    if (fromGrok) return fromGrok;
  }

  const rawArg = codexToolRawArgument(event);
  const fromCodex = strReplaceFromObject(parseMaybeJsonRecord(rawArg));
  if (fromCodex) return fromCodex;

  return null;
}

function toolDetailFromTailEvent(
  event: TailEvent,
  toolName?: string,
): string | undefined {
  const patch = codexPatchTextFromTailEvent(event);
  if (patch) return patch;

  const replace = strReplaceFromTailEvent(event, toolName);
  if (replace && (replace.oldText || replace.newText)) {
    return strReplaceDetailText(replace);
  }

  return undefined;
}

function rawTailEventsForHorizon(
  events: TailEvent[],
  now: number,
  windowMs: number | undefined,
): TailEvent[] {
  const sorted = [...events].sort((left, right) => left.ts - right.ts);
  return typeof windowMs === "number" && windowMs > 0
    ? sorted.filter((event) => event.ts >= now - windowMs)
    : sorted;
}

function tailEventsForHorizon(
  events: TailEvent[],
  now: number,
  windowMs: number | undefined,
): TailEvent[] {
  const inWindow = rawTailEventsForHorizon(events, now, windowMs);
  const displayed = filterTailEventsForDisplay(inWindow, "work");
  return displayed.length > MAX_LANE_TRACE_EVENTS
    ? displayed.slice(-MAX_LANE_TRACE_EVENTS)
    : displayed;
}

/** Build lane observe data from the tail firehose (wall-clock timestamps). */
export function observeDataFromTail(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
  current: boolean,
  options?: { now?: number; windowMs?: number },
): ObserveData {
  const now = options?.now ?? Date.now();
  const rawTail = rawTailEventsForHorizon(events, now, options?.windowMs);
  const windowedTail = tailEventsForHorizon(rawTail, now, undefined);
  // Lane presence is horizon-gated by the caller; trace content keeps a
  // minimum tail of history so a freshly-admitted lane isn't nearly empty.
  const tail = windowedTail.length >= LANE_TRACE_FILL_MIN
    ? windowedTail
    : tailEventsForHorizon(events, now, undefined).slice(-LANE_TRACE_FILL_MIN);
  const sessionStart = tail[0]?.ts ?? transcript.mtimeMs;

  const observeEvents = tail.map((event): ObserveEvent => {
    const toolFields = observeToolFieldsFromTailEvent(event);
    const strReplace = strReplaceFromTailEvent(event, toolFields.tool);
    const detail = tailObserveEventDetail(event, transcript)
      ?? toolDetailFromTailEvent(event, toolFields.tool);
    const diff = strReplace && (strReplace.oldText || strReplace.newText)
      ? strReplaceDiffFromEdit(strReplace)
      : diffPreviewFromPatch(detail);
    return {
      id: event.id,
      t: Math.max(0, Math.round((event.ts - sessionStart) / 1000)),
      at: event.ts,
      kind: observeKindFromTailEvent(event),
      text: observeTextFromTailEvent(event, toolFields),
      tool: toolFields.tool,
      arg: toolFields.arg,
      result: toolFields.result,
      stream: toolFields.stream,
      diff,
      detail,
      live: current && event.id === tail[tail.length - 1]?.id,
    };
  });

  const files = filesFromObserveEvents(observeEvents);
  const usage = usageFromTailEvents(rawTail, {
    scope: typeof options?.windowMs === "number" && options.windowMs > 0 ? "turn" : "session",
  });

  return {
    events: observeEvents,
    files,
    live: current && observeEvents.length > 0,
    metadata: {
      session: observeSessionFromTail(transcript, events, sessionStart),
      usage,
    },
  };
}

/** @deprecated Use observeDataFromTail — kept for call-site compatibility. */
export function nativeObserveData(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
  current: boolean,
): ObserveData {
  return observeDataFromTail(transcript, events, current);
}

function titleCase(value: string): string {
  return value ? `${value[0]?.toUpperCase()}${value.slice(1)}` : "Native";
}

function shortId(value: string | null | undefined): string {
  if (!value) return "session";
  return value.replace(/\.jsonl$/u, "").slice(0, 8);
}

export function nativeSessionAgent(
  transcript: TailDiscoveredTranscript,
  lastActiveAt: number,
  current: boolean,
): Agent {
  const sessionId = transcript.sessionId?.trim() || null;
  const isSubagent = Boolean(transcript.subagentId);
  const name = isSubagent
    ? `${titleCase(transcript.source)} subagent ${shortId(transcript.subagentId)}`
    : `${titleCase(transcript.source)} ${shortId(sessionId)}`;
  return {
    id: nativeSessionId(transcript),
    definitionId: `native:${transcript.source}`,
    name,
    handle: null,
    agentClass: "organic",
    harness: transcript.source,
    state: current ? "working" : "idle",
    projectRoot: transcript.cwd,
    cwd: transcript.cwd,
    updatedAt: lastActiveAt,
    createdAt: null,
    transport: null,
    selector: null,
    defaultSelector: null,
    nodeQualifier: null,
    workspaceQualifier: null,
    wakePolicy: null,
    capabilities: [],
    project: transcript.project,
    branch: null,
    role: isSubagent ? "subagent" : null,
    model: null,
    harnessSessionId: sessionId,
    harnessLogPath: transcript.transcriptPath,
    conversationId: sessionId ?? nativeSessionId(transcript),
    homeNodeId: null,
    homeNodeName: null,
    ownerId: null,
    ownerName: null,
    ownerHandle: null,
    staleLocalRegistration: false,
    retiredFromFleet: false,
    replacedByAgentId: null,
    terminalSurface: null,
  };
}

const TERMINAL_BACKEND_HARNESSES = new Set(["tmux", "zellij", "herdr"]);

function projectFromPath(path: string | null | undefined): string | null {
  const trimmed = path?.trim();
  if (!trimmed) return null;
  const parts = trimmed.split("/").filter(Boolean);
  return parts[parts.length - 1] ?? trimmed;
}

function terminalSurfaceDescriptor(
  session: TerminalSessionRecord,
): Agent["terminalSurface"] {
  const surface = session.surfaces.find((candidate) => isRelayCapableTerminalBackend(candidate.backend));
  if (!surface || !isRelayCapableTerminalBackend(surface.backend)) return null;
  return {
    backend: surface.backend,
    sessionName: surface.sessionName,
    paneId: surface.paneId,
    socketDir: surface.socketDir ?? null,
  };
}

function isRegisteredHarnessTerminalSession(session: TerminalSessionRecord): boolean {
  const harness = session.harness?.trim();
  if (!harness || TERMINAL_BACKEND_HARNESSES.has(harness.toLowerCase())) return false;
  if (!session.sourceSessionId?.trim()) return false;
  if (session.origin === "discovered" || session.metadata?.registryState === "discovered") return false;
  return session.surfaces.length > 0;
}

function terminalSessionRefs(session: TerminalSessionRecord): string[] {
  const refs = new Set<string>();
  for (const candidate of [
    session.id,
    session.sourceSessionId,
    normalizeTailSessionRef(session.sourceSessionId),
  ]) {
    const trimmed = candidate?.trim();
    if (trimmed) refs.add(trimmed);
  }
  for (const surface of session.surfaces) {
    const surfaceName = surface.sessionName?.trim();
    if (surfaceName) refs.add(surfaceName);
  }
  return [...refs];
}

function nativeTerminalSessionId(session: TerminalSessionRecord): string {
  return `native:${session.harness}:terminal:${session.id}`;
}

function terminalSessionAgent(
  session: TerminalSessionRecord,
  lastActiveAt: number,
  current: boolean,
): Agent {
  const harness = session.harness.trim() || "native";
  const sessionId = session.sourceSessionId.trim() || session.id;
  const project = projectFromPath(session.cwd);
  return {
    id: nativeTerminalSessionId(session),
    definitionId: `native:${harness}`,
    name: `${titleCase(harness)} ${shortId(sessionId)}`,
    handle: null,
    agentClass: "organic",
    harness,
    state: current ? "working" : "idle",
    projectRoot: session.cwd || null,
    cwd: session.cwd || null,
    updatedAt: lastActiveAt,
    createdAt: session.createdAt ?? null,
    transport: terminalSurfaceDescriptor(session)?.backend ?? null,
    selector: null,
    defaultSelector: null,
    nodeQualifier: null,
    workspaceQualifier: null,
    wakePolicy: null,
    capabilities: [],
    project,
    branch: null,
    role: null,
    model: null,
    harnessSessionId: sessionId,
    harnessLogPath: null,
    conversationId: sessionId,
    homeNodeId: null,
    homeNodeName: null,
    ownerId: null,
    ownerName: null,
    ownerHandle: null,
    staleLocalRegistration: false,
    retiredFromFleet: false,
    replacedByAgentId: null,
    terminalSurface: terminalSurfaceDescriptor(session),
  };
}

function terminalSurfaceLabel(session: TerminalSessionRecord): string | null {
  const surface = session.surfaces[0];
  return surface ? `${surface.backend}:${surface.sessionName}` : null;
}

function sessionBackedObserveData(input: {
  id: string;
  harness: string | null | undefined;
  sessionId: string | null | undefined;
  cwd: string | null | undefined;
  model?: string | null;
  startedAt: number;
  current: boolean;
  detail?: string | null;
}): ObserveData {
  const harness = input.harness?.trim() || "Native";
  return {
    events: [{
      id: `${input.id}:session-ready`,
      t: 0,
      at: input.startedAt,
      kind: "system",
      text: `${titleCase(harness)} session ready`,
      detail: input.detail ?? input.cwd ?? input.sessionId ?? undefined,
      live: input.current,
    }],
    files: [],
    live: input.current,
    metadata: {
      session: {
        adapterType: input.harness ?? undefined,
        cwd: input.cwd ?? undefined,
        externalSessionId: input.sessionId ?? undefined,
        sessionStart: input.startedAt,
        model: input.model ?? undefined,
        source: "session-registry",
      },
    },
  };
}

function terminalSessionObserveData(
  session: TerminalSessionRecord,
  current: boolean,
  lastActiveAt: number,
): ObserveData {
  const surface = terminalSurfaceLabel(session);
  const detail = [surface ? `surface: ${surface}` : null, session.cwd].filter(Boolean).join(" · ");
  return sessionBackedObserveData({
    id: nativeTerminalSessionId(session),
    harness: session.harness,
    sessionId: session.sourceSessionId,
    cwd: session.cwd,
    startedAt: lastActiveAt,
    current,
    detail: detail || null,
  });
}

export function observeLastSubstantiveActivityAt(
  observe: ObserveData | null | undefined,
): number | null {
  if (!observe) return null;

  const sessionStart = observe.metadata?.session?.sessionStart;
  let latest: number | null = null;

  for (const event of observe.events) {
    if (!isSubstantiveObserveEvent(event)) continue;
    const wallMs = observeEventWallMs(event, sessionStart);
    if (wallMs === null) continue;
    latest = latest === null ? wallMs : Math.max(latest, wallMs);
  }

  if (typeof sessionStart === "number" && Number.isFinite(sessionStart)) {
    for (const file of observe.files) {
      if (!Number.isFinite(file.lastT) || file.lastT < 0) continue;
      const wallMs = sessionStart + file.lastT * 1000;
      latest = latest === null ? wallMs : Math.max(latest, wallMs);
    }
  }

  return latest;
}

function hasLiveSubstantiveWork(observe: ObserveData | null | undefined): boolean {
  if (!observe?.live) return false;
  return observe.events.some(
    (event) => event.live === true && isSubstantiveObserveEvent(event),
  );
}

function hasRecentSubstantiveObserve(
  observe: ObserveData | null | undefined,
  now: number,
  windowMs: number,
): boolean {
  const lastAt = observeLastSubstantiveActivityAt(observe);
  if (lastAt === null) return false;
  return now - lastAt <= windowMs;
}

function laneActivityAt(
  agent: Agent,
  observeEntry: ObserveCacheEntry | undefined,
  now: number,
): number {
  if (hasLiveSubstantiveWork(observeEntry?.data)) {
    return now;
  }

  const observeAt = observeLastSubstantiveActivityAt(observeEntry?.data);
  const agentAt = agent.updatedAt ?? 0;

  if (observeAt !== null) {
    return Math.max(observeAt, agentAt);
  }

  return 0;
}

export function isAgentLaneLive(
  observe: ObserveData | null | undefined,
): boolean {
  return hasLiveSubstantiveWork(observe);
}

const PLACEHOLDER_EVENT_MARKERS = [
  "transcript discovered",
  "waiting for events",
  "no session trace",
  "waiting for a live session",
];

function isWarmupBootObserveEvent(event: ObserveEvent): boolean {
  if (event.kind !== "boot" && event.kind !== "system") return false;
  const text = event.text.trim().toLowerCase();
  const detail = (event.detail ?? "").trim().toLowerCase();
  if (!text.includes("session started")) return false;
  return detail.includes("turns: 0") && detail.includes("status: idle");
}

function isSubstantiveObserveEvent(event: ObserveEvent): boolean {
  if (event.kind === "tool" || event.kind === "think" || event.kind === "ask" || event.kind === "message") {
    return true;
  }
  if (event.kind === "note") return true;
  if (event.kind === "system" || event.kind === "boot") {
    if (isWarmupBootObserveEvent(event)) return false;
    const text = event.text.trim().toLowerCase();
    return !PLACEHOLDER_EVENT_MARKERS.some((marker) => text.includes(marker));
  }
  return false;
}

const ATTRIBUTION_RANK: Record<TailHarness, number> = {
  "scout-managed": 3,
  "hudson-managed": 2,
  unattributed: 1,
};

/** File-discovered transcripts default to unattributed; resolve from live processes. */
export function resolveTranscriptAttribution(
  transcript: TailDiscoveredTranscript,
  processes: TailDiscoveredProcess[],
): TailHarness {
  const cwd = transcript.cwd?.trim();
  if (!cwd) return transcript.harness;

  const matches = processes.filter((proc) => proc.source === transcript.source && proc.cwd === cwd);
  if (matches.length === 0) return transcript.harness;

  return matches.reduce((best, candidate) => {
    const bestRank = ATTRIBUTION_RANK[best.harness] ?? 0;
    const candRank = ATTRIBUTION_RANK[candidate.harness] ?? 0;
    if (candRank > bestRank) return candidate;
    if (candRank === bestRank && candidate.pid < best.pid) return candidate;
    return best;
  }).harness;
}

export function buildLaneFacts(
  transcript: TailDiscoveredTranscript | null | undefined,
  events: TailEvent[],
  agent: Agent,
  processes: TailDiscoveredProcess[],
  observe?: ObserveData | null,
  parentAgent?: Agent,
): LaneFacts {
  const session = observe?.metadata?.session;
  const turnContext = latestTurnContext(events);
  const sessionMeta = latestSessionMeta(events);
  const attribution = transcript
    ? resolveTranscriptAttribution(transcript, processes)
    : attributionFromEvents(events);
  const inferredFiles = observe ? filesFromObserveEvents(observe.events) : [];
  const touchedFiles = mergeObserveFiles(observe?.files, inferredFiles);
  // Vitals/cockpit context should reflect the latest turn-scoped usage from the
  // full transcript, not horizon-filtered observe metadata (which can drop stale
  // token_count events outside the selected window).
  const usage = usageFromTailEvents(events, { scope: "turn" })
    ?? observe?.metadata?.usage;

  const facts: LaneFacts = {
    touchedFiles,
    model: stringValue(
      session?.model,
      turnContext?.model,
      nestedRecord(nestedRecord(turnContext, "collaboration_mode"), "settings")?.model,
      agent.model,
    ),
    effort: stringValue(session?.effort, effortFromTurnContext(turnContext)),
    branch: stringValue(
      session?.gitBranch,
      branchFromPayload(turnContext),
      branchFromPayload(sessionMeta),
      agent.branch,
    ),
    cwd: stringValue(session?.cwd, sessionMeta?.cwd, agent.cwd, agent.projectRoot),
    originator: stringValue(session?.originator, sessionMeta?.originator, sessionMeta?.source),
    attribution,
    turn: events.length > 0
      ? turnFactsFromTailEvents(events)
      : (observe?.live ? { phase: "started" } : { phase: "idle" }),
    usage,
    parentSessionId: transcript?.parentSessionId?.trim() || undefined,
    parentAgentName: transcript?.parentSessionId && parentAgent
      ? agentLabel(parentAgent)
      : undefined,
    currentTask: currentTaskFromTailEvents(events, observe),
  };

  const compaction = laneCompactionStateFromTail(events, usage, {
    model: facts.model,
    adapterType: transcript?.source ?? agent.harness,
  });
  if (compaction.eligible || compaction.lastCompactedAt !== null) {
    facts.compaction = {
      eligible: compaction.eligible,
      reason: compaction.reason,
      ...(compaction.lastCompactedAt !== null ? { lastCompactedAt: compaction.lastCompactedAt } : {}),
      ...(compaction.lastCompactedSummary ? { lastCompactedSummary: compaction.lastCompactedSummary } : {}),
    };
  }

  for (const key of ["model", "effort", "branch", "cwd", "originator", "attribution", "usage", "compaction", "currentTask"] as const) {
    if (facts[key] === undefined) delete facts[key];
  }
  return facts;
}

/** Work signal for lane admission — aligned with tail "work" display, not lifecycle noise. */
function isLaneAdmissionTailEvent(event: TailEvent): boolean {
  if (isTailNoiseEvent(event)) return false;

  if (event.kind === "tool"
    || event.kind === "tool-result"
    || event.kind === "assistant"
    || event.kind === "user") {
    return true;
  }

  if (event.kind !== "system") return false;

  if (event.source === "grok") {
    return /^turn /u.test(event.summary);
  }

  if (event.source === "codex") {
    const summary = event.summary.trim().toLowerCase();
    if (summary === "task started"
      || summary === "task complete"
      || summary.startsWith("turn aborted")) {
      return true;
    }
    const raw = event.raw;
    if (raw && typeof raw === "object" && !Array.isArray(raw)) {
      const payload = (raw as Record<string, unknown>).payload;
      if (payload && typeof payload === "object" && !Array.isArray(payload)) {
        const payloadType = (payload as Record<string, unknown>).type;
        if (payloadType === "reasoning" && summary !== "[reasoning]") {
          return true;
        }
      }
    }
  }

  return false;
}

function hasRecentLaneAdmissionTailEvents(
  events: TailEvent[],
  now: number,
  windowMs: number,
): boolean {
  return events.some((event) => {
    if (now - event.ts > windowMs) return false;
    return isLaneAdmissionTailEvent(event);
  });
}

function hasDisplayableLaneTrace(observe: ObserveData | null | undefined): boolean {
  return observe?.events.some(isSubstantiveObserveEvent) ?? false;
}

function normalizeTailSessionRef(value: string | null | undefined): string | null {
  const trimmed = value?.trim();
  if (!trimmed) return null;
  const leaf = trimmed.split("/").pop() ?? trimmed;
  return leaf.endsWith(".jsonl") ? leaf.slice(0, -".jsonl".length) : leaf;
}

function tailSessionRefsForTranscript(
  transcript: TailDiscoveredTranscript,
): string[] {
  const refs = new Set<string>();
  for (const candidate of [
    transcript.sessionId,
    transcript.transcriptPath,
    normalizeTailSessionRef(transcript.sessionId),
    normalizeTailSessionRef(transcript.transcriptPath),
  ]) {
    const trimmed = candidate?.trim();
    if (trimmed) refs.add(trimmed);
  }
  return [...refs];
}

function tailEventsForTranscript(
  transcript: TailDiscoveredTranscript,
  eventsBySession: Map<string, TailEvent[]>,
): TailEvent[] {
  const refs = tailSessionRefsForTranscript(transcript);
  const seen = new Set<string>();
  const events: TailEvent[] = [];
  for (const ref of refs) {
    for (const event of eventsBySession.get(ref) ?? []) {
      if (seen.has(event.id)) continue;
      seen.add(event.id);
      events.push(event);
    }
  }
  return events;
}

function scoutSessionRefsForAgent(agent: Agent): string[] {
  const refs = new Set<string>();
  const sessionId = agent.harnessSessionId?.trim();
  if (sessionId) {
    refs.add(sessionId);
    const normalized = normalizeTailSessionRef(sessionId);
    if (normalized) refs.add(normalized);
    const uuid = extractSessionUuid(sessionId);
    if (uuid) refs.add(uuid);
  }
  for (const candidate of [
    agent.harnessLogPath,
    agent.conversationId,
    extractSessionUuid(agent.harnessLogPath),
    extractSessionUuid(agent.conversationId),
  ]) {
    const trimmed = candidate?.trim();
    if (trimmed) refs.add(trimmed);
  }
  return [...refs];
}

/** Prefer deliberate scout cards over transport placeholders when several agents share a session ref. */
function scoutBindingRank(agent: Agent): number {
  if (!hasDesignedAgentCard(agent, "scout")) return 0;
  if (hasProviderHarnessSession(agent)) return 2;
  return 1;
}

function bindScoutAgent(
  scoutBySession: Map<string, Agent>,
  ref: string,
  agent: Agent,
): void {
  const existing = scoutBySession.get(ref);
  if (!existing) {
    scoutBySession.set(ref, agent);
    return;
  }
  const existingRank = scoutBindingRank(existing);
  const nextRank = scoutBindingRank(agent);
  if (nextRank > existingRank) {
    scoutBySession.set(ref, agent);
    return;
  }
  if (nextRank === existingRank && agent.id.localeCompare(existing.id) < 0) {
    scoutBySession.set(ref, agent);
  }
}

function scoutAgentForTranscript(
  transcript: TailDiscoveredTranscript,
  scoutBySession: Map<string, Agent>,
): Agent | undefined {
  for (const ref of tailSessionRefsForTranscript(transcript)) {
    const agent = scoutBySession.get(ref);
    if (agent) return agent;
  }
  return undefined;
}

function agentSharesTranscriptSession(
  agent: Agent,
  representedSessionRefs: ReadonlySet<string>,
): boolean {
  return scoutSessionRefsForAgent(agent).some((ref) => representedSessionRefs.has(ref));
}

function terminalSessionSharesRepresentedSession(
  session: TerminalSessionRecord,
  representedSessionRefs: ReadonlySet<string>,
): boolean {
  return terminalSessionRefs(session).some((ref) => representedSessionRefs.has(ref));
}

function sessionSubstantiveLastActiveAt(
  sessionId: string | null | undefined,
  eventsBySession: Map<string, TailEvent[]>,
  transcript?: TailDiscoveredTranscript,
): number {
  const events = transcript
    ? tailEventsForTranscript(transcript, eventsBySession)
    : (sessionId?.trim() ? eventsBySession.get(sessionId.trim()) ?? [] : []);
  let latest = 0;
  for (const event of events) {
    if (!isLaneAdmissionTailEvent(event)) continue;
    latest = Math.max(latest, event.ts);
  }
  return latest;
}

function terminalSessionSubstantiveLastActiveAt(
  session: TerminalSessionRecord,
  eventsBySession: Map<string, TailEvent[]>,
): number {
  let latest = 0;
  for (const ref of terminalSessionRefs(session)) {
    latest = Math.max(latest, sessionSubstantiveLastActiveAt(ref, eventsBySession));
  }
  return latest;
}

function transcriptActiveAt(
  transcript: TailDiscoveredTranscript,
  eventsBySession: Map<string, TailEvent[]>,
): number {
  return sessionSubstantiveLastActiveAt(transcript.sessionId, eventsBySession, transcript);
}

function scoutAgentForTerminalSession(
  session: TerminalSessionRecord,
  scoutBySession: Map<string, Agent>,
): Agent | undefined {
  for (const ref of terminalSessionRefs(session)) {
    const agent = scoutBySession.get(ref);
    if (agent) return agent;
  }
  return undefined;
}

function shouldUseSessionBackedPlaceholderLane(
  agent: Agent,
  now: number,
  windowMs: number,
): boolean {
  if (!hasProviderHarnessSession(agent)) return false;
  if (isIdleCodexRelay(agent)) return false;
  const transport = agent.transport?.trim();
  if (transport !== "pi_rpc" && transport !== "pairing_bridge") return false;
  const updatedAt = agent.updatedAt ?? 0;
  return updatedAt > 0 && now - updatedAt <= windowMs;
}

function agentProviderPresenceAt(
  agent: Agent,
): number {
  if (agent.retiredFromFleet || agent.staleLocalRegistration) return 0;
  if (!hasDesignedAgentCard(agent, "scout")) return 0;
  if (!hasProviderHarnessSession(agent)) return 0;
  if (isIdleCodexRelay(agent)) return 0;
  return Math.max(agent.updatedAt ?? 0, agent.createdAt ?? 0);
}

function agentSessionBackedObserveData(
  agent: Agent,
  current: boolean,
  lastActiveAt: number,
): ObserveData {
  return sessionBackedObserveData({
    id: agent.id,
    harness: agent.harness,
    sessionId: agent.harnessSessionId,
    cwd: agent.cwd ?? agent.projectRoot,
    model: agent.model,
    startedAt: lastActiveAt,
    current,
    detail: [agent.transport, agent.cwd ?? agent.projectRoot, agent.harnessSessionId]
      .filter(Boolean)
      .join(" · ") || null,
  });
}

function agentPresenceObserveData(
  agent: Agent,
  lastActiveAt: number,
): ObserveData {
  return {
    events: [],
    files: [],
    live: false,
    metadata: {
      session: {
        adapterType: agent.harness ?? undefined,
        cwd: agent.cwd ?? agent.projectRoot ?? undefined,
        externalSessionId: agent.harnessSessionId ?? undefined,
        sessionStart: lastActiveAt,
        model: agent.model ?? undefined,
        source: "agent-presence",
      },
    },
  };
}

function brokerActivityObserveData(
  agent: Agent,
  activity: NonNullable<Agent["brokerActivity"]>,
): ObserveData {
  const activeStates = new Set(["queued", "waking", "running", "waiting", "in_flight"]);
  return {
    events: activity.map((event, index): ObserveEvent => ({
      id: `broker:${event.kind}:${event.id}`,
      t: index,
      at: event.at,
      kind: event.kind === "flight" ? "tool" : event.kind === "invocation" ? "ask" : "message",
      text: event.summary,
      ...(event.kind === "flight" ? {
        tool: "scout flight",
        arg: event.state ?? undefined,
        live: Boolean(event.state && activeStates.has(event.state)),
      } : {}),
    })),
    files: [],
    live: activity.some((event) => Boolean(event.state && activeStates.has(event.state))),
    metadata: {
      session: {
        adapterType: agent.harness ?? "scout",
        cwd: agent.cwd ?? agent.projectRoot ?? undefined,
        sessionStart: activity[0]?.at,
        source: "broker-native",
        approvalPolicy: agent.runtimePolicy?.approvalPolicy ?? undefined,
        sandbox: agent.runtimePolicy?.sandbox ?? undefined,
      },
    },
  };
}

function hasNativeLaneWorkingSignal(
  events: TailEvent[],
  now: number,
  windowMs: number,
): boolean {
  return hasRecentLaneAdmissionTailEvents(events, now, windowMs);
}

/** True when the lane represents an agent actively doing work within the horizon. */
export function isAgentLaneWorking(
  lane: AgentLane,
  now: number = Date.now(),
  windowMs: number = agentLaneHorizonWindowMs(DEFAULT_AGENT_LANE_HORIZON),
  sessionSubstantiveAt = 0,
): boolean {
  const { agent, observe, lastActiveAt, source } = lane;
  if (lastActiveAt <= 0 || now - lastActiveAt > windowMs) {
    return false;
  }

  if (source === "native") {
    if (sessionSubstantiveAt > 0 && now - sessionSubstantiveAt <= windowMs) {
      return true;
    }
    return hasLiveSubstantiveWork(observe)
      || hasRecentSubstantiveObserve(observe, now, windowMs);
  }

  if (sessionSubstantiveAt > 0 && now - sessionSubstantiveAt <= windowMs) {
    return true;
  }

  if (hasLiveSubstantiveWork(observe)) {
    return true;
  }

  if (hasRecentSubstantiveObserve(observe, now, windowMs)) {
    return true;
  }

  return false;
}

function compareLanesById(a: AgentLane, b: AgentLane): number {
  return a.id.localeCompare(b.id);
}

function laneSessionRefs(lane: AgentLane): string[] {
  return [
    lane.agent.harnessSessionId,
    lane.agent.conversationId,
    lane.observe?.metadata?.session?.externalSessionId,
  ].filter((value): value is string => Boolean(value?.trim()));
}

/**
 * Keep harness-owned children beside their observed parent. Stable slots still
 * decide the order of unrelated lanes and of siblings under the same parent.
 */
function sortLanesByObservedLineage(
  lanes: AgentLane[],
  order: StableLaneOrder,
): AgentLane[] {
  const parentBySession = new Map<string, AgentLane>();
  for (const lane of lanes) {
    for (const ref of laneSessionRefs(lane)) parentBySession.set(ref, lane);
  }

  const parentByChildId = new Map<string, AgentLane>();
  for (const lane of lanes) {
    const parentSessionId = lane.facts?.parentSessionId?.trim();
    const parent = parentSessionId ? parentBySession.get(parentSessionId) : undefined;
    if (parent && parent.id !== lane.id) parentByChildId.set(lane.id, parent);
  }

  return [...lanes].sort((left, right) => {
    const leftParent = parentByChildId.get(left.id);
    const rightParent = parentByChildId.get(right.id);
    const leftRoot = leftParent ?? left;
    const rightRoot = rightParent ?? right;
    const leftRootSlot = order.slots.get(leftRoot.id) ?? Number.MAX_SAFE_INTEGER;
    const rightRootSlot = order.slots.get(rightRoot.id) ?? Number.MAX_SAFE_INTEGER;
    if (leftRootSlot !== rightRootSlot) return leftRootSlot - rightRootSlot;
    if (leftRoot.id !== rightRoot.id) return compareLanesById(leftRoot, rightRoot);
    if (left.id === leftRoot.id) return -1;
    if (right.id === rightRoot.id) return 1;
    const leftSlot = order.slots.get(left.id) ?? Number.MAX_SAFE_INTEGER;
    const rightSlot = order.slots.get(right.id) ?? Number.MAX_SAFE_INTEGER;
    if (leftSlot !== rightSlot) return leftSlot - rightSlot;
    return compareLanesById(left, right);
  });
}

const SESSION_UUID_RE = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

function extractSessionUuid(value: string | null | undefined): string | null {
  const match = value?.match(SESSION_UUID_RE);
  return match?.[0]?.toLowerCase() ?? null;
}

export type StableLaneOrder = {
  slots: Map<string, number>;
  nextSlot: number;
};

export function createStableLaneOrder(): StableLaneOrder {
  return { slots: new Map(), nextSlot: 0 };
}

/** Keep lane columns in first-seen order; new lanes append at the end. */
export function sortLanesWithStableOrder(
  lanes: AgentLane[],
  order: StableLaneOrder,
): { lanes: AgentLane[]; newLaneIds: string[] } {
  const newLaneIds: string[] = [];

  for (const lane of lanes) {
    const slotKey = lane.id;
    if (!order.slots.has(slotKey)) {
      order.slots.set(slotKey, order.nextSlot);
      order.nextSlot += 1;
      newLaneIds.push(lane.id);
    }
  }

  const activeSlotKeys = new Set(lanes.map((lane) => lane.id));
  for (const slotKey of [...order.slots.keys()]) {
    if (!activeSlotKeys.has(slotKey)) order.slots.delete(slotKey);
  }

  const sorted = sortLanesByObservedLineage(lanes, order);

  return { lanes: sorted, newLaneIds };
}

function canonicalScoutSessionKey(agent: Agent): string | null {
  return extractSessionUuid(agent.harnessSessionId)
    ?? normalizeTailSessionRef(agent.harnessSessionId)
    ?? agent.harnessSessionId?.trim()
    ?? null;
}

function agentLabel(agent: Agent): string {
  return agent.name.trim() || agent.id;
}

function rosterIssueId(kind: AgentLaneRosterIssueKind, sessionRef: string): string {
  return `${kind}:${sessionRef}`;
}

function pushRosterIssue(
  issues: AgentLaneRosterIssue[],
  seen: Set<string>,
  issue: Omit<AgentLaneRosterIssue, "id"> & { id?: string },
): void {
  const sessionRef = issue.sessionRef ?? issue.kind;
  const id = issue.id ?? rosterIssueId(issue.kind, sessionRef);
  if (seen.has(id)) return;
  seen.add(id);
  issues.push({ ...issue, id });
}

function selectedScoutAgentForSession(
  agents: Agent[],
  scoutBySession: Map<string, Agent>,
): Agent | undefined {
  for (const agent of agents) {
    for (const ref of scoutSessionRefsForAgent(agent)) {
      const bound = scoutBySession.get(ref);
      if (bound && agents.some((candidate) => candidate.id === bound.id)) {
        return bound;
      }
    }
  }
  return undefined;
}

/** Cursor process-monitor logs rotate files under one app sessionId. */
function transcriptGroupingKey(transcript: TailDiscoveredTranscript): string {
  if (transcript.source === "cursor") {
    return `${transcript.source}:path:${transcript.transcriptPath}`;
  }
  const sessionId = transcript.sessionId?.trim();
  return sessionId
    ? `${transcript.source}:${sessionId}`
    : `${transcript.source}:path:${transcript.transcriptPath}`;
}

function dedupeCursorTranscriptsForLanes(
  transcripts: TailDiscoveredTranscript[],
): TailDiscoveredTranscript[] {
  const bestBySession = new Map<string, TailDiscoveredTranscript>();
  const others: TailDiscoveredTranscript[] = [];
  for (const transcript of transcripts) {
    if (transcript.source !== "cursor") {
      others.push(transcript);
      continue;
    }
    const sessionId = transcript.sessionId?.trim() || transcript.transcriptPath;
    const existing = bestBySession.get(sessionId);
    if (!existing || transcript.mtimeMs > existing.mtimeMs) {
      bestBySession.set(sessionId, transcript);
    }
  }
  return [...others, ...bestBySession.values()];
}

const PROVIDER_HARNESS_TRANSPORTS = new Set([
  "codex_app_server",
  "claude_stream_json",
  "pairing_bridge",
  "pi_rpc",
]);

/** Configured registry placeholders without transport — not part of live lane roster diagnostics. */
export function isLaneRosterFleetAgent(agent: Agent): boolean {
  if (agent.retiredFromFleet || agent.staleLocalRegistration) return false;
  if (isTransportRefInHarnessSlot(agent.harnessSessionId, agent.terminalSurface)) return true;
  if (agent.terminalSurface || agent.transport?.trim()) return true;
  if (agent.state === "in_flight") return true;
  return hasProviderHarnessSession(agent);
}

/** Active provider transports should carry a harness session id; roster cards and terminal relays do not. */
export function expectsProviderHarnessSession(agent: Agent): boolean {
  if (agent.agentClass === "organic") return false;
  if ((agent.brokerActivity?.length ?? 0) > 0) return false;
  if (agent.terminalSurface) return false;
  const transport = agent.transport?.trim();
  if (!transport || transport === "tmux" || transport === "zellij") return false;
  if (!agent.harness?.trim()) return false;
  if (agent.state !== "in_flight") return false;
  return PROVIDER_HARNESS_TRANSPORTS.has(transport);
}

function collectDuplicateTranscriptIssues(
  transcripts: TailDiscoveredTranscript[],
): AgentLaneRosterIssue[] {
  const issues: AgentLaneRosterIssue[] = [];
  const seen = new Set<string>();
  const bySession = new Map<string, TailDiscoveredTranscript[]>();

  for (const transcript of transcripts) {
    const key = transcriptGroupingKey(transcript);
    const bucket = bySession.get(key) ?? [];
    bucket.push(transcript);
    bySession.set(key, bucket);
  }

  for (const [sessionRef, bucket] of bySession) {
    if (bucket.length <= 1) continue;
    pushRosterIssue(issues, seen, {
      kind: "duplicate_transcript_session",
      sessionRef,
      transcriptPaths: bucket.map((transcript) => transcript.transcriptPath),
      message: `Tail discovery returned ${bucket.length} transcripts for ${sessionRef}.`,
    });
  }

  return issues;
}

function collectScoutFleetIssues(
  scoutAgents: Agent[],
  scoutBySession: Map<string, Agent>,
): AgentLaneRosterIssue[] {
  const fleetAgents = scoutAgents.filter(isLaneRosterFleetAgent);
  const issues: AgentLaneRosterIssue[] = [];
  const seen = new Set<string>();
  const byCanonical = new Map<string, Agent[]>();

  for (const agent of fleetAgents) {
    const key = canonicalScoutSessionKey(agent);
    if (!key) continue;
    const bucket = byCanonical.get(key) ?? [];
    if (!bucket.some((candidate) => candidate.id === agent.id)) {
      bucket.push(agent);
    }
    byCanonical.set(key, bucket);
  }

  const pollutedHarness = fleetAgents.filter(
    (agent) => isTransportRefInHarnessSlot(agent.harnessSessionId, agent.terminalSurface),
  );
  if (pollutedHarness.length > 0) {
    pushRosterIssue(issues, seen, {
      kind: "harness_session_polluted",
      sessionRef: "harness-slot",
      agentIds: pollutedHarness.map((agent) => agent.id),
      agentNames: pollutedHarness.map(agentLabel),
      message: `${pollutedHarness.length} agent(s) store a transport ref in harnessSessionId — use terminalSurface for attach and harnessSessionId for provider ids only.`,
    });
  }

  const unboundHarness = fleetAgents.filter(
    (agent) => expectsProviderHarnessSession(agent) && !hasProviderHarnessSession(agent),
  );
  if (unboundHarness.length > 0) {
    pushRosterIssue(issues, seen, {
      kind: "harness_session_unbound",
      sessionRef: "fleet",
      agentIds: unboundHarness.map((agent) => agent.id),
      agentNames: unboundHarness.map(agentLabel),
      message: `${unboundHarness.length} scout agent(s) have no provider harness session bound (lanes use tail transcripts, not agent.id).`,
    });
  }

  for (const [sessionRef, agents] of byCanonical) {
    if (agents.length <= 1) continue;

    const selected = selectedScoutAgentForSession(agents, scoutBySession);
    const shadowed = agents.filter((agent) => agent.id !== selected?.id);
    if (shadowed.length === 0) continue;
    pushRosterIssue(issues, seen, {
      kind: "session_binding_conflict",
      sessionRef,
      agentIds: agents.map((agent) => agent.id),
      agentNames: agents.map(agentLabel),
      selectedAgentId: selected?.id,
      message: selected
        ? `Multiple scout agents claim ${sessionRef}; showing ${agentLabel(selected)}.`
        : `Multiple scout agents claim ${sessionRef} but none could be selected.`,
    });
  }

  return issues;
}

export function rosterIssuesFromTailDiscovery(
  discovery: { issues?: Array<{
    kind: "transcript_path_collision";
    sessionKey: string;
    message: string;
    transcriptPaths: string[];
  }> } | null | undefined,
): AgentLaneRosterIssue[] {
  if (!discovery?.issues?.length) return [];
  const seen = new Set<string>();
  const issues: AgentLaneRosterIssue[] = [];
  for (const issue of discovery.issues) {
    // Cursor process-monitor logs rotate files under one app session id; not a harness collision.
    if (issue.sessionKey.startsWith("cursor:")) continue;
    if (seen.has(issue.sessionKey)) continue;
    seen.add(issue.sessionKey);
    issues.push({
      id: rosterIssueId("transcript_path_collision", issue.sessionKey),
      kind: "transcript_path_collision",
      sessionRef: issue.sessionKey,
      transcriptPaths: issue.transcriptPaths,
      message: issue.message,
    });
  }
  return issues;
}

export function buildAgentLanes(input: {
  transcripts: TailDiscoveredTranscript[];
  tailEvents: TailEvent[];
  processes?: TailDiscoveredProcess[];
  scoutAgents?: Agent[];
  terminalSessions?: TerminalSessionRecord[];
  observeCache?: Record<string, ObserveCacheEntry | undefined>;
  now: number;
  workingOnly?: boolean;
  horizon?: AgentLaneHorizonKey;
  /** @deprecated Pass scoutAgents instead. */
  agents?: Agent[];
}): AgentLaneRosterBuild {
  const {
    transcripts: rawTranscripts,
    tailEvents,
    processes = [],
    scoutAgents = input.agents ?? [],
    terminalSessions = [],
    observeCache = {},
    now,
    workingOnly = true,
    horizon = DEFAULT_AGENT_LANE_HORIZON,
  } = input;
  const transcripts = dedupeCursorTranscriptsForLanes(rawTranscripts);
  const windowMs = agentLaneHorizonWindowMs(horizon);
  const lanes: AgentLane[] = [];

  const eventsBySession = new Map<string, TailEvent[]>();
  for (const event of tailEvents) {
    const bucket = eventsBySession.get(event.sessionId) ?? [];
    bucket.push(event);
    eventsBySession.set(event.sessionId, bucket);
  }

  const scoutBySession = new Map<string, Agent>();
  for (const agent of scoutAgents) {
    for (const ref of scoutSessionRefsForAgent(agent)) {
      bindScoutAgent(scoutBySession, ref, agent);
    }
  }

  const representedTranscriptSessionRefs = new Set<string>();
  const representedBoundAgentIds = new Set<string>();
  const rosterIssues: AgentLaneRosterIssue[] = [
    ...collectDuplicateTranscriptIssues(transcripts),
    ...collectScoutFleetIssues(scoutAgents, scoutBySession),
  ];
  const rosterIssueIds = new Set(rosterIssues.map((issue) => issue.id));

  for (const transcript of transcripts) {
    const sessionId = transcript.sessionId?.trim();
    const events = tailEventsForTranscript(transcript, eventsBySession);
    const lastActiveAt = transcriptActiveAt(transcript, eventsBySession);
    const current = lastActiveAt > 0 && now - lastActiveAt <= windowMs;
    if (!current) {
      continue;
    }

    const scoutAgent = scoutAgentForTranscript(transcript, scoutBySession);
    const parentAgent = transcript.parentSessionId
      ? scoutBySession.get(transcript.parentSessionId)
      : undefined;
    if (scoutAgent) representedBoundAgentIds.add(scoutAgent.id);
    const observe = observeDataFromTail(transcript, events, current, { now, windowMs });
    const hasLoadedTailEvents = events.length > 0;
    const facts = buildLaneFacts(
      transcript,
      events,
      scoutAgent ?? nativeSessionAgent(transcript, lastActiveAt, current),
      processes,
      observe,
      parentAgent,
    );
    const sessionSubstantiveAt = lastActiveAt;
    const lane: AgentLane = scoutAgent
      ? {
          id: scoutAgent.id,
          agent: { ...scoutAgent, updatedAt: lastActiveAt },
          source: "scout",
          observe,
          facts,
          lastActiveAt,
          current,
        }
      : {
          id: nativeSessionId(transcript),
          agent: nativeSessionAgent(transcript, lastActiveAt, current),
          source: "native",
          observe,
          facts,
          lastActiveAt,
          current,
        };
    if (workingOnly && !isAgentLaneWorking(lane, now, windowMs, sessionSubstantiveAt)) {
      continue;
    }
    if (hasLoadedTailEvents && !hasDisplayableLaneTrace(observe) && !isAgentLaneLive(observe)) {
      continue;
    }
    for (const ref of tailSessionRefsForTranscript(transcript)) {
      representedTranscriptSessionRefs.add(ref);
    }
    lanes.push(lane);
  }

  for (const session of terminalSessions) {
    if (!isRegisteredHarnessTerminalSession(session)) continue;
    if (terminalSessionSharesRepresentedSession(session, representedTranscriptSessionRefs)) {
      continue;
    }

    const sessionSubstantiveAt = terminalSessionSubstantiveLastActiveAt(session, eventsBySession);
    const lastActiveAt = Math.max(sessionSubstantiveAt, session.updatedAt ?? 0, session.createdAt ?? 0);
    const current = lastActiveAt > 0 && now - lastActiveAt <= windowMs;
    if (!current) continue;

    const scoutAgent = scoutAgentForTerminalSession(session, scoutBySession);
    if (scoutAgent) representedBoundAgentIds.add(scoutAgent.id);
    const terminalAgent = terminalSessionAgent(session, lastActiveAt, current);
    const agent = scoutAgent
      ? {
          ...scoutAgent,
          harnessSessionId: scoutAgent.harnessSessionId ?? session.sourceSessionId,
          terminalSurface: scoutAgent.terminalSurface ?? terminalAgent.terminalSurface,
          updatedAt: Math.max(scoutAgent.updatedAt ?? 0, lastActiveAt),
        }
      : terminalAgent;
    const observe = terminalSessionObserveData(session, current, lastActiveAt);
    const lane: AgentLane = {
      id: scoutAgent ? scoutAgent.id : nativeTerminalSessionId(session),
      agent,
      source: scoutAgent ? "scout" : "native",
      observe,
      facts: buildLaneFacts(null, [], agent, processes, observe),
      lastActiveAt,
      current,
    };
    if (workingOnly && !isAgentLaneWorking(lane, now, windowMs, sessionSubstantiveAt || lastActiveAt)) {
      continue;
    }
    for (const ref of terminalSessionRefs(session)) {
      representedTranscriptSessionRefs.add(ref);
    }
    lanes.push(lane);
  }

  for (const agent of scoutAgents) {
    const brokerActivity = recentBrokerActivity(agent, now, windowMs);
    if (isIdleCodexRelay(agent) && brokerActivity.length === 0) continue;
    if (!hasDesignedAgentCard(agent, "scout")) continue;
    const providerSession = hasProviderHarnessSession(agent);
    if (!providerSession && brokerActivity.length === 0) continue;
    if (providerSession && agentSharesTranscriptSession(agent, representedTranscriptSessionRefs)) {
      if (!representedBoundAgentIds.has(agent.id)) {
        const sessionRef = canonicalScoutSessionKey(agent) ?? agent.id;
        pushRosterIssue(rosterIssues, rosterIssueIds, {
          kind: "shadowed_scout_card",
          sessionRef,
          agentIds: [agent.id],
          agentNames: [agentLabel(agent)],
          message: `${agentLabel(agent)} is active but hidden because another lane already represents ${sessionRef}.`,
        });
      }
      continue;
    }

    const observeEntry = observeCache[agent.id];
    const sessionSubstantiveAt = providerSession
      ? sessionSubstantiveLastActiveAt(agent.harnessSessionId, eventsBySession)
      : 0;
    const brokerActivityAt = brokerActivity.at(-1)?.at ?? 0;
    const providerPresenceAt = agentProviderPresenceAt(agent);
    const placeholderEligible = shouldUseSessionBackedPlaceholderLane(agent, now, windowMs);
    const placeholderAt = placeholderEligible ? agent.updatedAt ?? 0 : 0;
    const lastActiveAt = Math.max(
      laneActivityAt(agent, observeEntry, now),
      sessionSubstantiveAt,
      placeholderAt,
      providerPresenceAt,
      brokerActivityAt,
    );
    const current = lastActiveAt > 0 && now - lastActiveAt <= windowMs;
    let observe = filterObserveDataForHorizonWithFill(observeEntry?.data ?? null, now, windowMs);
    if (!observe && brokerActivity.length > 0) {
      observe = brokerActivityObserveData(agent, brokerActivity);
    }
    if (
      placeholderEligible
      && current
      && !hasDisplayableLaneTrace(observe)
      && !isAgentLaneLive(observe)
    ) {
      observe = agentSessionBackedObserveData(agent, current, lastActiveAt);
    } else if (!observe && providerPresenceAt > 0) {
      observe = agentPresenceObserveData(agent, lastActiveAt);
    }
    const lane: AgentLane = {
      id: agent.id,
      agent,
      source: "scout",
      observe,
      facts: buildLaneFacts(null, [], agent, processes, observe),
      lastActiveAt,
      current,
    };
    // Provider registration proves that the card is bound, not that it is
    // active forever. Only let presence bypass trace-based admission while the
    // registration itself is inside the selected lane horizon. Broker activity
    // is already horizon-filtered by recentBrokerActivity above.
    const providerPresent = providerPresenceAt > 0 && now - providerPresenceAt <= windowMs;
    const present = providerPresent || brokerActivityAt > 0;
    if (workingOnly && !present && !isAgentLaneWorking(lane, now, windowMs, sessionSubstantiveAt)) {
      continue;
    }
    if (!present && !hasDisplayableLaneTrace(observe) && !isAgentLaneLive(observe)) {
      continue;
    }
    lanes.push(lane);
  }

  return {
    lanes: lanes.sort(compareLanesById),
    issues: rosterIssues,
  };
}
