import { describe, expect, test } from "bun:test";

import type { TerminalSessionRecord } from "@openscout/protocol";
import type { Agent } from "../../lib/types.ts";
import {
  agentLaneHorizonWindowMs,
  buildLaneFacts,
  buildAgentLanes,
  createStableLaneOrder,
  expectsProviderHarnessSession,
  isLaneRosterFleetAgent,
  hasDesignedAgentCard,
  isAutoGeneratedLaneAgentName,
  isAgentLaneWorking,
  isIdleCodexRelay,
  laneContextLabel,
  lanePrimaryLabel,
  laneStatusLabel,
  observeDataFromTail,
  resolveTranscriptAttribution,
  rosterIssuesFromTailDiscovery,
  shouldPollAgentForLaneObserve,
  sortLanesWithStableOrder,
  type AgentLane,
} from "./agent-lanes-model.ts";
import { agentLaneToCardModel } from "./agent-lane-card-model.ts";

const NOW = 1_700_000_000_000;

function lane(overrides: Partial<AgentLane> & { agent: Agent }): AgentLane {
  return {
    id: overrides.agent.id,
    source: "scout",
    observe: null,
    lastActiveAt: NOW - 5_000,
    current: true,
    ...overrides,
  };
}

describe("lane display labels", () => {
  test("uses project for auto-generated native session names", () => {
    const agent = stubAgent("Grok 0f8eddbb");
    agent.agentClass = "organic";
    agent.harness = "grok";
    agent.project = "openscout";

    expect(isAutoGeneratedLaneAgentName(agent)).toBe(true);
    expect(hasDesignedAgentCard(agent, "native")).toBe(false);
    expect(lanePrimaryLabel(agent, "native")).toBe("openscout");
    expect(laneStatusLabel(agent, "native")).toBe("grok");
    expect(laneContextLabel(agent, "native")).toBe("grok");
  });

  test("keeps deliberate scout agent card names", () => {
    const agent = stubAgent("openscout-card");
    agent.project = "openscout";
    agent.harness = "codex";
    agent.harnessSessionId = "sess-codex-live";

    expect(isAutoGeneratedLaneAgentName(agent)).toBe(false);
    expect(hasDesignedAgentCard(agent, "scout")).toBe(true);
    expect(lanePrimaryLabel(agent, "scout")).toBe("openscout-card");
    expect(laneStatusLabel(agent, "scout")).toBe("codex");
    expect(laneContextLabel(agent, "scout")).toBe("openscout");
  });
});

describe("agent lane card model", () => {
  test("uses tokens in context for the compact token readout", () => {
    const agent = stubAgent("scope");
    const model = agentLaneToCardModel(
      lane({
        agent,
        facts: {
          touchedFiles: [],
          usage: {
            inputTokens: 14_687_351,
            contextInputTokens: 249_229,
            outputTokens: 56_686,
            totalTokens: 14_744_037,
            contextWindowTokens: 1_000_000,
          },
          turn: { phase: "complete", index: 2 },
        },
      }),
      { isLive: false, nowMs: NOW },
    );

    expect(model.context).toBe(25);
    expect(model.tokens).toBe("249.2k");
    expect(model.tokenUsage?.total).toBe(14_744_037);
  });

  test("labels a child lane with its observed Scout parent", () => {
    const agent = stubAgent("claude subagent worker123");
    agent.agentClass = "organic";
    agent.role = "subagent";
    agent.harness = "claude";
    agent.harnessSessionId = "worker123";

    const model = agentLaneToCardModel(lane({
      source: "native",
      agent,
      facts: {
        touchedFiles: [],
        parentSessionId: "parent-session-123456",
        parentAgentName: "fable",
      },
    }), { isLive: true, nowMs: NOW });

    expect(model.name).toBe("claude subagent worker123");
    expect(model.parentSessionId).toBe("parent-session-123456");
    expect(model.parentSessionLabel).toBe("fable · parent-s");
  });
});

describe("isAgentLaneWorking", () => {
  test("excludes in-flight scout agents without substantive trace activity", () => {
    const agent: Agent = {
      id: "agent:alpha",
      definitionId: "alpha",
      name: "alpha",
      handle: null,
      agentClass: "managed",
      harness: "claude",
      state: "in_flight",
      projectRoot: null,
      cwd: null,
      updatedAt: NOW - 3 * 60_000,
      createdAt: null,
      transport: null,
      selector: null,
      defaultSelector: null,
      nodeQualifier: null,
      workspaceQualifier: null,
      wakePolicy: null,
      capabilities: [],
      project: null,
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "claude-hung-session",
      harnessLogPath: null,
      terminalSurface: null,
      conversationId: "conv-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
      staleLocalRegistration: false,
      retiredFromFleet: false,
      replacedByAgentId: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 3 * 60_000,
      observe: null,
    }), NOW)).toBe(false);
  });

  test("includes in-flight scout agents with recent substantive observe activity", () => {
    const agent: Agent = {
      id: "agent:alpha",
      definitionId: "alpha",
      name: "alpha",
      handle: null,
      agentClass: "managed",
      harness: "codex",
      state: "in_flight",
      projectRoot: null,
      cwd: null,
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      defaultSelector: null,
      nodeQualifier: null,
      workspaceQualifier: null,
      wakePolicy: null,
      capabilities: [],
      project: null,
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "sess-live",
      harnessLogPath: null,
      terminalSurface: null,
      conversationId: "conv-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
      staleLocalRegistration: false,
      retiredFromFleet: false,
      replacedByAgentId: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 15_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 15,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: true,
        metadata: {
          session: {
            sessionStart: NOW - 15_000,
          },
        },
      },
    }), NOW)).toBe(true);
  });

  test("excludes organic processes without substantive observe activity", () => {
    const agent: Agent = {
      id: "harness:codex:1234",
      definitionId: "codex",
      name: "codex",
      handle: null,
      agentClass: "organic",
      harness: "codex",
      state: "working",
      projectRoot: "/tmp/repo",
      cwd: "/tmp/repo",
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      defaultSelector: null,
      nodeQualifier: null,
      workspaceQualifier: null,
      wakePolicy: null,
      capabilities: [],
      project: "repo",
      branch: null,
      role: null,
      model: null,
      harnessSessionId: null,
      harnessLogPath: null,
      terminalSurface: null,
      conversationId: "harness:1234",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
      staleLocalRegistration: false,
      retiredFromFleet: false,
      replacedByAgentId: null,
    };

    expect(isAgentLaneWorking(lane({ agent }), NOW)).toBe(false);
  });

  test("includes lanes with recent tool activity in observe", () => {
    const agent: Agent = {
      id: "harness:codex:5678",
      definitionId: "codex",
      name: "codex",
      handle: null,
      agentClass: "organic",
      harness: "codex",
      state: "working",
      projectRoot: "/tmp/repo",
      cwd: "/tmp/repo",
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      defaultSelector: null,
      nodeQualifier: null,
      workspaceQualifier: null,
      wakePolicy: null,
      capabilities: [],
      project: "repo",
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "sess-1",
      harnessLogPath: "/tmp/sess.jsonl",
      terminalSurface: null,
      conversationId: "sess-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
      staleLocalRegistration: false,
      retiredFromFleet: false,
      replacedByAgentId: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 120_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 120,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: true,
        metadata: {
          session: {
            sessionStart: NOW - 120_000,
          },
        },
      },
    }), NOW)).toBe(true);
  });

  test("excludes idle codex warmup boots from lane working signal", () => {
    const agent = stubAgent("Atelier");
    agent.harness = "codex";
    agent.transport = "codex_app_server";
    agent.state = "available";
    agent.harnessSessionId = "019ee108-5864-70e2-8de6-ffe81b21e8be";
    agent.project = "Atelier";

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 30_000,
      observe: {
        events: [{
          id: "boot",
          t: 0,
          kind: "boot",
          text: "Session started · gpt-5.5",
          detail: "workspace: /Users/art/dev/atelier · turns: 0 · status: idle",
        }],
        files: [],
        live: true,
        metadata: {
          session: {
            sessionStart: NOW - 30_000,
          },
        },
      },
    }), NOW)).toBe(false);
  });

  test("respects the selected activity window", () => {
    const agent = stubAgent("alpha");
    agent.state = "callable";
    const staleLane = lane({
      agent,
      lastActiveAt: NOW - 20 * 60_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 612,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: false,
        metadata: {
          session: {
            sessionStart: NOW - 3 * 60 * 60_000,
          },
        },
      },
    });

    expect(isAgentLaneWorking(staleLane, NOW, agentLaneHorizonWindowMs("5m"))).toBe(false);
    expect(isAgentLaneWorking(staleLane, NOW, agentLaneHorizonWindowMs("30m"))).toBe(false);
  });

  test("excludes recently touched transcripts without substantive tail activity", () => {
    const sessionId = "019edd5a-ad7c-7563-8b28-a9d34699a369";
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "claude",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId,
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [
        stubTailEvent(sessionId, NOW - 15_000, "system", {
          source: "claude",
          summary: "agent-name",
        }),
        stubTailEvent(sessionId, NOW - 14_000, "system", {
          source: "claude",
          summary: "permission-mode",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("uses the last substantive event instead of a newer transcript mtime", () => {
    const sessionId = "019edd5a-ad7c-7563-8b28-a9d34699a369";
    const substantiveAt = NOW - 10 * 60_000;
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "claude",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId,
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent(sessionId, substantiveAt, "assistant", {
        source: "claude",
        summary: "Finished the requested review.",
      })],
      now: NOW,
      horizon: "30m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.lastActiveAt).toBe(substantiveAt);
  });

  test("includes native codex lanes with recent substantive tail events", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "019edd5a-ad7c-7563-8b28-a9d34699a369",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent("019edd5a-ad7c-7563-8b28-a9d34699a369", NOW - 15_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("codex");
  });

  test("maps a recent Kimi transcript and tool activity into a native lane", () => {
    const sessionId = "session_a8ddc351-12b4-42e4-bb3d-ea3d975fafa4";
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "kimi",
        transcriptPath: `/Users/art/.kimi-code/sessions/wd_openscout/session/${sessionId}/agents/main/wire.jsonl`,
        sessionId,
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent(sessionId, NOW - 10_000, "tool", {
        source: "kimi",
        summary: "Read packages/web/client/components/HarnessMark.tsx",
      })],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.id).toBe(`native:kimi:${sessionId}`);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("kimi");
    expect(lanes[0]?.agent.harnessSessionId).toBe(sessionId);
    expect(lanes[0]?.observe?.events[0]?.kind).toBe("tool");
  });

  test("includes native codex lanes with recent task lifecycle activity", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "019ede3a-7fef-7750-a51c-0f2428f8dcee",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [
        stubTailEvent("019ede3a-7fef-7750-a51c-0f2428f8dcee", NOW - 12_000, "system", {
          source: "codex",
          summary: "task started",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("codex");
  });

  test("excludes native grok lanes with only streaming phase noise", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "grok",
        transcriptPath: "/Users/art/.grok/sessions/%2FUsers%2Fart%2Fdev%2Fopenscout/sess-grok/events.jsonl",
        sessionId: "sess-grok",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [
        stubTailEvent("sess-grok", NOW - 10_000, "system", {
          source: "grok",
          summary: "phase · streaming_reasoning",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("includes native grok lanes with recent tool activity", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "grok",
        transcriptPath: "/Users/art/.grok/sessions/%2FUsers%2Fart%2Fdev%2Fopenscout/sess-grok/events.jsonl",
        sessionId: "sess-grok",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [
        stubTailEvent("sess-grok", NOW - 10_000, "tool", {
          source: "grok",
          summary: "Grep · pattern",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("grok");
  });

  test("does not let a scout-managed process from another source claim a native transcript", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "grok",
        transcriptPath: "/Users/art/.grok/sessions/%2FUsers%2Fart%2Fdev%2Fopenscout/sess-grok/events.jsonl",
        sessionId: "sess-grok",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [
        stubTailEvent("sess-grok", NOW - 10_000, "tool", {
          source: "grok",
          summary: "Grep · pattern",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.agent.harness).toBe("grok");
  });

  test("includes scout-managed codex lanes when no scout agent owns the session", () => {
    const { lanes } = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 15_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 10_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("codex");
    expect(resolveTranscriptAttribution({
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-codex-live",
      cwd: "/Users/art/dev/openscout",
      project: "openscout",
      harness: "unattributed",
      mtimeMs: NOW,
      size: 1,
    }, [{
      pid: 42,
      ppid: 1,
      command: "codex app-server",
      etime: "01:00",
      cwd: "/Users/art/dev/openscout",
      harness: "scout-managed",
      parentChain: [],
      source: "codex",
    }])).toBe("scout-managed");
  });

  test("includes scout codex agents when substantive tail events are fresh but observe is stale", () => {
    const agent = stubAgent("openscout-card");
    agent.harnessSessionId = "sess-codex-live";
    agent.state = "callable";
    agent.updatedAt = NOW - 3 * 60 * 60_000;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 15_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 12_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });

  test("prefers the scout lane when it owns a session with fresh substantive tail events", () => {
    const agent = stubAgent("openscout-card");
    agent.harnessSessionId = "sess-codex-live";
    agent.state = "callable";
    agent.updatedAt = NOW - 3 * 60 * 60_000;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 10_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 8_000, "assistant")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });

  test("enriches Grok StrReplace tail events with old/new preview metadata", () => {
    const transcript = {
      source: "grok",
      transcriptPath: "/tmp/grok-strreplace.jsonl",
      sessionId: "sess-strreplace",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const path = "packages/web/client/lib/tail-display.ts";
    const data = observeDataFromTail(transcript, [
      {
        id: "replace",
        ts: NOW - 2_000,
        source: "grok",
        sessionId: "sess-strreplace",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool",
        summary: `StrReplace · ${path} · edit: -const max = 96; · +const max = 120;`,
        raw: {
          tool_name: "StrReplace",
          tool_arg: path,
          tool_input: {
            path,
            old_string: "const max = 96;",
            new_string: "const max = 120;",
          },
        },
      },
    ], true);

    expect(data.events).toHaveLength(1);
    expect(data.events[0]?.tool).toBe("StrReplace");
    expect(data.events[0]?.arg).toBe(path);
    expect(data.events[0]?.detail).toContain("old:\nconst max = 96;");
    expect(data.events[0]?.detail).toContain("new:\nconst max = 120;");
    expect(data.events[0]?.diff?.preview).toContain("-const max = 96;");
    expect(data.events[0]?.diff?.preview).toContain("+const max = 120;");
  });

  test("filters grok streaming noise and maps tool names from summaries", () => {
    const transcript = {
      source: "grok",
      transcriptPath: "/tmp/grok.jsonl",
      sessionId: "sess-grok",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      {
        id: "phase",
        ts: NOW - 5_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "system",
        summary: "phase · streaming_text",
      },
      {
        id: "read",
        ts: NOW - 3_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool",
        summary: "Read started",
      },
      {
        id: "shell",
        ts: NOW - 1_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool-result",
        summary: "Shell completed · success",
      },
    ], true);

    expect(data.events.map((event) => event.text)).toEqual([
      "Read · started",
      "Shell · completed",
    ]);
    expect(data.events[0]?.tool).toBe("Read");
    expect(data.events[1]?.tool).toBe("Shell");
    expect(data.events[0]?.detail).toBeUndefined();
  });

  test("tops the trace tail up past the horizon when the window is sparse", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-horizon",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const events = [
      stubTailEvent("sess-horizon", NOW - 45 * 60_000, "tool", { summary: "stale" }),
      stubTailEvent("sess-horizon", NOW - 20 * 60_000, "tool", { summary: "recent-a" }),
      stubTailEvent("sess-horizon", NOW - 5 * 60_000, "assistant", { summary: "recent-b" }),
    ];

    const data = observeDataFromTail(transcript, events, true, {
      now: NOW,
      windowMs: 30 * 60_000,
    });

    // Presence is horizon-gated by the caller; content keeps a tail of history
    // (up to LANE_TRACE_FILL_MIN) so a present-but-quiet lane isn't empty.
    expect(data.events.map((event) => event.text)).toEqual([
      "stale",
      "recent-a",
      "recent-b",
    ]);
    expect(data.metadata?.session?.sessionStart).toBe(NOW - 45 * 60_000);
  });

  test("keeps the trace window-only when the horizon already fills the lane", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-dense",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const events = [
      stubTailEvent("sess-dense", NOW - 45 * 60_000, "tool", { summary: "stale" }),
      ...Array.from({ length: 60 }, (_, index) =>
        stubTailEvent("sess-dense", NOW - (60 - index) * 1_000, "tool", { summary: `in-window-${index}` })),
    ];

    const data = observeDataFromTail(transcript, events, true, {
      now: NOW,
      windowMs: 30 * 60_000,
    });

    expect(data.events).toHaveLength(60);
    expect(data.events.some((event) => event.text === "stale")).toBe(false);
    expect(data.events.every((event) => (event.at ?? 0) >= NOW - 30 * 60_000)).toBe(true);
  });

  test("uses latest-turn usage from raw token events inside the selected horizon", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-usage-horizon",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      stubTailEvent("sess-usage-horizon", NOW - 20 * 60_000, "system", {
        summary: "tokens · 1000000",
        raw: {
          type: "event_msg",
          payload: {
            type: "token_count",
            info: {
              total_token_usage: {
                input_tokens: 900_000,
                cached_input_tokens: 800_000,
                output_tokens: 100_000,
                total_tokens: 1_000_000,
              },
              last_token_usage: {
                input_tokens: 90_000,
                cached_input_tokens: 80_000,
                output_tokens: 10_000,
                total_tokens: 100_000,
              },
            },
          },
        },
      }),
      stubTailEvent("sess-usage-horizon", NOW - 2 * 60_000, "system", {
        summary: "tokens · 500000",
        raw: {
          type: "event_msg",
          payload: {
            type: "token_count",
            info: {
              total_token_usage: {
                input_tokens: 499_000,
                cached_input_tokens: 450_000,
                output_tokens: 1_000,
                reasoning_output_tokens: 250,
                total_tokens: 500_000,
              },
              last_token_usage: {
                input_tokens: 50_000,
                cached_input_tokens: 30_000,
                output_tokens: 800,
                reasoning_output_tokens: 125,
                total_tokens: 50_800,
              },
              model_context_window: 200_000,
            },
            rate_limits: { plan_type: "pro" },
          },
        },
      }),
      stubTailEvent("sess-usage-horizon", NOW - 1_000, "tool", { summary: "grep foo" }),
    ], true, {
      now: NOW,
      windowMs: 5 * 60_000,
    });

    expect(data.events.map((event) => event.text)).toEqual(["bash · grep foo"]);
    expect(data.metadata?.usage?.inputTokens).toBe(50_000);
    expect(data.metadata?.usage?.cacheReadInputTokens).toBe(30_000);
    expect(data.metadata?.usage?.outputTokens).toBe(800);
    expect(data.metadata?.usage?.reasoningOutputTokens).toBe(125);
    expect(data.metadata?.usage?.totalTokens).toBe(50_800);
    // cached_input_tokens is a subset of input_tokens — context is last input only
    expect(data.metadata?.usage?.contextInputTokens).toBe(50_000);
    expect(data.metadata?.usage?.contextWindowTokens).toBe(200_000);
    expect(data.metadata?.usage?.planType).toBe("pro");
  });

  test("does not leak stale token totals into a lane horizon with no recent token event", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-stale-usage",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      stubTailEvent("sess-stale-usage", NOW - 20 * 60_000, "system", {
        summary: "tokens · 1000000",
        raw: {
          type: "event_msg",
          payload: {
            type: "token_count",
            info: {
              total_token_usage: {
                input_tokens: 900_000,
                output_tokens: 100_000,
                total_tokens: 1_000_000,
              },
            },
          },
        },
      }),
      stubTailEvent("sess-stale-usage", NOW - 1_000, "tool", { summary: "grep foo" }),
    ], true, {
      now: NOW,
      windowMs: 5 * 60_000,
    });

    expect(data.events.map((event) => event.text)).toEqual(["bash · grep foo"]);
    expect(data.metadata?.usage).toBeUndefined();
  });

  test("maps tail event timestamps into lane observe metadata", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-1",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      {
        id: "e1",
        ts: NOW - 4_000,
        source: "codex",
        sessionId: "sess-1",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool",
        summary: "grep foo",
      },
      {
        id: "e2",
        ts: NOW - 1_000,
        source: "codex",
        sessionId: "sess-1",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "assistant",
        summary: "done",
      },
    ], true);

    expect(data.metadata?.session?.sessionStart).toBe(NOW - 4_000);
    expect(data.events[1]?.t).toBe(3);
  });

  test("enriches codex tail observe metadata with session facts and usage", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-facts",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const events = [
      stubTailEvent("sess-facts", NOW - 6_000, "system", {
        summary: "session sess-facts · /repo",
        raw: {
          type: "session_meta",
          payload: {
            id: "sess-facts",
            cwd: "/repo",
            originator: "Codex Desktop",
            cli_version: "0.140.0-alpha.19",
            source: "vscode",
            model_provider: "openai",
          },
        },
      }),
      stubTailEvent("sess-facts", NOW - 5_000, "system", {
        summary: "task started",
        raw: { type: "event_msg", payload: { type: "task_started" } },
      }),
      stubTailEvent("sess-facts", NOW - 4_000, "system", {
        summary: "turn context · gpt-5.5 · xhigh",
        raw: {
          type: "turn_context",
          payload: {
            cwd: "/repo",
            model: "gpt-5.5",
            effort: "xhigh",
            git_branch: "main",
          },
        },
      }),
      stubTailEvent("sess-facts", NOW - 3_000, "system", {
        summary: "tokens · 42",
        raw: {
          type: "event_msg",
          payload: {
            type: "token_count",
            info: {
              total_token_usage: {
                input_tokens: 20,
                cached_input_tokens: 4,
                output_tokens: 22,
                reasoning_output_tokens: 8,
                total_tokens: 42,
              },
              last_token_usage: {
                input_tokens: 12,
                cached_input_tokens: 4,
                output_tokens: 22,
                reasoning_output_tokens: 8,
                total_tokens: 34,
              },
              model_context_window: 1000,
            },
            rate_limits: { plan_type: "pro" },
          },
        },
      }),
      stubTailEvent("sess-facts", NOW - 2_000, "user", {
        summary: "Implement Agent Lanes roll-ups",
      }),
      stubTailEvent("sess-facts", NOW - 1_000, "tool", {
        summary: "apply_patch({\"patch\":\"*** Begin Patch\\n*** Update File: packages/web/client/screens/ops/agent-lanes-model.ts\\n@@\\n-old\\n+new\\n*** End Patch\"})",
        raw: {
          type: "response_item",
          payload: {
            type: "function_call",
            name: "apply_patch",
            arguments: "{\"patch\":\"*** Begin Patch\\n*** Update File: packages/web/client/screens/ops/agent-lanes-model.ts\\n@@\\n-old\\n+new\\n*** End Patch\"}",
          },
        },
      }),
    ];
    const data = observeDataFromTail(transcript, events, true);
    const agent = stubAgent("openscout-card");
    const facts = buildLaneFacts(transcript, events, agent, [{
      pid: 42,
      ppid: 1,
      command: "codex app-server",
      etime: "01:00",
      cwd: "/repo",
      harness: "scout-managed",
      parentChain: [],
      source: "codex",
    }], data);

    expect(data.metadata?.session?.model).toBe("gpt-5.5");
    expect(data.metadata?.session?.effort).toBe("xhigh");
    expect(data.metadata?.session?.originator).toBe("Codex Desktop");
    expect(data.metadata?.usage?.totalTokens).toBe(42);
    // last.input_tokens only (cached is a subset, not additive)
    expect(data.metadata?.usage?.contextInputTokens).toBe(12);
    expect(data.metadata?.usage?.contextWindowTokens).toBe(1000);
    expect(data.metadata?.usage?.cacheReadInputTokens).toBe(4);
    expect(facts.model).toBe("gpt-5.5");
    expect(facts.effort).toBe("xhigh");
    expect(facts.branch).toBe("main");
    expect(facts.attribution).toBe("scout-managed");
    expect(facts.turn?.phase).toBe("started");
    expect(facts.currentTask).toContain("Agent Lanes");
    expect(facts.touchedFiles.map((file) => file.path)).toContain(
      "packages/web/client/screens/ops/agent-lanes-model.ts",
    );
  });

  test("enriches Claude tail observe metadata with latest-turn context usage", () => {
    const transcript = {
      source: "claude",
      transcriptPath: "/tmp/claude.jsonl",
      sessionId: "claude-facts",
      cwd: "/repo",
      project: "repo",
      harness: "scout-managed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const events = [
      stubTailEvent("claude-facts", NOW - 2_000, "assistant", {
        source: "claude",
        raw: {
          type: "assistant",
          timestamp: "2026-06-20T20:00:00.000Z",
          message: {
            id: "msg-1",
            role: "assistant",
            model: "claude-opus-4-8",
            content: [{ type: "text", text: "done" }],
            usage: {
              input_tokens: 2,
              cache_read_input_tokens: 91_793,
              cache_creation_input_tokens: 1_478,
              output_tokens: 1_647,
              service_tier: "standard",
              speed: "standard",
            },
          },
        },
      }),
    ];

    const data = observeDataFromTail(transcript, events, true);

    expect(data.metadata?.usage?.contextInputTokens).toBe(93_273);
    expect(data.metadata?.usage?.contextWindowTokens).toBe(1_000_000);
    expect(data.metadata?.usage?.totalTokens).toBe(94_920);
  });

  test("excludes stale observe history even when poll metadata is fresh", () => {
    const agent = stubAgent("dewey");
    agent.state = "callable";
    agent.updatedAt = NOW;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/dewey.jsonl",
          sessionId: "sess-dewey",
          updatedAt: NOW,
          data: {
            events: [{
              id: "evt-1",
              t: 612,
              kind: "message",
              text: "old reply",
              to: "human",
            }],
            files: [],
            live: true,
            metadata: {
              session: {
                sessionStart: NOW - 3 * 60 * 60_000,
              },
            },
          },
        },
      },
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("drops provider-present scout lanes when registration and trace rows fall outside the horizon", () => {
    const agent = stubAgent("dewey-present");
    agent.state = "callable";
    agent.transport = "codex_app_server";
    agent.harnessSessionId = "sess-dewey-present";
    agent.updatedAt = NOW - 60 * 60_000;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/dewey-present.jsonl",
          sessionId: "sess-dewey-present",
          updatedAt: NOW,
          data: {
            events: [{
              id: "evt-1",
              t: 612,
              kind: "message",
              text: "old reply",
              to: "human",
            }],
            files: [],
            live: false,
            metadata: {
              session: {
                sessionStart: NOW - 3 * 60 * 60_000,
              },
            },
          },
        },
      },
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });
});

describe("sortLanesWithStableOrder", () => {
  test("keeps existing lanes in first-seen order as activity timestamps change", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    const beta = lane({ agent: stubAgent("beta"), lastActiveAt: NOW - 60_000 });

    const first = sortLanesWithStableOrder([alpha, beta], order);
    expect(first.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:beta"]);

    const bumpedBeta = { ...beta, lastActiveAt: NOW + 30_000 };
    const staleAlpha = { ...alpha, lastActiveAt: NOW - 120_000 };
    const second = sortLanesWithStableOrder([bumpedBeta, staleAlpha], order);
    expect(second.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:beta"]);
    expect(second.newLaneIds).toEqual([]);
  });

  test("appends newly working agents at the end", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    sortLanesWithStableOrder([alpha], order);

    const gamma = lane({ agent: stubAgent("gamma") });
    const result = sortLanesWithStableOrder([alpha, gamma], order);
    expect(result.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:gamma"]);
    expect(result.newLaneIds).toEqual(["agent:gamma"]);
  });

  test("re-admits returning agents at the end after they leave the roster", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    sortLanesWithStableOrder([alpha], order);
    sortLanesWithStableOrder([], order);

    const result = sortLanesWithStableOrder([alpha], order);
    expect(result.lanes.map((item) => item.id)).toEqual(["agent:alpha"]);
    expect(result.newLaneIds).toEqual(["agent:alpha"]);
  });

  test("keeps observed child lanes directly after their parent", () => {
    const order = createStableLaneOrder();
    const parentAgent = stubAgent("fable");
    parentAgent.harnessSessionId = "parent-session";
    const parent = lane({ agent: parentAgent });
    const unrelated = lane({ agent: stubAgent("other") });
    const childAgent = stubAgent("claude subagent worker");
    childAgent.agentClass = "organic";
    childAgent.role = "subagent";
    childAgent.harnessSessionId = "worker";
    const child = lane({
      agent: childAgent,
      source: "native",
      facts: { touchedFiles: [], parentSessionId: "parent-session" },
    });

    const result = sortLanesWithStableOrder([parent, unrelated, child], order);
    expect(result.lanes.map((item) => item.id)).toEqual([
      "agent:fable",
      "agent:claude subagent worker",
      "agent:other",
    ]);
  });
});

describe("buildAgentLanes roster", () => {
  test("surfaces binding conflicts when multiple scout agents share one session", () => {
    const mkAgent = (suffix: string) => {
      const agent = stubAgent(`relay-card-${suffix}`);
      agent.harness = "claude";
      agent.harnessSessionId = "claude-sess-live";
      return agent;
    };

    const { lanes, issues } = buildAgentLanes({
      scoutAgents: [mkAgent("a"), mkAgent("b"), mkAgent("c")],
      transcripts: [{
        source: "claude",
        transcriptPath: "/tmp/claude/live.jsonl",
        sessionId: "claude-sess-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 10_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent("claude-sess-live", NOW - 8_000, "assistant", { source: "claude" })],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(issues.some((issue) => issue.kind === "session_binding_conflict")).toBe(true);
  });

  test("surfaces transport refs stored in harnessSessionId", () => {
    const agent = stubAgent("relay-flight");
    agent.harness = "claude";
    agent.harnessSessionId = "relay-openscout-card-flight-claude";

    const { issues } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(issues.some((issue) => issue.kind === "harness_session_polluted")).toBe(true);
  });

  test("binds scout claude cards to the live transcript instead of spawning broker lanes", () => {
    const mkAgent = (suffix: string) => {
      const agent = stubAgent(`relay-card-${suffix}`);
      agent.harness = "claude";
      agent.project = "openscout";
      agent.projectRoot = "/Users/art/dev/openscout";
      agent.cwd = "/Users/art/dev/openscout";
      // Server resolves relay-* placeholders to the live Claude session id.
      agent.harnessSessionId = "claude-sess-live";
      agent.harnessLogPath = "/tmp/claude/live.jsonl";
      return agent;
    };

    const { lanes, issues } = buildAgentLanes({
      scoutAgents: [mkAgent("a"), mkAgent("b"), mkAgent("c")],
      transcripts: [{
        source: "claude",
        transcriptPath: "/tmp/claude/live.jsonl",
        sessionId: "claude-sess-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 10_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent("claude-sess-live", NOW - 8_000, "assistant", { source: "claude" })],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(mkAgent("a").id);
    expect(issues.length).toBeGreaterThan(0);
  });

  test("does not add broker lanes for transport-only flights without a matching transcript", () => {
    const agent = stubAgent("relay-flight");
    agent.harness = "claude";
    agent.harnessSessionId = "relay-openscout-card-flight-claude";
    agent.state = "in_flight";
    agent.updatedAt = NOW;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/flight.jsonl",
          sessionId: agent.harnessSessionId!,
          updatedAt: NOW,
          data: {
            events: [{
              id: "evt-flight",
              t: 8,
              kind: "tool",
              text: "Read file",
              tool: "Read",
            }],
            files: [],
            live: true,
            metadata: { session: { sessionStart: NOW - 8_000 } },
          },
        },
      },
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("prefers scout lane over native lane for the same claude session", () => {
    const agent = stubAgent("openscout-claude-card");
    agent.harness = "claude";
    agent.harnessSessionId = "claude-sess-shared";

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [{
        source: "claude",
        transcriptPath: "/tmp/claude/shared.jsonl",
        sessionId: "claude-sess-shared",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 10_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent("claude-sess-shared", NOW - 8_000, "assistant", { source: "claude" })],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });

  test("excludes idle codex app-server sessions with warmup-only observe traces", () => {
    const agent = stubAgent("Atelier");
    agent.harness = "codex";
    agent.transport = "codex_app_server";
    agent.state = "available";
    agent.harnessSessionId = "019ee108-5864-70e2-8de6-ffe81b21e8be";
    agent.project = "Atelier";
    agent.updatedAt = NOW - 30_000;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/warmup.jsonl",
          sessionId: agent.harnessSessionId,
          data: {
            events: [{
              id: "boot",
              t: 0,
              kind: "boot",
              text: "Session started · gpt-5.5",
              detail: "workspace: /Users/art/dev/atelier · turns: 0 · status: idle",
            }],
            files: [],
            live: true,
            metadata: { session: { sessionStart: NOW - 30_000 } },
          },
          updatedAt: NOW,
        },
      },
      now: NOW,
      horizon: "30m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("admits Scoutbot from broker-native activity without a provider transcript", () => {
    const agent = stubAgent("Scout");
    agent.id = "scoutbot";
    agent.definitionId = "scoutbot";
    agent.handle = "scoutbot";
    agent.agentClass = "operator";
    agent.role = "operator-assistant";
    agent.harness = "codex";
    agent.transport = "codex_app_server";
    agent.state = "available";
    agent.harnessSessionId = null;
    agent.brokerActivity = [{
      id: "msg-scoutbot",
      kind: "message",
      at: NOW - 12_000,
      state: null,
      summary: "I dispatched the review to Hudson.",
      conversationId: "dm.operator.scoutbot",
    }];

    const { lanes, issues } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.agent.id).toBe("scoutbot");
    expect(lanes[0]?.observe?.metadata?.session?.source).toBe("broker-native");
    expect(lanes[0]?.observe?.events[0]).toMatchObject({
      kind: "message",
      text: "I dispatched the review to Hudson.",
    });
    expect(issues.some((issue) => issue.kind === "harness_session_unbound")).toBe(false);
  });

  test("admits recent pi rpc codex sessions before transcript activity arrives", () => {
    const agent = stubAgent("lattices");
    agent.harness = "codex";
    agent.transport = "pi_rpc";
    agent.state = "idle";
    agent.harnessSessionId = "lattices-pi-codex";
    agent.project = "lattices";
    agent.cwd = "/Users/art/dev/lattices";
    agent.updatedAt = NOW - 6_000;

    const { lanes, issues } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
    expect(lanes[0]?.observe?.events[0]?.text).toBe("Codex session ready");
    expect(issues.some((issue) => issue.kind === "harness_session_unbound")).toBe(false);
  });

  test("admits registered terminal harness sessions before transcript activity arrives", () => {
    const terminalSession: TerminalSessionRecord = {
      id: "ts.codex-live",
      harness: "codex",
      sourceSessionId: "codex-native-session",
      cwd: "/Users/art/dev/lattices",
      resumeCommand: "codex resume codex-native-session",
      surfaces: [{
        backend: "tmux",
        sessionName: "lattices-codex",
        paneId: "%1",
        attachCommand: ["tmux", "attach", "-t", "lattices-codex"],
        observeCommand: null,
        relay: {
          backend: "tmux",
          sessionName: "lattices-codex",
          tmuxSession: "lattices-codex",
        },
        state: "live",
      }],
      createdAt: NOW - 7_000,
      updatedAt: NOW - 5_000,
      metadata: { source: "scout-cli", updatedBy: "session_intake" },
    };

    const { lanes } = buildAgentLanes({
      scoutAgents: [],
      transcripts: [],
      terminalSessions: [terminalSession],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("codex");
    expect(lanes[0]?.agent.harnessSessionId).toBe("codex-native-session");
    expect(lanes[0]?.agent.terminalSurface?.sessionName).toBe("lattices-codex");
    expect(lanes[0]?.observe?.events[0]?.text).toBe("Codex session ready");
  });

  test("ignores backend-only discovered terminal sessions in lanes", () => {
    const terminalSession: TerminalSessionRecord = {
      id: "discovered.tmux.1",
      harness: "tmux",
      sourceSessionId: "random-shell",
      cwd: "",
      resumeCommand: "tmux attach -t random-shell",
      surfaces: [{
        backend: "tmux",
        sessionName: "random-shell",
        paneId: null,
        attachCommand: ["tmux", "attach", "-t", "random-shell"],
        observeCommand: null,
        relay: {
          backend: "tmux",
          sessionName: "random-shell",
          tmuxSession: "random-shell",
        },
        state: "live",
      }],
      createdAt: NOW,
      updatedAt: NOW,
      metadata: { registryState: "discovered" },
    };

    const { lanes } = buildAgentLanes({
      scoutAgents: [],
      transcripts: [],
      terminalSessions: [terminalSession],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("still admits designed scout cards without a tail transcript", () => {
    const agent = stubAgent("openscout-card");
    agent.harness = "codex";
    agent.harnessSessionId = "sess-designed-live";
    agent.state = "callable";
    agent.updatedAt = NOW;

    const { lanes } = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [],
      tailEvents: [],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/card.jsonl",
          sessionId: agent.harnessSessionId!,
          updatedAt: NOW,
          data: {
            events: [{
              id: "evt-designed",
              t: 8,
              kind: "tool",
              text: "grep pattern",
              tool: "grep",
            }],
            files: [],
            live: true,
            metadata: { session: { sessionStart: NOW - 8_000 } },
          },
        },
      },
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });
});

describe("roster issues", () => {
  test("does not flag terminal-surface agents as harness session unbound", () => {
    const agent = stubAgent("02.agentic-code");
    agent.transport = "tmux";
    agent.terminalSurface = {
      backend: "tmux",
      sessionName: "relay-02-agentic-code",
      paneId: "%0",
      socketDir: null,
    };

    expect(expectsProviderHarnessSession(agent)).toBe(false);

    const { issues } = buildAgentLanes({
      transcripts: [],
      tailEvents: [],
      scoutAgents: [agent],
      now: NOW,
    });

    expect(issues.some((issue) => issue.kind === "harness_session_unbound")).toBe(false);
  });

  test("does not flag configured roster cards without transport as harness session unbound", () => {
    const agent = stubAgent("Action");
    agent.transport = null;
    agent.harness = null;
    agent.state = "available";

    expect(isLaneRosterFleetAgent(agent)).toBe(false);
    expect(expectsProviderHarnessSession(agent)).toBe(false);

    const { issues } = buildAgentLanes({
      transcripts: [],
      tailEvents: [],
      scoutAgents: [agent],
      now: NOW,
    });

    expect(issues.some((issue) => issue.kind === "harness_session_unbound")).toBe(false);
  });

  test("does not flag idle codex app-server sessions waiting for the next thread", () => {
    const agent = stubAgent("Openscout 185");
    agent.transport = "codex_app_server";
    agent.harness = "codex";
    agent.state = "available";

    expect(expectsProviderHarnessSession(agent)).toBe(false);
    expect(isIdleCodexRelay(agent)).toBe(true);
    expect(shouldPollAgentForLaneObserve(agent, NOW, "30m")).toBe(false);
  });

  test("flags in-flight provider transports missing a harness session", () => {
    const agent = stubAgent("Scout");
    agent.transport = "codex_app_server";
    agent.harness = "codex";
    agent.state = "in_flight";

    expect(expectsProviderHarnessSession(agent)).toBe(true);

    const { issues } = buildAgentLanes({
      transcripts: [],
      tailEvents: [],
      scoutAgents: [agent],
      now: NOW,
    });

    expect(issues.some((issue) => issue.kind === "harness_session_unbound")).toBe(true);
  });

  test("ignores benign cursor monitor path collisions from tail discovery", () => {
    const issues = rosterIssuesFromTailDiscovery({
      issues: [
        {
          kind: "transcript_path_collision",
          sessionKey: "cursor:49cda248-f33b-4316-91b9-0a4362182de2",
          message: "Session cursor:49cda248 maps to multiple transcript files; tail is watching a.log.",
          transcriptPaths: ["/tmp/a.log", "/tmp/b.log"],
        },
        {
          kind: "transcript_path_collision",
          sessionKey: "claude:fc59aeae-973b-4ec4-90a7-095fddbeb140",
          message: "Session claude:fc59aeae maps to multiple transcript files; tail is watching a.jsonl.",
          transcriptPaths: ["/tmp/a.jsonl", "/tmp/b.jsonl"],
        },
      ],
    });

    expect(issues).toHaveLength(1);
    expect(issues[0]?.kind).toBe("transcript_path_collision");
    expect(issues[0]?.sessionRef).toBe("claude:fc59aeae-973b-4ec4-90a7-095fddbeb140");
  });

  test("does not treat rotating cursor monitor logs as duplicate transcript sessions", () => {
    const sharedSessionId = "cursor-4b4e2a4d-713b-6356-9b9f-3a5b2a2e2a2e";
    const transcripts = [
      {
        source: "cursor" as const,
        transcriptPath: "/Users/art/Library/Application Support/Cursor/process-monitor/1783270000.log",
        sessionId: sharedSessionId,
        cwd: null,
        project: "openscout",
        harness: "unattributed" as const,
        mtimeMs: NOW - 60_000,
        size: 100,
      },
      {
        source: "cursor" as const,
        transcriptPath: "/Users/art/Library/Application Support/Cursor/process-monitor/1783271000.log",
        sessionId: sharedSessionId,
        cwd: null,
        project: "openscout",
        harness: "unattributed" as const,
        mtimeMs: NOW - 30_000,
        size: 120,
      },
    ];

    const { issues } = buildAgentLanes({
      transcripts,
      tailEvents: [],
      scoutAgents: [],
      now: NOW,
    });

    expect(issues.some((issue) => issue.kind === "duplicate_transcript_session")).toBe(false);
  });
});

function stubTailEvent(
  sessionId: string,
  ts: number,
  kind: "tool" | "assistant" | "user" | "tool-result" | "system",
  overrides: Partial<import("../../lib/types.ts").TailEvent> = {},
): import("../../lib/types.ts").TailEvent {
  return {
    id: `evt:${sessionId}:${ts}`,
    ts,
    source: "codex",
    sessionId,
    pid: 1,
    parentPid: null,
    project: "openscout",
    cwd: "/Users/art/dev/openscout",
    harness: "unattributed",
    kind,
    summary: "grep foo",
    ...overrides,
  };
}

function stubAgent(name: string): Agent {
  return {
    id: `agent:${name}`,
    definitionId: name,
    name,
    handle: null,
    agentClass: "managed",
    harness: "codex",
    state: "callable",
    projectRoot: null,
    cwd: null,
    updatedAt: NOW,
    createdAt: null,
    transport: null,
    selector: null,
    defaultSelector: null,
    nodeQualifier: null,
    workspaceQualifier: null,
    wakePolicy: null,
    capabilities: [],
    project: null,
    branch: null,
    role: null,
    model: null,
    harnessSessionId: null,
    harnessLogPath: null,
    terminalSurface: null,
    conversationId: `${name}-conv`,
    homeNodeId: null,
    homeNodeName: null,
    ownerId: null,
    ownerName: null,
    ownerHandle: null,
    staleLocalRegistration: false,
    retiredFromFleet: false,
    replacedByAgentId: null,
  };
}
