import { useWorldMessages } from "./use-world-messages.ts";
import { clampFloorPan, wheelZoomFactor, worldDetailFade, zoomAboutPoint, ZOOM_STEP } from "./floor-minimap.ts";
import { WorldMinimap } from "./WorldMinimap.tsx";
import { WorldSky, type SkyBeacon } from "./WorldSky.tsx";
import { WorldActorTalk } from "./WorldActorTalk.tsx";
import { FloorExchangePanel } from "./FloorExchangePanel.tsx";
import { floorExchanges } from "./floor-exchanges.ts";
import { CAST_MEMBERS, matchCastSlug } from "../../lib/crew-registry.ts";
import { CharacterFamilyPreview } from "./CharacterFamilyPreview.tsx";
import { workerCharacters } from "./worker-characters.ts";
import { floorPreviewText } from "./floor-preview-text.ts";
import { FloorMessagePasses } from "./FloorMessagePasses.tsx";
import { floorCharacterName } from "./floor-character-name.ts";
import { WorkRunView } from "./WorkRunView.tsx";
import { buildSharedFloorLayout, type SharedFloorLayoutMemory } from "./shared-floor-layout.ts";
import { floorRelations } from "./floor-memory.ts";
import { buildLaneSessionStats } from "./agent-lane-detail.ts";
import { floorContextEvents } from "./floor-context-model.ts";
import { floorActorState } from "./agent-floor-actor.ts";
import { timeAgo } from "../../lib/time.ts";
import { buildSharedWorkArtifacts } from "./shared-work-artifacts.ts";
import { useScout } from "../../scout/Provider.tsx";
import { FileCode2 } from "lucide-react";
import { SharedFloorCharacter } from "./SharedFloorCharacter.tsx";
import { projectFloorPoint, unprojectFloorPoint, type MapProjection } from "./shared-floor-camera.ts";
import { lazy, Suspense, useEffect, useMemo, useRef, useState } from "react";
const SageModelStudio = lazy(() => import("./SageModelStudio.tsx"));
import { isAutoGeneratedLaneAgentName, lanePrimaryLabel, type AgentLane } from "./agent-lanes-model.ts";
import outpostsUrl from "./assets/world-outposts-v1.png?url";
import starPointsUrl from "./assets/solar-system-scope-2k-stars-points.png?url";
import "./shared-work-floor.css";

/** Distance as a ratio, because "0.0004x" reads as noise and "1:2,500" reads as far. */
function formatZoom(zoom: number) {
  if (zoom >= 1) return `${Number(zoom.toFixed(zoom < 10 ? 1 : 0))}:1`;
  return `1:${Math.round(1 / zoom).toLocaleString()}`;
}

function islandArt(key: string) {
  let hash = 0;
  for (const char of key) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return {
    outpostPosition: `${(hash % 3) * 50}% center`,
    skyPosition: `${hash % 100}% ${18 + (hash % 58)}%`,
  };
}

export function SharedWorkFloor({ lanes, now, onActor }: { lanes: AgentLane[]; now: number; onActor: (lane: AgentLane) => void }) {
  const { openFilePreview } = useScout();
  const brokerMessages = useWorldMessages();
  const [talkTarget, setTalkTarget] = useState<string | null>(null);
  const [actorMenu, setActorMenu] = useState<{ lane: AgentLane; x: number; y: number; compose: boolean; voice?: boolean } | null>(null);
  const [workRun, setWorkRun] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  /**
   * Actors whose context bubble is held open. Hover shows one at a time and
   * loses it the moment you move the mouse, which makes comparing two agents
   * impossible — you cannot read the second without giving up the first. A
   * click pins, a second click on the same actor releases, and pins accumulate,
   * so a handful of the people on the floor can be watched side by side. Order
   * is pin order, which is also their stacking order when bubbles overlap.
   */
  const [pinnedActors, setPinnedActors] = useState<string[]>([]);
  const [exchangePair, setExchangePair] = useState<[string,string] | null>(null);
  const [speakingActor, setSpeakingActor] = useState<string | null>(null);
  const [playful, setPlayful] = useState(false);
  const [riggedCharacters, setRiggedCharacters] = useState(true);
  const [castStyle, setCastStyle] = useState<"crew" | "chip" | "prototype">("crew");
  const castAssignments = useRef<Record<string, string>>({});
  for (const lane of [...lanes].sort((a,b) => a.id.localeCompare(b.id))) {
    if (!castAssignments.current[lane.id]) {
      const used = Object.values(castAssignments.current);
      castAssignments.current[lane.id] = matchCastSlug(lane.agent.name) ?? CAST_MEMBERS.find(member => !used.includes(member.slug))?.slug ?? CAST_MEMBERS[used.length % CAST_MEMBERS.length]!.slug;
    }
  }
  const [familyPreview, setFamilyPreview] = useState(false);
  const [modelStudio, setModelStudio] = useState(false);
  const [renderedPrototype, setRenderedPrototype] = useState(true);
  // Reserve each character once; roster updates never duplicate or reassign a friend.
  const characterOwners = useRef<string[]>([]);
  for (const lane of lanes) {
    if (characterOwners.current.length >= workerCharacters.length) break;
    if (!characterOwners.current.includes(lane.id)) characterOwners.current.push(lane.id);
  }
  const [furniture, setFurniture] = useState(false);
  const [boundaries, setBoundaries] = useState(false);
  const [teamsOpen, setTeamsOpen] = useState(false);
  const [layersOpen, setLayersOpen] = useState(false);
  const [paused, setPaused] = useState(false);
  const viewport = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState({ width: 900, height: 500 });
  const [workspaceKey, setWorkspaceKey] = useState<string | null>(null);
  const [projection, setProjection] = useState<MapProjection>("flat");
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [actorOffsets, setActorOffsets] = useState<Record<string, { x: number; y: number }>>({});
  const [draggingActor, setDraggingActor] = useState<string | null>(null);
  const actorDrag = useRef<{ id: string; sx: number; sy: number; x: number; y: number; baseX: number; baseY: number; moved: boolean } | null>(null);
  const suppressActorClick = useRef(false);
  const drag = useRef<{ x: number; y: number; px: number; py: number } | null>(null);
  useEffect(() => {
    if (!viewport.current) return;
    const observer = new ResizeObserver(([entry]) => setSize({ width: entry.contentRect.width, height: entry.contentRect.height }));
    observer.observe(viewport.current); return () => observer.disconnect();
  }, [workRun]);
  const layoutMemory = useRef<SharedFloorLayoutMemory | undefined>(undefined);
  const spatial = useMemo(() => buildSharedFloorLayout(lanes, layoutMemory.current), [lanes]);
  useEffect(() => { layoutMemory.current = spatial.memory; }, [spatial]);
  const groups = new Map(spatial.groups.map((group) => [group.key, group]));
  const entries = [...groups];
  const layout = groups;
  const selectedLane = lanes.find((lane) => lane.id === selectedId) ?? null;
  const selectedArtifacts = selectedLane ? buildSharedWorkArtifacts(lanes).filter((artifact) => artifact.owners.some((owner) => owner.id === selectedLane.id)) : [];
  const connections = new Map<string, { lane: AgentLane; reason: string }>();
  for (const artifact of selectedArtifacts) for (const owner of artifact.owners) {
    if (owner.id !== selectedId) connections.set(owner.id, { lane: owner, reason: "Shared file activity" });
  }
  const familyEdges = floorRelations(lanes);
  const parents = [...new Map(familyEdges.map(({ parent }) => [parent.id, parent])).values()];
  const actorName = (lane: AgentLane) => floorCharacterName(lane).label;
  for (const edge of familyEdges) {
    if (edge.child.id === selectedId) connections.set(edge.parent.id, { lane: edge.parent, reason: "Parent session" });
    if (edge.parent.id === selectedId) connections.set(edge.child.id, { lane: edge.child, reason: "Child session" });
  }
  const connected = new Set(connections.keys());
  if (exchangePair) exchangePair.forEach(id=>connected.add(id));
  const exchanges = floorExchanges(lanes, now, brokerMessages);
  const exchangePairs = new Map<string,[string,string]>();
  for (const e of exchanges) exchangePairs.set([e.from,e.to].sort().join(":"), [e.from,e.to]);
  for (const { parent, child } of familyEdges) {
    const key = [parent.id, child.id].sort().join(":");
    if (!exchangePairs.has(key)) exchangePairs.set(key, [parent.id, child.id]);
  }
  const pairStillExists = !!exchangePair && [...exchangePairs.values()].some(pair => pair.every(id => exchangePair.includes(id)));
  useEffect(() => { if (exchangePair && !pairStillExists) setExchangePair(null); }, [pairStillExists, exchangePair]);
  const openExchange = (pair:[string,string]) => { setSelectedId(null); setExchangePair(pair); };
  const positions = new Map(spatial.groups.flatMap((group) => group.actors.map((actor) => [actor.lane.id, { x: actor.centerX + (actorOffsets[actor.lane.id]?.x ?? 0), y: actor.centerY + (actorOffsets[actor.lane.id]?.y ?? 0) }] as const)));
  const sourcePoint = selectedId ? positions.get(selectedId) : null;
  const recent = selectedLane ? floorContextEvents([selectedLane], now, ["tool", "message", "ask"]).slice(0, 3) : [];
  const selectedState = selectedLane ? floorActorState(selectedLane, now) : null;
  const worldWidth = spatial.worldWidth;
  const worldHeight = spatial.worldHeight;
  const projectedWidth = projection === "iso" ? Math.sqrt(3) / 2 * (worldWidth + worldHeight) : worldWidth;
  const projectedHeight = projection === "iso" ? (worldWidth + worldHeight) / 2 : worldHeight;
  const fit = Math.min((size.width - 36) / projectedWidth, (size.height - 70) / projectedHeight);
  const scale = Math.max(.12, fit) * zoom;
  // Mirrors the committed camera so a burst of wheel events inside one frame
  // compounds instead of all reading the same pre-batch state.
  const camera = useRef({ zoom, pan });
  camera.current = { zoom, pan };
  // The world's on-screen size at a given zoom, for keeping it in frame.
  const clampPan = (value: { x: number; y: number }, atZoom: number) => {
    const at = Math.max(.12, fit) * atZoom;
    return clampFloorPan(value, { width: projectedWidth * at, height: projectedHeight * at }, size);
  };
  const applyZoom = (factor: number, focus?: { x: number; y: number }) => {
    const next = zoomAboutPoint(camera.current.zoom, camera.current.pan, factor, focus);
    next.pan = clampPan(next.pan, next.zoom);
    camera.current = next;
    setZoom(next.zoom);
    setPan(next.pan);
  };
  // React delegates wheel listeners as passive. Own this listener so zoom can
  // consume the gesture without also scrolling an enclosing native/web pane.
  useEffect(() => {
    const node = viewport.current;
    if (!node) return;
    const wheel = (event: WheelEvent) => {
      if ((event.target as Element).closest(".shared-floor__inspect")) return;
      event.preventDefault();
      const box = node.getBoundingClientRect();
      applyZoom(wheelZoomFactor(event.deltaY, event.deltaMode), {
        x: event.clientX - box.left - box.width / 2,
        y: event.clientY - box.top - box.height / 2,
      });
    };
    node.addEventListener("wheel", wheel, { passive: false });
    return () => node.removeEventListener("wheel", wheel);
  });
  const detail = worldDetailFade(zoom);
  // Where each workspace lands on screen, for the sky to draw once the floor
  // itself is too far away to read. Mirrors the benches transform exactly:
  // translate(pan) · scale · project, about the centre of the world.
  const beacons = useMemo<SkyBeacon[]>(() => spatial.groups.map((group) => {
    const point = projectFloorPoint(
      group.x + group.width / 2 - worldWidth / 2,
      group.y + group.height / 2 - worldHeight / 2,
      projection,
    );
    return { x: point.x * scale + pan.x, y: point.y * scale + pan.y, spread: group.width * scale };
  }), [spatial.groups, projection, scale, pan, worldWidth, worldHeight]);
  const focusActor = (actor: AgentLane) => {
    setExchangePair(null); setSelectedId(actor.id);
    onActor(actor);
  };
  /** Clicking a person on the floor both inspects them and holds their bubble. */
  const engageActor = (actor: AgentLane) => {
    setPinnedActors((pinned) => pinned.includes(actor.id) ? pinned.filter((id) => id !== actor.id) : [...pinned, actor.id]);
    focusActor(actor);
  };
  // An actor can leave the roster while pinned; the pin goes with them.
  useEffect(() => {
    setPinnedActors((pinned) => {
      const live = pinned.filter((id) => lanes.some((lane) => lane.id === id));
      return live.length === pinned.length ? pinned : live;
    });
  }, [lanes]);
  useEffect(() => {
    if (!selectedId && !exchangePair && pinnedActors.length === 0) return;
    const clear = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelectedId(null); setExchangePair(null); setPinnedActors([]); } };
    window.addEventListener("keydown", clear);
    return () => window.removeEventListener("keydown", clear);
  }, [selectedId, exchangePair, pinnedActors.length]);
  return workRun ? <div className="shared-floor shared-floor__experiment"><button className="shared-floor__back" type="button" onClick={() => setWorkRun(false)}>← Back to world</button><WorkRunView lanes={lanes} now={now} onActor={onActor} /></div> : <div className={`shared-floor is-map is-${projection}${selectedLane || exchangePair ? " has-selection" : ""}${boundaries ? " has-boundaries" : ""}${paused ? " is-paused" : ""}`}>
    {actorMenu ? <WorldActorTalk key={actorMenu.lane.id} {...actorMenu} onSent={() => { setTalkTarget(actorMenu.lane.id); setSelectedId(actorMenu.lane.id); }} onTalk={() => setActorMenu({ ...actorMenu, compose: true, voice: false })} onDictate={() => setActorMenu({ ...actorMenu, compose: true, voice: true })} onProfile={() => { focusActor(actorMenu.lane); setActorMenu(null); }} onClose={() => setActorMenu(null)} /> : null}
    {modelStudio ? <Suspense fallback={<div role="status">Loading 3D studio…</div>}><SageModelStudio onClose={() => setModelStudio(false)} /></Suspense> : null}
    {exchangePair ? <FloorExchangePanel key={exchangePair.join(":")} pair={exchangePair} lanes={lanes} now={now} onClose={()=>setExchangePair(null)} onFile={openFilePreview} onSpeaker={setSpeakingActor} /> : null}
    {familyPreview ? <CharacterFamilyPreview onClose={() => setFamilyPreview(false)} /> : null}
    <div className="shared-floor__teams"><button type="button" aria-expanded={teamsOpen} onClick={() => setTeamsOpen(!teamsOpen)}>Agent teams{familyEdges.length ? ` · ${familyEdges.length}` : ""}</button>{teamsOpen ? <section aria-label="Agent families"><strong>Parent → subagents</strong>{parents.length ? parents.map((parent) => <div key={parent.id}><button type="button" onClick={() => focusActor(parent)}>{actorName(parent)}</button>{familyEdges.filter((edge) => edge.parent.id === parent.id).map(({ child }) => <button className="shared-floor__team-child" type="button" key={child.id} onClick={() => focusActor(child)}>↳ {actorName(child)}<small>{floorActorState(child, now).label}</small></button>)}</div>) : <p>No parent links reported in this roster yet.</p>}</section> : null}</div>
    <div className="shared-floor__layers"><button type="button" aria-expanded={layersOpen} onClick={() => setLayersOpen(!layersOpen)}>Layers</button>{layersOpen ? <div><label><input type="checkbox" aria-label="Work surfaces" checked={furniture} onChange={(event) => setFurniture(event.target.checked)} />Work surfaces</label><label><input type="checkbox" aria-label="Boundaries" checked={boundaries} onChange={(event) => setBoundaries(event.target.checked)} />Boundaries</label><label><input type="checkbox" aria-label="Playful motion" checked={playful} onChange={(event) => setPlayful(event.target.checked)} />Playful motion</label><label>Characters<select aria-label="Map character style" value={castStyle} onChange={event => setCastStyle(event.target.value as typeof castStyle)}><option value="crew">Crew</option><option value="chip">Pixel Chip</option><option value="prototype">Prototype rigs</option></select></label>{castStyle === "prototype" ? <label><input type="checkbox" aria-label="Character rig" checked={riggedCharacters} onChange={(event) => setRiggedCharacters(event.target.checked)} />Character rig</label> : null}<button type="button" onClick={() => { setFamilyPreview(true); setLayersOpen(false); }}>Preview character family →</button><button type="button" onClick={() => { setModelStudio(true); setLayersOpen(false); }}>3D character studio →</button>{castStyle === "prototype" ? <label><input type="checkbox" aria-label="Rendered characters" checked={renderedPrototype} onChange={(event) => setRenderedPrototype(event.target.checked)} />Rendered characters</label> : null}<button type="button" className="shared-floor__run-link" onClick={() => { setLayersOpen(false); setWorkRun(true); }}>Try Work run →</button></div> : null}</div>
    <div className="shared-floor__camera" aria-label="Map camera">
      <button type="button" aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? "Resume" : "Pause"}</button><div role="group" aria-label="Map projection">{(["flat", "iso"] as const).map((mode) => <button type="button" key={mode} aria-pressed={projection === mode} onClick={() => setProjection(mode)}>{mode === "iso" ? "Iso" : "Flat"}</button>)}</div>
      <button type="button" aria-label="Zoom shared map out" onClick={() => applyZoom(1 / ZOOM_STEP)}>−</button><button type="button" onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>Fit</button><button type="button" aria-label="Zoom shared map in" onClick={() => applyZoom(ZOOM_STEP)}>+</button><output className="shared-floor__zoom-readout" aria-label={`Zoom ${formatZoom(zoom)}`}>{formatZoom(zoom)}</output>
    </div>
    <WorldMinimap width={worldWidth} height={worldHeight} projection={projection} size={size} scale={scale} zoom={zoom} pan={pan} onPan={(next) => setPan(clampPan(next, zoom))} onZoom={setZoom} workspaces={[...groups].map(([id,g])=>({id,label:`Locate workspace ${g.cwd || "unknown"}, ${g.lanes.length} actors`,x:g.x+g.width/2,y:g.y+g.height/2}))} />
    {workspaceKey && groups.has(workspaceKey) ? <aside className="shared-floor__workspace-panel" aria-label="Workspace details"><header><strong>{groups.get(workspaceKey)!.cwd.split("/").filter(Boolean).at(-1) || "Workspace"}</strong><button type="button" aria-label="Close workspace details" onClick={() => setWorkspaceKey(null)}>×</button></header><p>{groups.get(workspaceKey)!.cwd}</p><h4>Reported branches</h4><small>{[...new Set(groups.get(workspaceKey)!.lanes.map(lane => lane.facts?.branch || buildLaneSessionStats(lane).branch).filter(Boolean))].join(" · ") || "Branch not reported"}</small><h4>Actors in this workspace</h4>{groups.get(workspaceKey)!.lanes.map(lane => <button className="shared-floor__workspace-actor" type="button" key={lane.id} onClick={() => focusActor(lane)}><span className="shared-floor__workspace-actor-heading"><strong>{actorName(lane)}</strong><small>{floorActorState(lane, now).label}</small></span><span className="shared-floor__workspace-runtime">{[lane.agent.harness, lane.facts?.model || buildLaneSessionStats(lane).model].filter(Boolean).join(" · ") || "Runtime not reported"}</span><span className="shared-floor__workspace-task">{floorPreviewText(lane.facts?.currentTask) || "No task reported"}</span><span className="shared-floor__workspace-runtime">{lane.facts?.branch || buildLaneSessionStats(lane).branch || "Branch not reported"} · {lane.id.slice(-5)}</span></button>)}</aside> : null}
    <div className="shared-floor__viewport" ref={viewport}
      onPointerDown={(event) => { if (event.button !== 0 || (event.target as Element).closest("button")) return; drag.current = { x: event.clientX, y: event.clientY, px: pan.x, py: pan.y }; event.currentTarget.setPointerCapture(event.pointerId); }}
      onPointerMove={(event) => { if (drag.current) setPan(clampPan({ x: drag.current.px + event.clientX - drag.current.x, y: drag.current.py + event.clientY - drag.current.y }, zoom)); }}
      onPointerUp={(event) => { if (drag.current && Math.hypot(event.clientX - drag.current.x, event.clientY - drag.current.y) < 4) { setSelectedId(null); setExchangePair(null); } drag.current = null; }} onPointerCancel={() => { drag.current = null; }}>
    <WorldSky zoom={zoom} pan={pan} beacons={beacons} beaconStrength={detail.beacons} />
    <div className="shared-floor__benches" style={{ opacity: detail.world, visibility: detail.world > 0 ? undefined : "hidden", width: worldWidth, height: worldHeight, transform: `translate(${pan.x}px, ${pan.y}px) scale(${scale})${projection === "iso" ? " matrix(0.8660254, 0.5, -0.8660254, 0.5, 0, 0)" : ""}`, marginLeft: -worldWidth / 2, marginTop: -worldHeight / 2 }}>


    <svg className="floor-exchange-links" width={worldWidth} height={worldHeight} aria-label="Agent exchange links">{[...exchangePairs].map(([key,pair])=> {
      const a=positions.get(pair[0]), b=positions.get(pair[1]); if(!a || !b) return null;
      const title=pair.map(id=>{const lane=lanes.find(l=>l.id===id); return lane ? actorName(lane) : "Actor";}).join(" and ");
      const hasMessages = exchanges.some(e => pair.includes(e.from) && pair.includes(e.to));
      const path=`M ${a.x} ${a.y} Q ${(a.x+b.x)/2} ${Math.min(a.y,b.y)-30} ${b.x} ${b.y}`;
      return <g key={key} role="button" tabIndex={0} aria-label={`${hasMessages ? "Open exchanges" : "Inspect relationship"} between ${title}`} className={`${hasMessages ? "is-exchange" : "is-family"}${exchangePair?.includes(pair[0]) && exchangePair.includes(pair[1]) ? " is-active" : ""}`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();openExchange(pair);}} onKeyDown={e=>{if(e.key==="Enter" || e.key===" "){e.preventDefault();openExchange(pair);}}}><title>{hasMessages ? "Recent exchanges" : "Parent relationship"} · {title}</title><path className="exchange-line" d={path}/><path className="exchange-hit" d={path}/></g>;
    })}</svg>
    <FloorMessagePasses broker={brokerMessages} lanes={lanes} now={now} positions={positions} paused={paused} />
    {sourcePoint ? <svg className="shared-floor__connections" width={worldWidth} height={worldHeight} aria-hidden="true">{[...connections].map(([id, connection]) => { const target = positions.get(id); return target ? <path key={id} className={connection.reason === "Shared file activity" ? "is-shared" : "is-lineage"} d={`M ${sourcePoint.x} ${sourcePoint.y} Q ${(sourcePoint.x + target.x) / 2} ${Math.min(sourcePoint.y, target.y) - 35} ${target.x} ${target.y}`} /> : null; })}</svg> : null}
    {[...groups].map(([key, group]) => {
      const art = islandArt(key);
      return <section className={`shared-floor__island${group.actors.length > 1 || furniture ? " has-place" : ""}${workspaceKey === key ? " is-open" : ""}`} key={key} aria-label={group.cwd || "Agent gathering"} style={{ left: layout.get(key)!.x, top: layout.get(key)!.y, height: layout.get(key)!.height, width: layout.get(key)!.width }}>
      <div className="shared-floor__place-presentation">
      <div className="shared-floor__sky" aria-hidden="true" style={{ backgroundImage: `url(${starPointsUrl})`, backgroundPosition: art.skyPosition }} />
      <div className="shared-floor__outpost" aria-hidden="true" style={{ backgroundImage: `url(${outpostsUrl})`, backgroundPosition: art.outpostPosition }} />
      <span className="shared-floor__label-anchor" aria-hidden="true" />
      <button type="button" className="shared-floor__gathering-label" aria-expanded={workspaceKey === key} onPointerDown={event => event.stopPropagation()} onClick={() => setWorkspaceKey(workspaceKey === key ? null : key)}><strong>{group.cwd === "~" ? "Home" : group.cwd.split("/").filter(Boolean).at(-1) || "Unassigned"}</strong><small>{group.cwd || "Workspace not reported"}</small></button>
      </div>
      {furniture ? <div className="shared-floor__optional-table"><span>{group.cwd.split("/").filter(Boolean).at(-1) || "Workspace"}</span><div>{buildSharedWorkArtifacts(group.lanes).slice(0, 4).map((artifact) => <button type="button" key={artifact.id} title={artifact.path} aria-label={`Preview ${artifact.path}`} disabled={!artifact.resolvedPath} onClick={() => artifact.resolvedPath && openFilePreview(artifact.resolvedPath)}><FileCode2 size={25} /><small>{artifact.path.split("/").at(-1)}</small></button>)}</div></div> : null}
      <div className="shared-floor__crew">{group.actors.map(({ lane, x, y }) => <div className={`shared-floor__wanderer${selectedId === lane.id ? " is-selected" : ""}${pinnedActors.includes(lane.id) ? " is-pinned" : ""}${connected.has(lane.id) ? " is-connected" : ""}${speakingActor === lane.id ? " is-speaking" : ""}`} key={lane.id} style={{ left: x + (actorOffsets[lane.id]?.x ?? 0), top: y + (actorOffsets[lane.id]?.y ?? 0), zIndex: draggingActor === lane.id ? 10 : pinnedActors.includes(lane.id) ? 7 + pinnedActors.indexOf(lane.id) : undefined }}
        data-dragging={draggingActor === lane.id || undefined}
        onPointerDown={(event) => {
          if (event.button !== 0) return;
          if (event.shiftKey || event.altKey || event.metaKey || event.ctrlKey) { event.stopPropagation(); suppressActorClick.current = true; const bounds = event.currentTarget.getBoundingClientRect(); setActorMenu({ lane, x: bounds.left + bounds.width / 2, y: bounds.bottom + 32, compose: true, voice: event.shiftKey }); return; }
          event.stopPropagation();
          suppressActorClick.current = false;
          const offset = actorOffsets[lane.id] ?? { x: 0, y: 0 };
          actorDrag.current = { id: lane.id, sx: event.clientX, sy: event.clientY, ...offset, baseX: group.x + x, baseY: group.y + y, moved: false };
          event.currentTarget.setPointerCapture(event.pointerId);
        }}
        onPointerMove={(event) => {
          const active = actorDrag.current;
          if (!active || active.id !== lane.id) return;
          event.stopPropagation();
          const dx = event.clientX - active.sx, dy = event.clientY - active.sy;
          if (!active.moved && Math.hypot(dx, dy) < 5) return;
          active.moved = true;
          setDraggingActor(lane.id);
          const delta = unprojectFloorPoint(dx / scale, dy / scale, projection);
          setActorOffsets((current) => ({ ...current, [lane.id]: {
            x: Math.max(0, Math.min(worldWidth - 84, active.baseX + active.x + delta.x)) - active.baseX,
            y: Math.max(20, Math.min(worldHeight - 120, active.baseY + active.y + delta.y)) - active.baseY,
          } }));
        }}
        onPointerUp={(event) => {
          if (actorDrag.current?.id !== lane.id) return;
          event.stopPropagation();
          if (!actorDrag.current.moved) engageActor(lane);
          suppressActorClick.current = true;
          actorDrag.current = null;
          setDraggingActor(null);
          if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId);
        }}
        onContextMenu={(event) => {
          event.preventDefault();
          event.stopPropagation();
          const bounds = event.currentTarget.getBoundingClientRect();
          setActorMenu({ lane, x: bounds.left + bounds.width / 2, y: bounds.bottom + 32, compose: false });
        }}
        onPointerCancel={() => { actorDrag.current = null; suppressActorClick.current = true; setDraggingActor(null); }}
        onClickCapture={(event) => { if (suppressActorClick.current) { event.stopPropagation(); suppressActorClick.current = false; } }}
      >{talkTarget === lane.id ? <span className="shared-floor__talk-follow" title="Message accepted · following observed agent status">↗ You <span>{floorActorState(lane, now).label}</span></span> : null}<SharedFloorCharacter crewSlug={castStyle !== "prototype" ? castAssignments.current[lane.id] : undefined} pixelCrew={castStyle === "chip"} rigged={riggedCharacters} lane={lane} now={now} paused={paused || draggingActor === lane.id} playful={playful} character={renderedPrototype ? workerCharacters[characterOwners.current.indexOf(lane.id)] : undefined} displayName={isAutoGeneratedLaneAgentName(lane.agent) ? lane.agent.harness || "Agent" : undefined} pinned={pinnedActors.includes(lane.id)} onActor={engageActor} /></div>)}</div>
    </section>;
    })}
  </div></div>

  </div>;
}
