import { describe, expect, test } from "bun:test";

import { isHarnessWrapperTitle, logicalSessionTitle } from "./session-title.js";

describe("logical session titles", () => {
  test("keeps a short user request", () => {
    expect(logicalSessionTitle("Fix the sidebar sort")).toBe("Fix the sidebar sort");
  });

  test("strips Claude local-command caveats and keeps the real ask", () => {
    const dumped = [
      "<local-command-caveat>",
      "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your process unless they are directed at you.",
      "</local-command-caveat>",
      "<command-name>review-pr</command-name>",
      "Please review the auth PR",
    ].join("\n");
    expect(logicalSessionTitle(dumped)).toBe("Please review the auth PR");
    expect(isHarnessWrapperTitle(dumped)).toBe(true);
  });

  test("rejects a caveat-only dump in favor of the project fallback", () => {
    const dumped = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>";
    expect(logicalSessionTitle(dumped, "openscout")).toBe("openscout");
    expect(isHarnessWrapperTitle(dumped)).toBe(true);
  });

  test("rejects task-notification wrappers", () => {
    const dumped = "<task-notification>Scheduled task output</task-notification>";
    expect(logicalSessionTitle(dumped, "Claude session")).toBe("Claude session");
  });

  test("caps long titles", () => {
    const long = "A".repeat(90);
    const titled = logicalSessionTitle(long);
    expect(titled?.endsWith("…")).toBe(true);
    expect(titled?.length).toBe(72);
  });
});
