/**
 * Logical session titles for Scout lists.
 *
 * Harness first-turns are often XML wrappers (`<local-command-caveat>`,
 * `<task-notification>`) or Codex/Kimi/Grok generated names. Prefer a
 * harness-provided title when the caller has one; otherwise strip wrappers
 * and keep the first meaningful user line. LLM titling, when added, should
 * call `resolveScoutBaselineRuntime` rather than the operator's session model.
 */

const TITLE_MAX_CHARS = 72;

const WRAPPER_TAGS = [
  "local-command-caveat",
  "task-notification",
  "command-name",
  "command-message",
  "command-args",
  "local-command",
];

const BOILERPLATE = [
  /^caveat:\s*the messages below were generated by the user/iu,
  /^do not respond to these messages/iu,
  /^\[user\]$/iu,
];

function compact(value: string): string {
  return value.replace(/\s+/gu, " ").trim();
}

function stripWrapperTags(value: string): string {
  let next = value;
  for (const tag of WRAPPER_TAGS) {
    const block = new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`, "giu");
    const empty = new RegExp(`<${tag}\\b[^>]*\\/>`, "giu");
    next = next.replace(block, "\n").replace(empty, "\n");
  }
  next = next.replace(/<\/?[A-Za-z][\w:-]*\b[^>]*>/gu, "\n");
  return next;
}

function isBoilerplate(value: string): boolean {
  return BOILERPLATE.some((pattern) => pattern.test(value));
}

function looksLikeWrapperDump(value: string): boolean {
  const lowered = value.toLowerCase();
  return WRAPPER_TAGS.some((tag) => lowered.includes(`<${tag}`))
    || lowered.includes("caveat: the messages below were generated");
}

/** True when a stored title is a harness wrapper dump, not a session name. */
export function isHarnessWrapperTitle(value: string | null | undefined): boolean {
  const trimmed = value?.trim() ?? "";
  if (!trimmed) return true;
  return looksLikeWrapperDump(trimmed) || isBoilerplate(trimmed);
}

/**
 * Turn a first user turn or harness name into a list-safe title.
 * Returns null when nothing human remains — callers should use a project
 * or harness fallback.
 */
export function logicalSessionTitle(
  source: string | null | undefined,
  fallback?: string | null,
): string | null {
  const raw = source?.trim() ?? "";
  const lines = (raw ? stripWrapperTags(raw) : "")
    .split(/\n+/u)
    .map((line) => compact(line))
    .filter((line) => line.length > 0 && !isBoilerplate(line) && !looksLikeWrapperDump(line));
  const candidate = lines.find((line) => line.length >= 12) ?? lines[0] ?? "";
  if (!candidate) {
    const fallbackText = fallback?.trim() ?? "";
    return fallbackText ? compact(fallbackText).slice(0, TITLE_MAX_CHARS) : null;
  }
  if (candidate.length <= TITLE_MAX_CHARS) return candidate;
  return `${candidate.slice(0, TITLE_MAX_CHARS - 1).trimEnd()}…`;
}
