import {
  listScoutDeprecatedCommands,
  listScoutPrimaryCommands,
} from "./registry.ts";

export function renderScoutHelp(version = "0.2.19"): string {
  const commandLines = listScoutPrimaryCommands()
    .map((command) => `  ${command.name.padEnd(12, " ")} ${command.summary}`)
    .join("\n");
  const deprecatedLines = listScoutDeprecatedCommands()
    .map((command) => `  ${command.name.padEnd(12, " ")} ${command.summary}`)
    .join("\n");

  return [
    `scout ${version}`,
    "",
    "Usage:",
    "  scout [--json] <command> [options]",
    "  scout relay <command> [options]",
    "",
    "Commands:",
    commandLines,
    ...(deprecatedLines ? ["", "Deprecated aliases:", deprecatedLines] : []),
    "",
    "Global flags:",
    '  --json        Structured JSON (doctor: NDJSON stream; last object has phase "complete")',
    "",
    "Doctor flags:",
    "  --fix         Ask native scoutd to run conservative repairs when supported",
    "  --yes         Non-interactive confirmation for scout doctor --fix",
    "",
    "First run:",
    "  scout config set name \"Ada\"",
    "  scout config agent-names init",
    "  scout setup --source-root ~/dev --default-harness codex",
    "  scout doctor",
    "  scout doctor --fix --yes                       # conservative native repairs when scoutd supports them",
    "  scout runtimes",
    "  scout providers usage                         # live provider quota windows and reset times",
    "  scout providers map                           # quota-aware role/model/provider recommendations",
    "  scout attention                                # recent open loops and local diffs",
    "",
    "Fast path:",
    '  scout send --to hudson "branch pushed"         # FYI only; no reply or work expected',
    "  scout match new BLUEBIRD                        # open a 10-minute codename invitation",
    '  scout ask --to hudson "review the parser"      # reply, judgment, or work expected',
    '  scout ask --to hudson --notify "review it"     # async ask; Scout reports completion later',
    '  scout alias set review --to hudson              # short mutable route pointer',
    '  scout ask --harness codex "review this"        # current project; fresh compatible worker',
    '  scout ask --project ../talkie --harness claude "review the spec"',
    '  scout ask --project ../talkie "compare auth"   # no agent id needed; broker routes',
    "  scout ask --to hudson --prompt-file ./handoff.md",
    "  scout wait inv_123 --timeout 600               # follow an existing ask",
    "  scout search index --source sessions --harness kimi --hours 12  # explicit session warm-up",
    '  scout search query "xcodebuild" --harness kimi --hours 12       # past harness sessions',
    "  scout tail --source codex --kind tool-result   # observe harness activity",
    "  scout attention --since 2d                    # on-demand open loops report",
    "  scout label watch release:0.2.66 --interval 2  # label-scoped activity firehose",
    "",
    "Orientation (only when route or sender is unclear):",
    "  scout whoami",
    "  scout inbox --latest 10 --json",
    "  scout who",
    "  scout channel triage --latest 10 --json",
    "  scout latest",
    "  scout search status                            # past harness-session index coverage",
    "  scout providers usage                         # Claude, Codex, and every available quota window",
    "  scout attention",
    "  scout latest --channel triage --messages --limit 3",
    "  scout menu",
    "  scout tui",
    "  scout server open",
    "",
    "macOS app:",
    "  scout install         # download + install OpenScout.app from the latest signed release",
    "  scout install --check # compare the installed app against the latest release",
    "",
    "Lifecycle:",
    '  scout send --to hudson "branch pushed"         # FYI only; no lifecycle',
    "  scout match 7KQ3MW                              # join a facilitated two-session match",
    '  scout ask --to hudson "review the parser"      # owned work; wait for ack',
    '  scout ask --to hudson --notify "review it"     # return after receipt; notify on completion',
    "  scout wait inv_123 --timeout 600               # wait by invocation, flight, message, or ref",
    "  scout flight get flt_123                       # current ask state",
    "  scout flight wait flt_123 --timeout 60         # bounded wait for terminal state",
    "  scout search index --source sessions --days 3  # warm harness-session knowledge",
    '  scout search query "topic" --harness codex     # find prior session work (not broker chat)',
    "  scout tail --project openscout --query test     # observed harness firehose",
    "  scout label feed release:0.2.66 --since 10m    # normalized label backlog",
    "  scout label brief release:0.2.66               # compact label digest",
    "  scout card create                              # fresh reply-ready return address",
    '  scout broadcast "deploying in 15m"             # explicit shared broadcast',
    "",
    "Implicit ask shortcut:",
    "  scout @agent your request",
    "  scout @agent --prompt-file ./handoff.md",
    "  scout hey @agent can you review this?",
    "  scout @agent.harness:codex use the Codex-backed one",
    "  scout @agent#codex?5.5 use the Codex 5.5-backed one",
    "",
    "File-backed input:",
    "  ask uses --prompt-file for the primary work prompt",
    "  send/broadcast/speak use --message-file for the message body",
    "  --body-file is accepted as the shared alias",
    "",
    "One-to-one delegation:",
    '  scout ask --to hudson "review the parser"      # DM by default; wait for ack',
    '  scout ask --to hudson --notify "review it"     # background wait, not a fire-and-forget send',
    '  scout ask --as premotion.master.mini --to hudson "build the editor"',
    "  scout ask --to hudson --prompt-file ./handoff.md",
    "",
    "Project targets:",
    '  scout ask --harness codex "review this"        # current project; broker chooses the worker',
    '  scout ask --project ../talkie "compare auth"   # broker resolves the concrete worker',
    '  scout ask --project ../talkie --harness claude "review this from Claude"',
    "  capability request -> project + harness; do not guess generic handles like claude.main",
    "  follow-up -> returned ref/flight/conversation/session handle; pin/name only after routing works",
    "  scout ask '>> project:../talkie compare auth'  # composer route form; quote >> in shells",
    "  use --project when you know the repo path but not the current Scout handle",
    "",
    "Routing:",
    '  scout send --to hudson "ready for review"      # one target -> DM',
    '  scout send --channel triage "need two reviewers"  # explicit group thread',
    '  scout broadcast "deploying in 15m"             # explicit shared broadcast',
    "  no target + no channel                         # error, not fallback",
    "  multiple targets + no channel                  # error, not fallback",
    "",
    "Send vs ask:",
    "  send                                           # FYI/update; no reply or work expected",
    "  ask                                            # reply, judgment, investigation, or work expected",
    "  ask --notify                                   # asynchronous work; return now, report later",
    "  when in doubt                                  # ask",
    "",
    "Addressing:",
    "  @name                              short form; requires exactly one live match",
    "  @name.harness:<codex|claude|...>   pin a specific harness (alias: runtime:)",
    "  @name#codex?<model>                shorthand for harness + model",
    "  @name.profile:<id>                 pin a specific profile (alias: persona:)",
    "  @name.model:<id>                   pin a specific model",
    "  @name.node:<host>                  pin a specific machine",
    "  Dimensions combine, any order: @vox.harness:codex.model:sonnet.node:mini",
    "",
    "MCP parity:",
    "  ask({ projectPath, harness }) handles capability-routed work",
    "  ask({ targetSessionId }) continues exact prior context; messages_send handles tell/update",
    "",
    "Compatibility:",
    "  relay         Namespace alias for ask/send/speak/watch/card",
    "  scout         Canonical CLI binary",
  ].join("\n");
}
