import {
  POPULAR_MODEL_FAMILIES,
  inexpensiveCognitionPick,
} from "./model-economics.js";

export const MODEL_WORLDVIEW_SCHEMA = 1 as const;

export type ModelWorldviewEconomics = {
  input: number;
  output: number;
  context: number | null;
  structuredOutput: boolean | null;
};

export type ModelWorldviewFamily = {
  id: string;
  label: string;
  inexpensive: string;
  budgetFloor: string | null;
  note: string | null;
  economics: ModelWorldviewEconomics | null;
};

export type ModelWorldview = {
  $comment: string;
  schema: typeof MODEL_WORLDVIEW_SCHEMA;
  generatedAt: string;
  source: string;
  popularOrder: string[];
  families: ModelWorldviewFamily[];
};

const COMMENT =
  "Published at https://openscout.app/.well-known/model-worldview.json. "
  + "Generated by `bun packages/agent-sessions/scripts/generate-model-worldview.ts` "
  + "from the curated picks in packages/agent-sessions/src/model-economics.ts — never hand-edit.";

function assertNonBlank(field: string, value: string): void {
  if (!value.trim()) throw new Error(`${field} must not be blank`);
  if (value !== value.trim()) {
    throw new Error(`${field} must not contain surrounding whitespace`);
  }
}

/** Enforce the schema-1 invariants required by downstream consumers. */
export function assertValidModelWorldview(worldview: ModelWorldview): void {
  if (worldview.schema !== MODEL_WORLDVIEW_SCHEMA) {
    throw new Error(`unsupported model worldview schema: ${worldview.schema}`);
  }
  if (!/^\d{4}-\d{2}-\d{2}$/u.test(worldview.generatedAt)) {
    throw new Error(`invalid model worldview generation date: ${worldview.generatedAt}`);
  }
  if (worldview.families.length === 0) {
    throw new Error("model worldview must contain at least one family");
  }

  const ids = new Set<string>();
  const inexpensive = new Set<string>();
  for (const family of worldview.families) {
    assertNonBlank("family id", family.id);
    assertNonBlank(`${family.id} label`, family.label);
    assertNonBlank(`${family.id} inexpensive pick`, family.inexpensive);

    if (ids.has(family.id)) {
      throw new Error(`duplicate model worldview family id: ${family.id}`);
    }
    if (inexpensive.has(family.inexpensive)) {
      throw new Error(`duplicate inexpensive model pick: ${family.inexpensive}`);
    }
    ids.add(family.id);
    inexpensive.add(family.inexpensive);
  }
}

/** Build the complete publishable schema-1 projection without filesystem I/O. */
export function buildModelWorldview(generatedAt: string): ModelWorldview {
  const families = POPULAR_MODEL_FAMILIES.map((family): ModelWorldviewFamily => {
    const pick = inexpensiveCognitionPick(family);
    return {
      id: pick.family,
      label: pick.label,
      inexpensive: pick.inexpensive,
      budgetFloor: pick.budgetFloor ?? null,
      note: pick.note ?? null,
      economics: pick.economics
        ? {
            input: pick.economics.input,
            output: pick.economics.output,
            context: pick.economics.context ?? null,
            structuredOutput: pick.economics.structuredOutput ?? null,
          }
        : null,
    };
  });
  const worldview: ModelWorldview = {
    $comment: COMMENT,
    schema: MODEL_WORLDVIEW_SCHEMA,
    generatedAt,
    source: "models.dev + curated FAMILY_TIER_PICKS",
    popularOrder: [...POPULAR_MODEL_FAMILIES],
    families,
  };

  assertValidModelWorldview(worldview);
  return worldview;
}
