import { describe, expect, test } from "bun:test";
import type { TerminalSessionRecord, TerminalSurface } from "@openscout/protocol";
import {
  collapseHerdrSessionItems,
  compactTerminalPath,
  isAutoGeneratedTerminalSessionName,
  isRelayCapableTerminalBackend,
  partitionTerminalListItems,
  resolveRegisteredTerminalTarget,
  terminalListItems,
  terminalNavGroup,
  terminalSurfaceDescriptorFromRegisteredSurface,
} from "./terminal-sessions.ts";

function terminalSession(
  id: string,
  backend: "tmux" | "zellij",
  sessionName: string,
): TerminalSessionRecord {
  return {
    id,
    harness: backend,
    sourceSessionId: sessionName,
    cwd: "",
    resumeCommand: `${backend} attach ${sessionName}`,
    surfaces: [{
      backend,
      sessionName,
      paneId: null,
      attachCommand: [backend, "attach", sessionName],
      observeCommand: null,
      relay: { backend, sessionName },
      state: "live",
    }],
    createdAt: 1,
    updatedAt: 1,
    metadata: {},
  };
}

describe("terminal session resolution", () => {
  test("resolves backend/session path links by surface key", () => {
    const target = resolveRegisteredTerminalTarget(
      [terminalSession("discovered.zellij.1", "zellij", "hudson-dm79928c")],
      undefined,
      "zellij:hudson-dm79928c",
    );

    expect(target?.session.id).toBe("discovered.zellij.1");
    expect(target?.surface.sessionName).toBe("hudson-dm79928c");
  });

  test("falls back to surface key when a remembered session id is stale", () => {
    const target = resolveRegisteredTerminalTarget(
      [
        terminalSession("ts.old", "zellij", "scout-zj-final-7e55c009"),
        terminalSession("discovered.zellij.1", "zellij", "hudson-dm79928c"),
      ],
      "ts.missing",
      "zellij:hudson-dm79928c",
    );

    expect(target?.session.id).toBe("discovered.zellij.1");
    expect(target?.surface.sessionName).toBe("hudson-dm79928c");
  });
});

describe("relay capability gate", () => {
  test("the relay carries tmux, zellij, and herdr", () => {
    expect(isRelayCapableTerminalBackend("tmux")).toBe(true);
    expect(isRelayCapableTerminalBackend("zellij")).toBe(true);
    expect(isRelayCapableTerminalBackend("herdr")).toBe(true);
    expect(isRelayCapableTerminalBackend("pty")).toBe(false);
    expect(isRelayCapableTerminalBackend(null)).toBe(false);
  });

  test("builds a relay descriptor for a herdr surface", () => {
    const surface = {
      backend: "herdr",
      sessionName: "openscout",
      paneId: null,
      attachCommand: ["herdr", "--session", "openscout"],
      observeCommand: null,
      relay: { backend: "herdr", sessionName: "openscout" },
      state: "live",
    } as TerminalSurface;

    expect(terminalSurfaceDescriptorFromRegisteredSurface(surface)).toEqual({
      backend: "herdr",
      sessionName: "openscout",
      paneId: null,
      socketDir: null,
    });
  });
});

describe("terminal list metadata", () => {
  test("surfaces project and thread context for table rows", () => {
    const [item] = terminalListItems([{
      ...terminalSession("ts.context", "tmux", "relay-openscout-main-dev-mac-mini-local-claude"),
      harness: "claude",
      sourceSessionId: "source-session-1",
      cwd: "/Users/example/dev/openscout",
      metadata: {
        project: "OpenScout",
        threadId: "thread-123",
        currentCommand: "claude",
        currentPath: "/Users/example/dev/openscout",
      },
    }]);

    expect(item?.project).toBe("OpenScout");
    expect(item?.contextKind).toBe("thread");
    expect(item?.contextValue).toBe("thread-123");
    expect(item?.cwdLabel).toBe("dev/openscout");
    expect(item?.searchable).toContain("thread-123");
    expect(item?.searchable).toContain("claude");
  });

  test("derives compact cwd labels", () => {
    expect(compactTerminalPath("/Users/example/dev/openscout/")).toBe("dev/openscout");
  });
});

function backendSession(
  id: string,
  backend: string,
  sessionName: string,
  options: { windows?: number; surfaceCount?: number } = {},
): TerminalSessionRecord {
  const surfaceCount = options.surfaceCount ?? 1;
  return {
    id,
    harness: backend,
    sourceSessionId: sessionName,
    cwd: "",
    resumeCommand: `${backend} attach ${sessionName}`,
    surfaces: Array.from({ length: surfaceCount }, (_, index) => ({
      backend,
      sessionName,
      paneId: index === 0 ? null : `%${index}`,
      attachCommand: [backend, "attach", sessionName],
      observeCommand: null,
      relay: { backend, sessionName },
      state: "live" as const,
    })),
    createdAt: 1,
    updatedAt: 1,
    metadata: options.windows === undefined ? {} : { windows: options.windows },
  };
}

describe("managed session partition", () => {
  test("herdr sessions collapse to one managed row per session name", () => {
    const items = terminalListItems([
      backendSession("discovered.herdr.1", "herdr", "openscout", { surfaceCount: 3 }),
      backendSession("discovered.herdr.2", "herdr", "openscout", { surfaceCount: 1 }),
    ]);
    const { managed, regular } = partitionTerminalListItems(items);

    expect(managed).toHaveLength(1);
    expect(managed[0]?.surface.sessionName).toBe("openscout");
    expect(regular).toHaveLength(0);
  });

  test("multi-window tmux sessions are managed, one row per session", () => {
    const items = terminalListItems([
      backendSession("discovered.tmux.1", "tmux", "teamup", { windows: 3, surfaceCount: 3 }),
    ]);
    const { managed, regular } = partitionTerminalListItems(items);

    expect(managed).toHaveLength(1);
    expect(managed[0]?.session.id).toBe("discovered.tmux.1");
    expect(regular).toHaveLength(0);
  });

  test("single-window and unreported tmux sessions stay regular", () => {
    const items = terminalListItems([
      backendSession("discovered.tmux.1", "tmux", "solo", { windows: 1 }),
      backendSession("discovered.tmux.2", "tmux", "plain"),
    ]);
    const { managed, regular } = partitionTerminalListItems(items);

    expect(managed).toHaveLength(0);
    expect(regular.map((item) => item.session.id)).toEqual([
      "discovered.tmux.1",
      "discovered.tmux.2",
    ]);
  });

  test("zellij and pty sessions stay regular and order is preserved", () => {
    const items = terminalListItems([
      backendSession("discovered.zellij.1", "zellij", "zj-one"),
      backendSession("discovered.herdr.1", "herdr", "openscout"),
      backendSession("scout.pty.1", "pty", "shell"),
      backendSession("discovered.tmux.1", "tmux", "teamup", { windows: 2 }),
      backendSession("discovered.zellij.2", "zellij", "zj-two"),
    ]);
    const { managed, regular } = partitionTerminalListItems(items);

    expect(managed.map((item) => item.surface.sessionName)).toEqual(["openscout", "teamup"]);
    expect(regular.map((item) => item.surface.sessionName)).toEqual(["zj-one", "shell", "zj-two"]);
  });
});

describe("terminal nav grouping", () => {
  test("auto-generated names match Scout's idiom, deliberate names do not", () => {
    expect(isAutoGeneratedTerminalSessionName("session-ms0hf3f7-3ngln1")).toBe(true);
    expect(isAutoGeneratedTerminalSessionName("tmux-mb1x2y3z-9q8w7e")).toBe(true);
    expect(isAutoGeneratedTerminalSessionName("relay-openscout-main-dev-mac-mini-local-claude")).toBe(true);
    expect(isAutoGeneratedTerminalSessionName("claude-ms0hf3f7")).toBe(true);
    expect(isAutoGeneratedTerminalSessionName("scout-tmux-obsidian")).toBe(false);
    expect(isAutoGeneratedTerminalSessionName("da-test2")).toBe(false);
    expect(isAutoGeneratedTerminalSessionName("blink")).toBe(false);
    expect(isAutoGeneratedTerminalSessionName("session-notes")).toBe(false);
  });

  test("groups by backend, origin, and name intentionality", () => {
    const groupOf = (session: TerminalSessionRecord) => {
      const [item] = terminalListItems([session]);
      return item ? terminalNavGroup(item) : null;
    };
    expect(groupOf(backendSession("scout.herdr.1", "herdr", "blink"))).toBe("herdr");
    expect(groupOf({ ...backendSession("discovered.herdr.1", "herdr", "blink"), origin: "discovered" }))
      .toBe("herdr");
    expect(groupOf(backendSession("scout.tmux.1", "tmux", "scout-tmux-obsidian"))).toBe("tmux-named");
    expect(groupOf(backendSession("scout.tmux.2", "tmux", "session-ms0hf3f7-3ngln1"))).toBe("tmux-auto");
    expect(groupOf({ ...backendSession("discovered.tmux.1", "tmux", "teamup"), origin: "discovered" }))
      .toBe("external");
    expect(groupOf(backendSession("scout.zellij.1", "zellij", "zj-one"))).toBe("external");
  });

  test("herdr pane surfaces collapse to one rail row per session", () => {
    const items = terminalListItems([
      backendSession("scout.herdr.1", "herdr", "blink", { surfaceCount: 3 }),
      backendSession("scout.tmux.1", "tmux", "scout-tmux-obsidian"),
    ]);
    const collapsed = collapseHerdrSessionItems(items);

    expect(items).toHaveLength(4);
    expect(collapsed).toHaveLength(2);
    expect(collapsed.map((item) => item.surface.sessionName)).toEqual(["blink", "scout-tmux-obsidian"]);
  });
});
