export const SCOUT_DESKTOP_CHANNELS = {
  getAppInfo: "scout:get-app-info",
  getServicesState: "scout:get-services-state",
  getHomeState: "scout:get-home-state",
  getMessagesWorkspaceState: "scout:get-messages-workspace-state",
  getRelayShellPatch: "scout:get-relay-shell-patch",
  getShellState: "scout:get-shell-state",
  refreshRelayShellPatch: "scout:refresh-relay-shell-patch",
  refreshShellState: "scout:refresh-shell-state",
  getAppSettings: "scout:get-app-settings",
  refreshSettingsInventory: "scout:refresh-settings-inventory",
  updateAppSettings: "scout:update-app-settings",
  retireProject: "scout:retire-project",
  restoreProject: "scout:restore-project",
  runOnboardingCommand: "scout:run-onboarding-command",
  skipOnboarding: "scout:skip-onboarding",
  restartOnboarding: "scout:restart-onboarding",
  getAgentConfig: "scout:get-agent-config",
  updateAgentConfig: "scout:update-agent-config",
  createAgent: "scout:create-agent",
  pickDirectory: "scout:pick-directory",
  reloadApp: "scout:reload-app",
  quitApp: "scout:quit-app",
  revealPath: "scout:reveal-path",
  getPhonePreparation: "scout:get-phone-preparation",
  updatePhonePreparation: "scout:update-phone-preparation",
  getPairingState: "scout:get-pairing-state",
  refreshPairingState: "scout:refresh-pairing-state",
  controlPairingService: "scout:control-pairing-service",
  updatePairingConfig: "scout:update-pairing-config",
  decidePairingApproval: "scout:decide-pairing-approval",
  answerPairingQuestion: "scout:answer-pairing-question",
  restartAgent: "scout:restart-agent",
  sendRelayMessage: "scout:send-relay-message",
  controlBroker: "scout:control-broker",
  getKeepAliveState: "scout:get-keep-alive-state",
  acquireKeepAliveLease: "scout:acquire-keep-alive-lease",
  releaseKeepAliveLease: "scout:release-keep-alive-lease",
  getAgentSession: "scout:get-agent-session",
  answerAgentSessionQuestion: "scout:answer-agent-session-question",
  openAgentSession: "scout:open-agent-session",
  toggleVoiceCapture: "scout:toggle-voice-capture",
  setVoiceRepliesEnabled: "scout:set-voice-replies-enabled",
  getLogCatalog: "scout:get-log-catalog",
  getBrokerInspector: "scout:get-broker-inspector",
  getFeedbackBundle: "scout:get-feedback-bundle",
  submitFeedbackReport: "scout:submit-feedback-report",
  readLogSource: "scout:read-log-source",
  openKnowledgeBase: "scout:open-knowledge-base",
} as const;

export type ScoutDesktopChannelName =
  typeof SCOUT_DESKTOP_CHANNELS[keyof typeof SCOUT_DESKTOP_CHANNELS];
